#!/usr/bin/env python3
"""Emit Helpers/LocalizationCatalog.cs from in-script translation tables."""
from __future__ import annotations

import json
from pathlib import Path

EN: dict[str, str] = {
    "common.on": "On",
    "common.off": "Off",
    "common.apply": "Apply",
    "common.cancel": "Cancel",
    "common.ok": "OK",
    "common.refresh": "Refresh",
    "common.required": "Required",
    "app.title": "PrivacyGuard",
    "app.version": "PrivacyGuard 0.1.0",
    "shell.standardUser": "Standard user",
    "shell.administrator": "Administrator",
    "shell.restartAdmin": "Restart as admin",
    "nav.overview": "Overview",
    "nav.dashboard": "Dashboard",
    "nav.profiles": "Profiles",
    "nav.records": "Records",
    "nav.history": "History",
    "nav.settings": "Settings",
    "dashboard.title": "Privacy dashboard",
    "dashboard.refresh": "Refresh",
    "dashboard.restartBannerTitle": "Restart as administrator to apply changes",
    "dashboard.restartBannerBody": "You can inspect everything now. Machine policy, DiagTrack, and Copilot/Cortana require elevation.",
    "dashboard.restartAdmin": "Restart as administrator",
    "dashboard.adminTitle": "Administrator",
    "dashboard.privacyScore": "Privacy score",
    "dashboard.outOf100": "out of 100",
    "dashboard.whyScore": "Why this score?",
    "dashboard.telemetryTitle": "Telemetry level",
    "dashboard.telemetrySubtitle": "AllowTelemetry policy (0–3)",
    "dashboard.applyTelemetry": "Apply telemetry level",
    "dashboard.telemetryHint": "Security is honored on Enterprise and Education only. Home and Pro treat it as Basic. A restore point is created first.",
    "dashboard.howTitle": "How PrivacyGuard applies changes",
    "dashboard.howBody": "Every change is confirmed, written only through PrivacyService, backed up to SQLite, and can be reverted from History. Critical Windows services are never touched. Advertising and feedback can be toggled as a standard user; services and policy keys need administrator rights.",
    "dashboard.requiresAdmin": "Requires administrator",
    "dashboard.loading": "Loading privacy status…",
    "dashboard.reading": "Reading Windows privacy settings…",
    "dashboard.bannerElevated": "Running as administrator. Changes can be applied immediately.",
    "dashboard.bannerLimited": "Limited access — restart as administrator to change services and machine policy.",
    "dashboard.refreshFailed": "Could not read privacy status. See logs for details.",
    "dashboard.refreshFailedTitle": "Refresh failed",
    "dashboard.alreadySet": "Already set",
    "dashboard.alreadySetMsg": "Telemetry is already at this level.",
    "dashboard.goodShape": "You're in good shape",
    "dashboard.goodShapeMsg": "The recommended privacy profile is already applied.",
    "dashboard.setTelemetry": "Set telemetry to {0}",
    "dashboard.enable": "Enable",
    "dashboard.disable": "Disable",
    "dashboard.confirmBody": "PrivacyGuard will apply the following reversible change(s):\n\n{0}\n\nA restore point is created automatically.",
    "dashboard.changeIncomplete": "Change not fully applied",
    "dashboard.privacyUpdated": "Privacy updated",
    "dashboard.finishedErrors": "Finished with errors",
    "dashboard.changeFailed": "Change failed",
    "dashboard.denied": "Windows denied the change. Restart PrivacyGuard as administrator and try again.",
    "dashboard.noLocalChanges": "No local changes yet",
    "dashboard.lastChanged": "Last changed {0}",
    "dashboard.updated": "Updated {0}",
    "dashboard.improve": "Apply recommended profile",
    "dashboard.improveDone": "Recommended profile applied",
    "dashboard.scoreLoading": "Reading Windows privacy settings…",
    "dashboard.scoreProtected": "Most optional collection is limited. You can still tighten a few services.",
    "dashboard.scorePartial": "Some advertising and diagnostic options are still on. Recommended profile will close the gaps.",
    "dashboard.scoreCollecting": "Windows is using default collection. Apply the recommended profile for a safer baseline.",
    "health.protected": "Protected",
    "health.needsAttention": "Needs attention",
    "health.collecting": "Collecting data",
    "health.unknown": "Unknown",
    "health.partial": "Partial",
    "health.limited": "Limited",
    "health.mixed": "Mixed",
    "dashboard.section.core": "Core telemetry",
    "dashboard.section.coreSub": "Diagnostic data Windows may send, and the services that carry it.",
    "dashboard.section.ads": "Advertising & personalization",
    "dashboard.section.adsSub": "Identifiers and history used to tailor ads, tips, and Timeline.",
    "dashboard.section.ai": "AI & assistant features",
    "dashboard.section.aiSub": "Cortana policy and Copilot visibility on this device.",
    "dashboard.section.other": "Other",
    "dashboard.section.otherSub": "Feedback prompts and remaining privacy-related options.",
    "telemetry.security": "Security — Enterprise only",
    "telemetry.basic": "Basic — recommended",
    "telemetry.enhanced": "Enhanced",
    "telemetry.full": "Full — Windows default",
    "telemetry.value.security": "Security",
    "telemetry.value.basic": "Basic",
    "telemetry.value.enhanced": "Enhanced",
    "telemetry.value.full": "Full",
    "common.windowsDefault": "Windows default",
    "service.running": "Running",
    "service.stopped": "Stopped",
    "service.automatic": "Automatic",
    "service.manual": "Manual",
    "service.disabled": "Disabled",
    "service.missing": "Not installed",
    "setting.telemetry": "Windows Telemetry",
    "setting.diagTrack": "Connected User Experiences (DiagTrack)",
    "setting.dmw": "WAP Push Message Routing (dmwappushservice)",
    "setting.advertising": "Advertising ID",
    "setting.activity": "Activity History / Timeline",
    "setting.cortana": "Cortana",
    "setting.copilot": "Windows Copilot",
    "setting.feedback": "Feedback & Diagnostics prompts",
    "setting.tailored": "Tailored experiences",
    "setting.telemetry.desc": "How much diagnostic data Windows may send to Microsoft (AllowTelemetry).",
    "setting.diagTrack.desc": "Implements Connected User Experiences and Telemetry. Stopping it reduces telemetry but may affect some diagnostics.",
    "setting.dmw.desc": "WAP push routing used by some telemetry and MDM scenarios. Safe to disable for most home users.",
    "setting.advertising.desc": "Identifier apps can use to show more relevant ads across experiences.",
    "setting.activity.desc": "Collects app and browsing activity for Timeline and cross-device resume.",
    "setting.cortana.desc": "Policy AllowCortana. On Windows 11 this mainly affects leftover Cortana components.",
    "setting.copilot.desc": "Policy TurnOffWindowsCopilot. Effectiveness depends on Windows build and how Copilot is installed.",
    "setting.feedback.desc": "Frequency of Feedback Hub and satisfaction prompts.",
    "setting.tailored.desc": "Uses diagnostic data to personalize tips, ads, and recommendations.",
    "setting.telemetry.side": "Enterprise-only Security level is ignored on Home/Pro (Windows raises it to Basic).",
    "setting.diagTrack.side": "Optional diagnostic experiences and some feedback/telemetry features may stop. Windows Update continues to work.",
    "setting.dmw.side": "Rare WAP push / some MDM delivery scenarios may be affected.",
    "setting.cortana.side": "Cortana (if present) will be policy-disabled. Windows Search itself stays available.",
    "setting.copilot.side": "Copilot UI may be hidden or ignored depending on your Windows build. A sign-out can be required.",
    "setting.activity.side": "Timeline and cross-device activity resume will stop.",
    "factor.telemetry": "Telemetry level",
    "factor.diagTrack": "DiagTrack",
    "factor.dmw": "WAP Push service",
    "factor.advertising": "Advertising ID",
    "factor.activity": "Activity history",
    "factor.cortana": "Cortana",
    "factor.copilot": "Copilot",
    "factor.feedback": "Feedback prompts",
    "factor.tailored": "Tailored experiences",
    "profile.recommended.title": "Recommended Privacy",
    "profile.recommended.summary": "Cuts advertising and optional diagnostics while keeping Windows Update and security healthy.",
    "profile.recommended.details": "Telemetry: Basic. Advertising ID off. Activity upload off. Feedback prompts off. DiagTrack left running so Windows Update diagnostics still work.",
    "profile.recommended.warning": "Some personalized tips, ads, and timeline sync will stop. This does not affect Windows Security or Update.",
    "profile.recommended.h1": "Telemetry: Basic",
    "profile.recommended.h2": "Advertising ID off",
    "profile.recommended.h3": "Activity history off",
    "profile.recommended.h4": "Feedback prompts off",
    "profile.recommended.h5": "DiagTrack stays running",
    "profile.maximum.title": "Maximum Privacy",
    "profile.maximum.summary": "Most restrictive supported configuration. Some optional Windows experiences may break.",
    "profile.maximum.details": "Telemetry: Security (or Basic on Home/Pro). DiagTrack and dmwappushservice stopped. Advertising, activity history, Cortana/Copilot policy, and feedback off.",
    "profile.maximum.warning": "Search highlights, timeline, optional diagnostic experiences, and some Store personalization may stop working. Reversible from History or Restore Default. On Home/Pro, Windows will not honor Security (0) telemetry.",
    "profile.maximum.h1": "Telemetry: Security or Basic",
    "profile.maximum.h2": "DiagTrack stopped",
    "profile.maximum.h3": "WAP Push disabled",
    "profile.maximum.h4": "Ads, Timeline, Copilot off",
    "profile.maximum.h5": "Feedback & tailored off",
    "profile.balanced.title": "Balanced",
    "profile.balanced.summary": "Keeps diagnostic services running, turns off advertising ID and activity upload.",
    "profile.balanced.details": "Telemetry: Full. DiagTrack running. Advertising ID off. Local activity allowed, cloud upload off. Copilot left unchanged.",
    "profile.balanced.warning": "Windows will still send optional diagnostic data. Only advertising and activity upload are reduced.",
    "profile.balanced.h1": "Telemetry: Full",
    "profile.balanced.h2": "DiagTrack running",
    "profile.balanced.h3": "Advertising ID off",
    "profile.balanced.h4": "Activity upload off",
    "profile.balanced.h5": "Copilot unchanged",
    "profile.restore.title": "Restore Default",
    "profile.restore.summary": "Removes PrivacyGuard policy values and returns services to typical Windows defaults.",
    "profile.restore.details": "Deletes AllowTelemetry policy, re-enables DiagTrack (Automatic + Running), restores advertising ID, activity history, Cortana/Copilot, and feedback to defaults.",
    "profile.restore.warning": "This restores data-collection defaults. It does not roll back unrelated third-party tweaks.",
    "profile.restore.h1": "Telemetry: Windows default",
    "profile.restore.h2": "DiagTrack automatic",
    "profile.restore.h3": "Advertising ID on",
    "profile.restore.h4": "Activity history on",
    "profile.restore.h5": "Cortana & Copilot restored",
    "profiles.title": "Privacy profiles",
    "profiles.subtitle": "One-click configurations. Each apply shows a confirmation, creates a restore point, and is fully reversible.",
    "profiles.safety": "Safety",
    "profiles.recommendedBadge": "Recommended",
    "profiles.active": "Active",
    "profiles.beforeContinue": "Before you continue",
    "profiles.scoreNone": "Score impact: no change",
    "profiles.scoreUp": "Score impact: +{0}",
    "profiles.scoreDown": "Score impact: {0}",
    "profiles.scoreUnknown": "Score impact: —",
    "profiles.lastApplied": "Last applied: {0} at {1}",
    "profiles.today": "Today",
    "profiles.yesterday": "Yesterday",
    "profiles.review": "Review and apply",
    "profiles.currentlyApplied": "Currently applied",
    "profiles.alreadyTitle": "Already applied",
    "profiles.alreadyMsg": "{0} is already applied.",
    "profiles.adminTitle": "Administrator required",
    "profiles.adminBody": "This profile changes machine-wide policy or services. Restart PrivacyGuard as administrator, then apply it again.",
    "profiles.applyTitle": "Apply {0}?",
    "profiles.confirmBody": "The following reversible changes will be applied:\n\n{0}",
    "profiles.appliedTitle": "Profile applied",
    "profiles.partialTitle": "Profile partially applied",
    "profiles.failedTitle": "Profile failed",
    "profiles.choose": "Choose a profile. Every apply creates a restore point first.",
    "history.title": "Change history",
    "history.subtitle": "Every mutation is recorded locally. Revert a single setting or restore a full backup point.",
    "history.audit": "Local audit log",
    "history.changes": "Changes",
    "history.filterAll": "All",
    "history.filterActive": "Active",
    "history.filterReverted": "Reverted",
    "history.revertSelected": "Revert selected",
    "history.revertN": "Revert {0} changes",
    "history.noneSelected": "None selected",
    "history.changeSelectedOne": "1 change selected",
    "history.changeSelectedMany": "{0} changes selected",
    "history.restoreSelectedOne": "1 restore point selected",
    "history.restoreSelectedMany": "{0} restore points selected",
    "history.emptyTitle": "No history yet",
    "history.emptyFilterTitle": "No matching changes",
    "history.emptyMsg": "No changes yet. Apply a profile or toggle a setting and it will show up here.",
    "history.emptyFilterMsg": "No changes match this filter.",
    "history.statusEmpty": "No changes yet. Applied settings will appear here.",
    "history.statusCounts": "{0} recorded change(s), {1} restore point(s).",
    "history.unavailable": "History unavailable",
    "history.alreadyRevertedTitle": "Already reverted",
    "history.alreadyRevertedBody": "The selected history item(s) were already marked as reverted.",
    "history.revertOne": "Revert this change?",
    "history.revertMany": "Revert {0} changes?",
    "history.revertBody": "The following reversible changes will be restored:\n\n{0}",
    "history.revertWarning": "A new restore point will be created before each revert.",
    "history.revertFailed": "Revert failed",
    "history.restoreTitle": "Restore this backup?",
    "history.restoreBody": "Restore point #{0} from {1} will be re-applied ({2} setting(s)).",
    "history.restoreWarning": "Current values are backed up first so this restore is itself reversible.",
    "history.restoreFailed": "Restore failed",
    "history.restored": "Restored",
    "history.restorePoints": "Restore points",
    "history.restorePointsSub": "Snapshots taken before each mutation.",
    "history.noRestoreTitle": "No restore points yet",
    "history.noRestoreBody": "A snapshot will appear here the first time a setting is changed.",
    "history.restoreButton": "Restore selected backup",
    "history.reverted": "Reverted",
    "history.manualChange": "Manual change",
    "history.restorePointN": "Restore point #{0}",
    "history.settingKey": "Setting key: ",
    "history.source": "Source: ",
    "history.today": "Today",
    "history.yesterday": "Yesterday",
    "history.earlier": "Earlier",
    "history.settingCapturedOne": "1 setting captured",
    "history.settingCapturedMany": "{0} settings captured",
    "history.storedLocally": "Change history is stored locally in SQLite.",
    "settings.title": "Settings",
    "settings.subtitle": "App preferences only. Windows privacy settings live on the Dashboard and Profiles pages.",
    "settings.appearance": "Appearance",
    "settings.theme": "Theme",
    "settings.themeDesc": "Follow Windows, or force a light or dark theme.",
    "settings.themeDefault": "Windows default",
    "settings.themeDefaultSub": "Match the system theme",
    "settings.themeLight": "Light",
    "settings.themeLightSub": "Always use a light theme",
    "settings.themeDark": "Dark",
    "settings.themeDarkSub": "Always use a dark theme",
    "settings.language": "Language",
    "settings.languageDesc": "Changes the entire PrivacyGuard interface. Dates and numbers follow this language too.",
    "settings.languagePlaceholder": "Search languages",
    "settings.startup": "Startup & safety",
    "settings.startWindows": "Start with Windows",
    "settings.startWindowsDesc": "Adds or removes a current-user Run key. Does not require administrator rights.",
    "settings.confirm": "Confirm before applying changes",
    "settings.confirmDesc": "Confirmation dialogs are always shown before PrivacyGuard changes Windows. This switch is locked on for safety.",
    "settings.confirmLock": "Always required for safety",
    "settings.record": "Record change history",
    "settings.recordDesc": "Write every setting mutation to the local SQLite database.",
    "settings.data": "Data",
    "settings.logs": "Log files",
    "settings.openFolder": "Open folder",
    "settings.database": "History database",
    "settings.about": "About",
    "settings.aboutBody": "Unified Privacy & Telemetry Control Dashboard for Windows 10/11. Changes are reversible and never target critical OS services.",
    "settings.checkUpdates": "Check for updates",
    "settings.upToDate": "You're up to date",
    "settings.upToDateBody": "PrivacyGuard 0.1.0 is the current build. Automatic update checks will be added in a later release.",
    "settings.autoStart": "Auto-start",
    "settings.autoStartError": "Could not update the current-user Run key.",
    "dialog.beforeContinue": "Before you continue",
    "privacy.nothingToChange": "Nothing to change — the system already matches the requested state.",
    "privacy.refusedUnknown": "Refused unknown setting '{0}'.",
    "privacy.needsAdmin": "This change requires administrator rights. Use Restart as administrator, then try again.",
    "privacy.applied": "Applied {0} change(s). Restore point #{1} was saved.",
    "privacy.completedErrors": "Completed with {0} error(s). Restore point #{1} is available.",
    "privacy.couldNotComplete": "The change could not be completed. {0}",
    "privacy.revertReason": "Revert: {0}",
    "privacy.restoreReason": "Restore point #{0}",
    "privacy.telemetryRange": "Telemetry level must be 0–3.",
    "privacy.telemetryRestoreFail": "Could not restore the telemetry policy. Administrator rights are required.",
    "privacy.telemetryWriteFail": "Could not write AllowTelemetry. Administrator rights are required.",
    "privacy.serviceNotAllowed": "Service '{0}' is not allowlisted.",
    "privacy.advertisingFail": "Could not update Advertising ID.",
    "privacy.activityFail": "Could not update Activity History policy. Administrator rights are required.",
    "privacy.cortanaRestoreFail": "Could not restore Cortana policy.",
    "privacy.cortanaWriteFail": "Could not write AllowCortana. Administrator rights are required.",
    "privacy.copilotRestoreFail": "Could not restore Copilot policy.",
    "privacy.copilotWriteFail": "Could not write TurnOffWindowsCopilot. Administrator rights are required.",
    "privacy.feedbackFail": "Could not update feedback rules.",
    "privacy.tailoredFail": "Could not update tailored experiences.",
    "privacy.notImplemented": "Setting '{0}' is not implemented.",
    "privacy.collectingData": "Collecting data",
    "preview.hintLead": "Browser preview only",
    "preview.hintBody": " — looks like the WinUI 3 app. It does not control Windows.",
    "preview.toggleTheme": "Toggle light / dark",
    "preview.dialogBody": "PrivacyGuard will apply a reversible change. A restore point is created automatically.",
    "preview.dialogMac": "This preview cannot change your Mac. On Windows, this dialog is required before any registry or service write.",
    "preview.sampleData": "Preview sample data",
    "preview.edition": "Windows 11 24H2 (Professional) — sample",
    "preview.sampleBanner": "Sample data for this preview. On Windows this page shows your real local history.",
    "preview.openFolder": "On Windows this opens %LocalAppData%\\PrivacyGuard\\logs\\.",
    "preview.appliedDemo": "Preview only — no Windows settings were changed.",
    "shell.elevationCancelled": "Administrator restart cancelled",
    "shell.elevationCancelledBody": "You are still a standard user. Restart as admin to change services and machine policy.",
    "shell.elevationFailed": "Could not restart as administrator",
    "shell.elevationFailedBody": "Windows did not relaunch PrivacyGuard elevated. Try again from the title bar.",
    "privacy.serviceStartTypeAdmin": "Could not change start type of '{0}'. Administrator rights are required.",
    "privacy.serviceWin32": "Could not change '{0}'. {1}",
    "privacy.serviceRefused": "Windows refused the change to '{0}'. {1}",
    "privacy.serviceUnexpected": "Unexpected error changing '{0}'.",
    "settings.openFolderError": "Could not open the logs folder.",
}

PT: dict[str, str] = {
    "common.on": "Ativado",
    "common.off": "Desativado",
    "common.apply": "Aplicar",
    "common.cancel": "Cancelar",
    "common.ok": "OK",
    "common.refresh": "Atualizar",
    "common.required": "Obrigatório",
    "shell.standardUser": "Usuário padrão",
    "shell.administrator": "Administrador",
    "shell.restartAdmin": "Reiniciar como admin",
    "nav.overview": "Visão geral",
    "nav.dashboard": "Painel",
    "nav.profiles": "Perfis",
    "nav.records": "Registros",
    "nav.history": "Histórico",
    "nav.settings": "Configurações",
    "dashboard.title": "Painel de privacidade",
    "dashboard.refresh": "Atualizar",
    "dashboard.restartBannerTitle": "Reinicie como administrador para aplicar alterações",
    "dashboard.restartBannerBody": "Você já pode inspecionar tudo. Política da máquina, DiagTrack e Copilot/Cortana exigem elevação.",
    "dashboard.restartAdmin": "Reiniciar como administrador",
    "dashboard.adminTitle": "Administrador",
    "dashboard.privacyScore": "Pontuação de privacidade",
    "dashboard.outOf100": "de 100",
    "dashboard.whyScore": "Por que esta pontuação?",
    "dashboard.telemetryTitle": "Nível de telemetria",
    "dashboard.telemetrySubtitle": "Política AllowTelemetry (0–3)",
    "dashboard.applyTelemetry": "Aplicar nível de telemetria",
    "dashboard.telemetryHint": "Segurança só vale em Enterprise e Education. Home e Pro tratam como Básico. Um ponto de restauração é criado primeiro.",
    "dashboard.howTitle": "Como o PrivacyGuard aplica alterações",
    "dashboard.howBody": "Toda alteração é confirmada, escrita apenas pelo PrivacyService, salva no SQLite e pode ser revertida no Histórico. Serviços críticos do Windows nunca são alterados. Publicidade e feedback podem ser trocados como usuário padrão; serviços e chaves de política precisam de administrador.",
    "dashboard.requiresAdmin": "Requer administrador",
    "dashboard.loading": "Carregando status de privacidade…",
    "dashboard.reading": "Lendo as configurações de privacidade do Windows…",
    "dashboard.bannerElevated": "Executando como administrador. As alterações podem ser aplicadas imediatamente.",
    "dashboard.bannerLimited": "Acesso limitado — reinicie como administrador para alterar serviços e política da máquina.",
    "dashboard.refreshFailed": "Não foi possível ler o status de privacidade. Consulte os logs.",
    "dashboard.refreshFailedTitle": "Falha ao atualizar",
    "dashboard.alreadySet": "Já definido",
    "dashboard.alreadySetMsg": "A telemetria já está neste nível.",
    "dashboard.goodShape": "Tudo certo",
    "dashboard.goodShapeMsg": "O perfil de privacidade recomendado já está aplicado.",
    "dashboard.setTelemetry": "Definir telemetria como {0}",
    "dashboard.enable": "Ativar",
    "dashboard.disable": "Desativar",
    "dashboard.confirmBody": "O PrivacyGuard aplicará as seguintes alterações reversíveis:\n\n{0}\n\nUm ponto de restauração é criado automaticamente.",
    "dashboard.changeIncomplete": "Alteração não aplicada por completo",
    "dashboard.privacyUpdated": "Privacidade atualizada",
    "dashboard.finishedErrors": "Concluído com erros",
    "dashboard.changeFailed": "Falha na alteração",
    "dashboard.denied": "O Windows recusou a alteração. Reinicie o PrivacyGuard como administrador e tente de novo.",
    "dashboard.noLocalChanges": "Nenhuma alteração local ainda",
    "dashboard.lastChanged": "Última alteração {0}",
    "dashboard.updated": "Atualizado {0}",
    "dashboard.improve": "Aplicar perfil recomendado",
    "dashboard.improveDone": "Perfil recomendado aplicado",
    "dashboard.scoreLoading": "Lendo as configurações de privacidade do Windows…",
    "dashboard.scoreProtected": "A maior parte da coleta opcional está limitada. Ainda é possível reforçar alguns serviços.",
    "dashboard.scorePartial": "Algumas opções de publicidade e diagnóstico ainda estão ativas. O perfil recomendado fecha as lacunas.",
    "dashboard.scoreCollecting": "O Windows está usando a coleta padrão. Aplique o perfil recomendado para uma base mais segura.",
    "health.protected": "Protegido",
    "health.needsAttention": "Precisa de atenção",
    "health.collecting": "Coletando dados",
    "health.unknown": "Desconhecido",
    "health.partial": "Parcial",
    "health.limited": "Limitado",
    "health.mixed": "Misto",
    "dashboard.section.core": "Telemetria principal",
    "dashboard.section.coreSub": "Dados de diagnóstico que o Windows pode enviar e os serviços que os transportam.",
    "dashboard.section.ads": "Publicidade e personalização",
    "dashboard.section.adsSub": "Identificadores e histórico usados para anúncios, dicas e Timeline.",
    "dashboard.section.ai": "IA e assistentes",
    "dashboard.section.aiSub": "Política da Cortana e visibilidade do Copilot neste dispositivo.",
    "dashboard.section.other": "Outros",
    "dashboard.section.otherSub": "Solicitações de feedback e demais opções de privacidade.",
    "telemetry.security": "Segurança — somente Enterprise",
    "telemetry.basic": "Básico — recomendado",
    "telemetry.enhanced": "Aprimorado",
    "telemetry.full": "Completo — padrão do Windows",
    "telemetry.value.security": "Segurança",
    "telemetry.value.basic": "Básico",
    "telemetry.value.enhanced": "Aprimorado",
    "telemetry.value.full": "Completo",
    "common.windowsDefault": "Padrão do Windows",
    "service.running": "Em execução",
    "service.stopped": "Parado",
    "service.automatic": "Automático",
    "service.manual": "Manual",
    "service.disabled": "Desativado",
    "service.missing": "Não instalado",
    "setting.telemetry": "Telemetria do Windows",
    "setting.diagTrack": "Experiências do usuário conectadas (DiagTrack)",
    "setting.dmw": "Roteamento de mensagens WAP Push (dmwappushservice)",
    "setting.advertising": "ID de publicidade",
    "setting.activity": "Histórico de atividades / Timeline",
    "setting.cortana": "Cortana",
    "setting.copilot": "Windows Copilot",
    "setting.feedback": "Solicitações de feedback e diagnóstico",
    "setting.tailored": "Experiências personalizadas",
    "setting.telemetry.desc": "Quanto dado de diagnóstico o Windows pode enviar à Microsoft (AllowTelemetry).",
    "setting.diagTrack.desc": "Implementa Experiências do usuário conectadas e Telemetria. Parar reduz a telemetria, mas pode afetar alguns diagnósticos.",
    "setting.dmw.desc": "Roteamento WAP Push usado em alguns cenários de telemetria e MDM. Seguro desativar para a maioria dos usuários domésticos.",
    "setting.advertising.desc": "Identificador que os apps podem usar para anúncios mais relevantes.",
    "setting.activity.desc": "Coleta atividade de apps e navegação para Timeline e retomada entre dispositivos.",
    "setting.cortana.desc": "Política AllowCortana. No Windows 11 afeta principalmente componentes restantes da Cortana.",
    "setting.copilot.desc": "Política TurnOffWindowsCopilot. A eficácia depende da build e de como o Copilot está instalado.",
    "setting.feedback.desc": "Frequência do Feedback Hub e de pesquisas de satisfação.",
    "setting.tailored.desc": "Usa dados de diagnóstico para personalizar dicas, anúncios e recomendações.",
    "setting.telemetry.side": "O nível Segurança só de Enterprise é ignorado no Home/Pro (o Windows sobe para Básico).",
    "setting.diagTrack.side": "Experiências de diagnóstico opcionais e alguns recursos de feedback/telemetria podem parar. O Windows Update continua funcionando.",
    "setting.dmw.side": "Cenários raros de WAP Push / entrega MDM podem ser afetados.",
    "setting.cortana.side": "A Cortana (se presente) será desativada por política. A Pesquisa do Windows permanece disponível.",
    "setting.copilot.side": "A interface do Copilot pode ser ocultada ou ignorada, conforme a build. Pode ser necessário sair da conta.",
    "setting.activity.side": "A Timeline e a retomada de atividade entre dispositivos serão interrompidas.",
    "factor.telemetry": "Nível de telemetria",
    "factor.diagTrack": "DiagTrack",
    "factor.dmw": "Serviço WAP Push",
    "factor.advertising": "ID de publicidade",
    "factor.activity": "Histórico de atividades",
    "factor.cortana": "Cortana",
    "factor.copilot": "Copilot",
    "factor.feedback": "Solicitações de feedback",
    "factor.tailored": "Experiências personalizadas",
    "profile.recommended.title": "Privacidade recomendada",
    "profile.recommended.summary": "Reduz publicidade e diagnósticos opcionais, mantendo o Windows Update e a segurança saudáveis.",
    "profile.recommended.details": "Telemetria: Básico. ID de publicidade desativado. Envio de atividade desativado. Feedback desativado. DiagTrack continua em execução para diagnósticos do Update.",
    "profile.recommended.warning": "Algumas dicas personalizadas, anúncios e sincronização da Timeline param. Isso não afeta o Windows Security nem o Update.",
    "profile.recommended.h1": "Telemetria: Básico",
    "profile.recommended.h2": "ID de publicidade desativado",
    "profile.recommended.h3": "Histórico de atividades desativado",
    "profile.recommended.h4": "Feedback desativado",
    "profile.recommended.h5": "DiagTrack continua em execução",
    "profile.maximum.title": "Privacidade máxima",
    "profile.maximum.summary": "Configuração mais restritiva suportada. Algumas experiências opcionais do Windows podem quebrar.",
    "profile.maximum.details": "Telemetria: Segurança (ou Básico no Home/Pro). DiagTrack e dmwappushservice parados. Publicidade, histórico, política Cortana/Copilot e feedback desativados.",
    "profile.maximum.warning": "Destaques de pesquisa, Timeline, diagnósticos opcionais e alguma personalização da Store podem parar. Reversível pelo Histórico ou Restaurar padrão. No Home/Pro, o Windows não honra telemetria Segurança (0).",
    "profile.maximum.h1": "Telemetria: Segurança ou Básico",
    "profile.maximum.h2": "DiagTrack parado",
    "profile.maximum.h3": "WAP Push desativado",
    "profile.maximum.h4": "Anúncios, Timeline e Copilot desativados",
    "profile.maximum.h5": "Feedback e experiências desativados",
    "profile.balanced.title": "Equilibrado",
    "profile.balanced.summary": "Mantém os serviços de diagnóstico em execução e desativa ID de publicidade e envio de atividade.",
    "profile.balanced.details": "Telemetria: Completa. DiagTrack em execução. ID de publicidade desativado. Atividade local permitida, envio à nuvem desativado. Copilot inalterado.",
    "profile.balanced.warning": "O Windows ainda enviará dados de diagnóstico opcionais. Só publicidade e envio de atividade são reduzidos.",
    "profile.balanced.h1": "Telemetria: Completa",
    "profile.balanced.h2": "DiagTrack em execução",
    "profile.balanced.h3": "ID de publicidade desativado",
    "profile.balanced.h4": "Envio de atividade desativado",
    "profile.balanced.h5": "Copilot inalterado",
    "profile.restore.title": "Restaurar padrão",
    "profile.restore.summary": "Remove os valores de política do PrivacyGuard e devolve os serviços aos padrões típicos do Windows.",
    "profile.restore.details": "Exclui a política AllowTelemetry, reativa o DiagTrack (Automático + Em execução) e restaura publicidade, histórico, Cortana/Copilot e feedback.",
    "profile.restore.warning": "Isto restaura os padrões de coleta de dados. Não desfaz ajustes de terceiros não relacionados.",
    "profile.restore.h1": "Telemetria: padrão do Windows",
    "profile.restore.h2": "DiagTrack automático",
    "profile.restore.h3": "ID de publicidade ativado",
    "profile.restore.h4": "Histórico de atividades ativado",
    "profile.restore.h5": "Cortana e Copilot restaurados",
    "profiles.title": "Perfis de privacidade",
    "profiles.subtitle": "Configurações com um clique. Cada aplicação pede confirmação, cria um ponto de restauração e é totalmente reversível.",
    "profiles.safety": "Segurança",
    "profiles.recommendedBadge": "Recomendado",
    "profiles.active": "Ativo",
    "profiles.beforeContinue": "Antes de continuar",
    "profiles.scoreNone": "Impacto na pontuação: nenhuma alteração",
    "profiles.scoreUp": "Impacto na pontuação: +{0}",
    "profiles.scoreDown": "Impacto na pontuação: {0}",
    "profiles.scoreUnknown": "Impacto na pontuação: —",
    "profiles.lastApplied": "Última aplicação: {0} às {1}",
    "profiles.today": "Hoje",
    "profiles.yesterday": "Ontem",
    "profiles.review": "Revisar e aplicar",
    "profiles.currentlyApplied": "Aplicado atualmente",
    "profiles.alreadyTitle": "Já aplicado",
    "profiles.alreadyMsg": "{0} já está aplicado.",
    "profiles.adminTitle": "Administrador necessário",
    "profiles.adminBody": "Este perfil altera política ou serviços de toda a máquina. Reinicie o PrivacyGuard como administrador e aplique de novo.",
    "profiles.applyTitle": "Aplicar {0}?",
    "profiles.confirmBody": "As seguintes alterações reversíveis serão aplicadas:\n\n{0}",
    "profiles.appliedTitle": "Perfil aplicado",
    "profiles.partialTitle": "Perfil aplicado parcialmente",
    "profiles.failedTitle": "Falha no perfil",
    "profiles.choose": "Escolha um perfil. Toda aplicação cria um ponto de restauração primeiro.",
    "history.title": "Histórico de alterações",
    "history.subtitle": "Cada mutação é registrada localmente. Reverta uma configuração ou restaure um ponto de backup completo.",
    "history.audit": "Registro de auditoria local",
    "history.changes": "Alterações",
    "history.filterAll": "Todas",
    "history.filterActive": "Ativas",
    "history.filterReverted": "Revertidas",
    "history.revertSelected": "Reverter selecionadas",
    "history.revertN": "Reverter {0} alterações",
    "history.noneSelected": "Nenhuma selecionada",
    "history.changeSelectedOne": "1 alteração selecionada",
    "history.changeSelectedMany": "{0} alterações selecionadas",
    "history.restoreSelectedOne": "1 ponto de restauração selecionado",
    "history.restoreSelectedMany": "{0} pontos de restauração selecionados",
    "history.emptyTitle": "Nenhum histórico ainda",
    "history.emptyFilterTitle": "Nenhuma alteração correspondente",
    "history.emptyMsg": "Ainda não há alterações. Aplique um perfil ou altere uma configuração para aparecer aqui.",
    "history.emptyFilterMsg": "Nenhuma alteração corresponde a este filtro.",
    "history.statusEmpty": "Ainda não há alterações. As configurações aplicadas aparecerão aqui.",
    "history.statusCounts": "{0} alteração(ões) registrada(s), {1} ponto(s) de restauração.",
    "history.unavailable": "Histórico indisponível",
    "history.alreadyRevertedTitle": "Já revertido",
    "history.alreadyRevertedBody": "Os itens de histórico selecionados já estavam marcados como revertidos.",
    "history.revertOne": "Reverter esta alteração?",
    "history.revertMany": "Reverter {0} alterações?",
    "history.revertBody": "As seguintes alterações reversíveis serão restauradas:\n\n{0}",
    "history.revertWarning": "Um novo ponto de restauração será criado antes de cada reversão.",
    "history.revertFailed": "Falha ao reverter",
    "history.restoreTitle": "Restaurar este backup?",
    "history.restoreBody": "O ponto de restauração nº {0} de {1} será reaplicado ({2} configuração(ões)).",
    "history.restoreWarning": "Os valores atuais são salvos primeiro, então esta restauração também é reversível.",
    "history.restoreFailed": "Falha na restauração",
    "history.restored": "Restaurado",
    "history.restorePoints": "Pontos de restauração",
    "history.restorePointsSub": "Instantâneos feitos antes de cada mutação.",
    "history.noRestoreTitle": "Nenhum ponto de restauração ainda",
    "history.noRestoreBody": "Um instantâneo aparecerá aqui na primeira alteração de configuração.",
    "history.restoreButton": "Restaurar backup selecionado",
    "history.reverted": "Revertido",
    "history.manualChange": "Alteração manual",
    "history.restorePointN": "Ponto de restauração nº {0}",
    "history.settingKey": "Chave da configuração: ",
    "history.source": "Origem: ",
    "history.today": "Hoje",
    "history.yesterday": "Ontem",
    "history.earlier": "Anterior",
    "history.settingCapturedOne": "1 configuração capturada",
    "history.settingCapturedMany": "{0} configurações capturadas",
    "history.storedLocally": "O histórico de alterações é armazenado localmente no SQLite.",
    "settings.title": "Configurações",
    "settings.subtitle": "Apenas preferências do app. As configurações de privacidade do Windows ficam no Painel e em Perfis.",
    "settings.appearance": "Aparência",
    "settings.theme": "Tema",
    "settings.themeDesc": "Siga o Windows ou force um tema claro ou escuro.",
    "settings.themeDefault": "Padrão do Windows",
    "settings.themeDefaultSub": "Combinar com o tema do sistema",
    "settings.themeLight": "Claro",
    "settings.themeLightSub": "Usar sempre o tema claro",
    "settings.themeDark": "Escuro",
    "settings.themeDarkSub": "Usar sempre o tema escuro",
    "settings.language": "Idioma",
    "settings.languageDesc": "Altera toda a interface do PrivacyGuard. Datas e números também seguem este idioma.",
    "settings.languagePlaceholder": "Buscar idiomas",
    "settings.startup": "Inicialização e segurança",
    "settings.startWindows": "Iniciar com o Windows",
    "settings.startWindowsDesc": "Adiciona ou remove uma chave Run do usuário atual. Não exige direitos de administrador.",
    "settings.confirm": "Confirmar antes de aplicar alterações",
    "settings.confirmDesc": "Os diálogos de confirmação sempre aparecem antes de o PrivacyGuard alterar o Windows. Esta opção fica bloqueada por segurança.",
    "settings.confirmLock": "Sempre obrigatório por segurança",
    "settings.record": "Registrar histórico de alterações",
    "settings.recordDesc": "Grava cada mutação de configuração no banco SQLite local.",
    "settings.data": "Dados",
    "settings.logs": "Arquivos de log",
    "settings.openFolder": "Abrir pasta",
    "settings.database": "Banco de histórico",
    "settings.about": "Sobre",
    "settings.aboutBody": "Painel unificado de privacidade e telemetria para Windows 10/11. As alterações são reversíveis e nunca atingem serviços críticos do sistema.",
    "settings.checkUpdates": "Verificar atualizações",
    "settings.upToDate": "Você está atualizado",
    "settings.upToDateBody": "O PrivacyGuard 0.1.0 é a build atual. A verificação automática de atualizações será adicionada em uma versão posterior.",
    "settings.autoStart": "Inicialização automática",
    "settings.autoStartError": "Não foi possível atualizar a chave Run do usuário atual.",
    "dialog.beforeContinue": "Antes de continuar",
    "privacy.nothingToChange": "Nada a alterar — o sistema já está no estado solicitado.",
    "privacy.refusedUnknown": "Configuração desconhecida recusada: '{0}'.",
    "privacy.needsAdmin": "Esta alteração exige direitos de administrador. Use Reiniciar como administrador e tente de novo.",
    "privacy.applied": "{0} alteração(ões) aplicada(s). O ponto de restauração nº {1} foi salvo.",
    "privacy.completedErrors": "Concluído com {0} erro(s). O ponto de restauração nº {1} está disponível.",
    "privacy.couldNotComplete": "A alteração não pôde ser concluída. {0}",
    "privacy.revertReason": "Reverter: {0}",
    "privacy.restoreReason": "Ponto de restauração nº {0}",
    "privacy.telemetryRange": "O nível de telemetria deve ser 0–3.",
    "privacy.telemetryRestoreFail": "Não foi possível restaurar a política de telemetria. Direitos de administrador são necessários.",
    "privacy.telemetryWriteFail": "Não foi possível gravar AllowTelemetry. Direitos de administrador são necessários.",
    "privacy.serviceNotAllowed": "O serviço '{0}' não está na lista permitida.",
    "privacy.advertisingFail": "Não foi possível atualizar o ID de publicidade.",
    "privacy.activityFail": "Não foi possível atualizar a política de Histórico de atividades. Direitos de administrador são necessários.",
    "privacy.cortanaRestoreFail": "Não foi possível restaurar a política da Cortana.",
    "privacy.cortanaWriteFail": "Não foi possível gravar AllowCortana. Direitos de administrador são necessários.",
    "privacy.copilotRestoreFail": "Não foi possível restaurar a política do Copilot.",
    "privacy.copilotWriteFail": "Não foi possível gravar TurnOffWindowsCopilot. Direitos de administrador são necessários.",
    "privacy.feedbackFail": "Não foi possível atualizar as regras de feedback.",
    "privacy.tailoredFail": "Não foi possível atualizar as experiências personalizadas.",
    "privacy.notImplemented": "A configuração '{0}' não está implementada.",
    "privacy.collectingData": "Coletando dados",
    "preview.hintLead": "Apenas pré-visualização no navegador",
    "preview.hintBody": " — parece o app WinUI 3. Não controla o Windows.",
    "preview.toggleTheme": "Alternar claro / escuro",
    "preview.dialogBody": "O PrivacyGuard aplicará uma alteração reversível. Um ponto de restauração é criado automaticamente.",
    "preview.dialogMac": "Esta pré-visualização não altera o Mac. No Windows, este diálogo é obrigatório antes de qualquer gravação no registro ou em serviços.",
    "preview.sampleData": "Dados de exemplo da pré-visualização",
    "preview.edition": "Windows 11 24H2 (Professional) — exemplo",
    "preview.sampleBanner": "Dados de exemplo desta pré-visualização. No Windows, esta página mostra o histórico local real.",
    "preview.openFolder": "No Windows, isso abre %LocalAppData%\\PrivacyGuard\\logs\\.",
    "preview.appliedDemo": "Apenas pré-visualização — nenhuma configuração do Windows foi alterada.",
    "shell.elevationCancelled": "Reinício como administrador cancelado",
    "shell.elevationCancelledBody": "Você continua como usuário padrão. Reinicie como admin para alterar serviços e política da máquina.",
    "shell.elevationFailed": "Não foi possível reiniciar como administrador",
    "shell.elevationFailedBody": "O Windows não relançou o PrivacyGuard elevado. Tente de novo pela barra de título.",
    "privacy.serviceStartTypeAdmin": "Não foi possível alterar o tipo de inicialização de '{0}'. Direitos de administrador são necessários.",
    "privacy.serviceWin32": "Não foi possível alterar '{0}'. {1}",
    "privacy.serviceRefused": "O Windows recusou a alteração de '{0}'. {1}",
    "privacy.serviceUnexpected": "Erro inesperado ao alterar '{0}'.",
    "settings.openFolderError": "Não foi possível abrir a pasta de logs.",
}

def fill_from_pairs(target: dict[str, str], pairs: dict[str, str]) -> None:
    target.update(pairs)


ES: dict[str, str] = {}
fill_from_pairs(ES, {
    "common.on": "Activado", "common.off": "Desactivado", "common.apply": "Aplicar", "common.cancel": "Cancelar",
    "common.ok": "Aceptar", "common.refresh": "Actualizar", "common.required": "Obligatorio",
    "shell.standardUser": "Usuario estándar", "shell.administrator": "Administrador", "shell.restartAdmin": "Reiniciar como admin",
    "nav.overview": "Resumen", "nav.dashboard": "Panel", "nav.profiles": "Perfiles", "nav.records": "Registros",
    "nav.history": "Historial", "nav.settings": "Configuración",
    "dashboard.title": "Panel de privacidad", "dashboard.refresh": "Actualizar",
    "dashboard.restartBannerTitle": "Reinicia como administrador para aplicar cambios",
    "dashboard.restartBannerBody": "Ya puedes inspeccionarlo todo. La directiva de equipo, DiagTrack y Copilot/Cortana requieren elevación.",
    "dashboard.restartAdmin": "Reiniciar como administrador", "dashboard.adminTitle": "Administrador",
    "dashboard.privacyScore": "Puntuación de privacidad", "dashboard.outOf100": "de 100", "dashboard.whyScore": "¿Por qué esta puntuación?",
    "dashboard.telemetryTitle": "Nivel de telemetría", "dashboard.telemetrySubtitle": "Directiva AllowTelemetry (0–3)",
    "dashboard.applyTelemetry": "Aplicar nivel de telemetría",
    "dashboard.telemetryHint": "Seguridad solo se respeta en Enterprise y Education. Home y Pro lo tratan como Básico. Primero se crea un punto de restauración.",
    "dashboard.howTitle": "Cómo PrivacyGuard aplica los cambios",
    "dashboard.howBody": "Cada cambio se confirma, se escribe solo a través de PrivacyService, se guarda en SQLite y se puede revertir desde Historial. Nunca se tocan servicios críticos de Windows. Publicidad y comentarios se pueden cambiar como usuario estándar; servicios y claves de directiva necesitan administrador.",
    "dashboard.requiresAdmin": "Requiere administrador", "dashboard.loading": "Cargando estado de privacidad…",
    "dashboard.reading": "Leyendo la configuración de privacidad de Windows…",
    "dashboard.bannerElevated": "Ejecutándose como administrador. Los cambios se pueden aplicar de inmediato.",
    "dashboard.bannerLimited": "Acceso limitado: reinicia como administrador para cambiar servicios y la directiva de equipo.",
    "dashboard.refreshFailed": "No se pudo leer el estado de privacidad. Consulta los registros.",
    "dashboard.refreshFailedTitle": "Error al actualizar", "dashboard.alreadySet": "Ya establecido",
    "dashboard.alreadySetMsg": "La telemetría ya está en este nivel.", "dashboard.goodShape": "Todo en orden",
    "dashboard.goodShapeMsg": "El perfil de privacidad recomendado ya está aplicado.",
    "dashboard.setTelemetry": "Establecer telemetría en {0}", "dashboard.enable": "Activar", "dashboard.disable": "Desactivar",
    "dashboard.confirmBody": "PrivacyGuard aplicará los siguientes cambios reversibles:\n\n{0}\n\nSe crea un punto de restauración automáticamente.",
    "dashboard.changeIncomplete": "Cambio no aplicado por completo", "dashboard.privacyUpdated": "Privacidad actualizada",
    "dashboard.finishedErrors": "Finalizado con errores", "dashboard.changeFailed": "Error al cambiar",
    "dashboard.denied": "Windows denegó el cambio. Reinicia PrivacyGuard como administrador e inténtalo de nuevo.",
    "dashboard.noLocalChanges": "Aún no hay cambios locales", "dashboard.lastChanged": "Último cambio {0}",
    "dashboard.updated": "Actualizado {0}", "dashboard.improve": "Aplicar perfil recomendado",
    "dashboard.improveDone": "Perfil recomendado aplicado",
    "dashboard.scoreLoading": "Leyendo la configuración de privacidad de Windows…",
    "dashboard.scoreProtected": "La mayor parte de la recopilación opcional está limitada. Aún puedes reforzar algunos servicios.",
    "dashboard.scorePartial": "Algunas opciones de publicidad y diagnóstico siguen activas. El perfil recomendado cierra las brechas.",
    "dashboard.scoreCollecting": "Windows usa la recopilación predeterminada. Aplica el perfil recomendado para una base más segura.",
    "health.protected": "Protegido", "health.needsAttention": "Requiere atención", "health.collecting": "Recopilando datos",
    "health.unknown": "Desconocido", "health.partial": "Parcial", "health.limited": "Limitado", "health.mixed": "Mixto",
    "dashboard.section.core": "Telemetría principal",
    "dashboard.section.coreSub": "Datos de diagnóstico que Windows puede enviar y los servicios que los transportan.",
    "dashboard.section.ads": "Publicidad y personalización",
    "dashboard.section.adsSub": "Identificadores e historial usados para anuncios, sugerencias y Timeline.",
    "dashboard.section.ai": "IA y asistentes", "dashboard.section.aiSub": "Directiva de Cortana y visibilidad de Copilot en este dispositivo.",
    "dashboard.section.other": "Otros", "dashboard.section.otherSub": "Solicitudes de comentarios y otras opciones de privacidad.",
    "telemetry.security": "Seguridad — solo Enterprise", "telemetry.basic": "Básico — recomendado",
    "telemetry.enhanced": "Mejorado", "telemetry.full": "Completo — valor predeterminado de Windows",
    "telemetry.value.security": "Seguridad", "telemetry.value.basic": "Básico", "telemetry.value.enhanced": "Mejorado",
    "telemetry.value.full": "Completo", "common.windowsDefault": "Valor predeterminado de Windows",
    "service.running": "En ejecución", "service.stopped": "Detenido", "service.automatic": "Automático",
    "service.manual": "Manual", "service.disabled": "Deshabilitado", "service.missing": "No instalado",
    "setting.telemetry": "Telemetría de Windows", "setting.diagTrack": "Experiencias de usuario conectadas (DiagTrack)",
    "setting.dmw": "Enrutamiento de mensajes WAP Push (dmwappushservice)", "setting.advertising": "Id. de publicidad",
    "setting.activity": "Historial de actividad / Timeline", "setting.cortana": "Cortana", "setting.copilot": "Windows Copilot",
    "setting.feedback": "Solicitudes de comentarios y diagnóstico", "setting.tailored": "Experiencias personalizadas",
    "setting.telemetry.desc": "Cuántos datos de diagnóstico puede enviar Windows a Microsoft (AllowTelemetry).",
    "setting.diagTrack.desc": "Implementa Experiencias de usuario conectadas y Telemetría. Detenerlo reduce la telemetría, pero puede afectar algunos diagnósticos.",
    "setting.dmw.desc": "Enrutamiento WAP Push usado en algunos escenarios de telemetría y MDM. Es seguro desactivarlo para la mayoría de usuarios domésticos.",
    "setting.advertising.desc": "Identificador que las aplicaciones pueden usar para mostrar anuncios más relevantes.",
    "setting.activity.desc": "Recopila actividad de aplicaciones y navegación para Timeline y reanudación entre dispositivos.",
    "setting.cortana.desc": "Directiva AllowCortana. En Windows 11 afecta principalmente a componentes restantes de Cortana.",
    "setting.copilot.desc": "Directiva TurnOffWindowsCopilot. La eficacia depende de la compilación y de cómo esté instalado Copilot.",
    "setting.feedback.desc": "Frecuencia del Centro de opiniones y de las encuestas de satisfacción.",
    "setting.tailored.desc": "Usa datos de diagnóstico para personalizar sugerencias, anuncios y recomendaciones.",
    "setting.telemetry.side": "El nivel Seguridad solo de Enterprise se ignora en Home/Pro (Windows lo sube a Básico).",
    "setting.diagTrack.side": "Las experiencias de diagnóstico opcionales y algunas funciones de comentarios/telemetría pueden detenerse. Windows Update sigue funcionando.",
    "setting.dmw.side": "Pueden verse afectados escenarios poco frecuentes de WAP Push / entrega MDM.",
    "setting.cortana.side": "Cortana (si está presente) se deshabilitará por directiva. La Búsqueda de Windows sigue disponible.",
    "setting.copilot.side": "La interfaz de Copilot puede ocultarse o ignorarse según la compilación. Puede ser necesario cerrar sesión.",
    "setting.activity.side": "Timeline y la reanudación de actividad entre dispositivos se detendrán.",
    "factor.telemetry": "Nivel de telemetría", "factor.diagTrack": "DiagTrack", "factor.dmw": "Servicio WAP Push",
    "factor.advertising": "Id. de publicidad", "factor.activity": "Historial de actividad", "factor.cortana": "Cortana",
    "factor.copilot": "Copilot", "factor.feedback": "Solicitudes de comentarios", "factor.tailored": "Experiencias personalizadas",
    "profile.recommended.title": "Privacidad recomendada",
    "profile.recommended.summary": "Reduce la publicidad y los diagnósticos opcionales, manteniendo Windows Update y la seguridad en buen estado.",
    "profile.recommended.details": "Telemetría: Básica. Id. de publicidad desactivada. Carga de actividad desactivada. Comentarios desactivados. DiagTrack sigue en ejecución para diagnósticos de Update.",
    "profile.recommended.warning": "Algunas sugerencias personalizadas, anuncios y la sincronización de Timeline se detendrán. No afecta a Windows Security ni a Update.",
    "profile.recommended.h1": "Telemetría: Básica", "profile.recommended.h2": "Id. de publicidad desactivada",
    "profile.recommended.h3": "Historial de actividad desactivado", "profile.recommended.h4": "Comentarios desactivados",
    "profile.recommended.h5": "DiagTrack sigue en ejecución",
    "profile.maximum.title": "Privacidad máxima",
    "profile.maximum.summary": "Configuración más restrictiva admitida. Algunas experiencias opcionales de Windows pueden dejar de funcionar.",
    "profile.maximum.details": "Telemetría: Seguridad (o Básica en Home/Pro). DiagTrack y dmwappushservice detenidos. Publicidad, historial, directiva Cortana/Copilot y comentarios desactivados.",
    "profile.maximum.warning": "Los destacados de búsqueda, Timeline, diagnósticos opcionales y cierta personalización de Store pueden dejar de funcionar. Reversible desde Historial o Restaurar valores. En Home/Pro, Windows no respeta la telemetría Seguridad (0).",
    "profile.maximum.h1": "Telemetría: Seguridad o Básica", "profile.maximum.h2": "DiagTrack detenido",
    "profile.maximum.h3": "WAP Push deshabilitado", "profile.maximum.h4": "Anuncios, Timeline y Copilot desactivados",
    "profile.maximum.h5": "Comentarios y experiencias desactivados",
    "profile.balanced.title": "Equilibrado",
    "profile.balanced.summary": "Mantiene los servicios de diagnóstico en ejecución y desactiva el id. de publicidad y la carga de actividad.",
    "profile.balanced.details": "Telemetría: Completa. DiagTrack en ejecución. Id. de publicidad desactivada. Actividad local permitida, carga a la nube desactivada. Copilot sin cambios.",
    "profile.balanced.warning": "Windows seguirá enviando datos de diagnóstico opcionales. Solo se reducen la publicidad y la carga de actividad.",
    "profile.balanced.h1": "Telemetría: Completa", "profile.balanced.h2": "DiagTrack en ejecución",
    "profile.balanced.h3": "Id. de publicidad desactivada", "profile.balanced.h4": "Carga de actividad desactivada",
    "profile.balanced.h5": "Copilot sin cambios",
    "profile.restore.title": "Restaurar valores",
    "profile.restore.summary": "Quita los valores de directiva de PrivacyGuard y devuelve los servicios a los valores típicos de Windows.",
    "profile.restore.details": "Elimina la directiva AllowTelemetry, rehabilita DiagTrack (Automático + En ejecución) y restaura publicidad, historial, Cortana/Copilot y comentarios.",
    "profile.restore.warning": "Esto restaura los valores predeterminados de recopilación. No deshace ajustes de terceros no relacionados.",
    "profile.restore.h1": "Telemetría: valor predeterminado de Windows", "profile.restore.h2": "DiagTrack automático",
    "profile.restore.h3": "Id. de publicidad activada", "profile.restore.h4": "Historial de actividad activado",
    "profile.restore.h5": "Cortana y Copilot restaurados",
    "profiles.title": "Perfiles de privacidad",
    "profiles.subtitle": "Configuraciones con un clic. Cada aplicación pide confirmación, crea un punto de restauración y es totalmente reversible.",
    "profiles.safety": "Seguridad", "profiles.recommendedBadge": "Recomendado", "profiles.active": "Activo",
    "profiles.beforeContinue": "Antes de continuar", "profiles.scoreNone": "Impacto en la puntuación: sin cambios",
    "profiles.scoreUp": "Impacto en la puntuación: +{0}", "profiles.scoreDown": "Impacto en la puntuación: {0}",
    "profiles.scoreUnknown": "Impacto en la puntuación: —", "profiles.lastApplied": "Última aplicación: {0} a las {1}",
    "profiles.today": "Hoy", "profiles.yesterday": "Ayer", "profiles.review": "Revisar y aplicar",
    "profiles.currentlyApplied": "Aplicado actualmente", "profiles.alreadyTitle": "Ya aplicado",
    "profiles.alreadyMsg": "{0} ya está aplicado.", "profiles.adminTitle": "Se requiere administrador",
    "profiles.adminBody": "Este perfil cambia directivas o servicios de todo el equipo. Reinicia PrivacyGuard como administrador y aplícalo de nuevo.",
    "profiles.applyTitle": "¿Aplicar {0}?", "profiles.confirmBody": "Se aplicarán los siguientes cambios reversibles:\n\n{0}",
    "profiles.appliedTitle": "Perfil aplicado", "profiles.partialTitle": "Perfil aplicado parcialmente",
    "profiles.failedTitle": "Error del perfil", "profiles.choose": "Elige un perfil. Cada aplicación crea primero un punto de restauración.",
    "history.title": "Historial de cambios",
    "history.subtitle": "Cada mutación se registra localmente. Revierte un ajuste o restaura un punto de copia de seguridad completo.",
    "history.audit": "Registro de auditoría local", "history.changes": "Cambios", "history.filterAll": "Todos",
    "history.filterActive": "Activos", "history.filterReverted": "Revertidos", "history.revertSelected": "Revertir selección",
    "history.revertN": "Revertir {0} cambios", "history.noneSelected": "Ninguno seleccionado",
    "history.changeSelectedOne": "1 cambio seleccionado", "history.changeSelectedMany": "{0} cambios seleccionados",
    "history.restoreSelectedOne": "1 punto de restauración seleccionado",
    "history.restoreSelectedMany": "{0} puntos de restauración seleccionados",
    "history.emptyTitle": "Aún no hay historial", "history.emptyFilterTitle": "No hay cambios coincidentes",
    "history.emptyMsg": "Aún no hay cambios. Aplica un perfil o cambia un ajuste para que aparezca aquí.",
    "history.emptyFilterMsg": "Ningún cambio coincide con este filtro.",
    "history.statusEmpty": "Aún no hay cambios. Los ajustes aplicados aparecerán aquí.",
    "history.statusCounts": "{0} cambio(s) registrado(s), {1} punto(s) de restauración.",
    "history.unavailable": "Historial no disponible", "history.alreadyRevertedTitle": "Ya revertido",
    "history.alreadyRevertedBody": "Los elementos de historial seleccionados ya estaban marcados como revertidos.",
    "history.revertOne": "¿Revertir este cambio?", "history.revertMany": "¿Revertir {0} cambios?",
    "history.revertBody": "Se restaurarán los siguientes cambios reversibles:\n\n{0}",
    "history.revertWarning": "Se creará un nuevo punto de restauración antes de cada reversión.",
    "history.revertFailed": "Error al revertir", "history.restoreTitle": "¿Restaurar esta copia?",
    "history.restoreBody": "Se volverá a aplicar el punto de restauración n.º {0} de {1} ({2} ajuste(s)).",
    "history.restoreWarning": "Los valores actuales se copian primero, así que esta restauración también es reversible.",
    "history.restoreFailed": "Error al restaurar", "history.restored": "Restaurado",
    "history.restorePoints": "Puntos de restauración", "history.restorePointsSub": "Instantáneas tomadas antes de cada mutación.",
    "history.noRestoreTitle": "Aún no hay puntos de restauración",
    "history.noRestoreBody": "Aquí aparecerá una instantánea la primera vez que se cambie un ajuste.",
    "history.restoreButton": "Restaurar copia seleccionada", "history.reverted": "Revertido",
    "history.manualChange": "Cambio manual", "history.restorePointN": "Punto de restauración n.º {0}",
    "history.settingKey": "Clave del ajuste: ", "history.source": "Origen: ", "history.today": "Hoy",
    "history.yesterday": "Ayer", "history.earlier": "Anterior", "history.settingCapturedOne": "1 ajuste capturado",
    "history.settingCapturedMany": "{0} ajustes capturados",
    "history.storedLocally": "El historial de cambios se almacena localmente en SQLite.",
    "settings.title": "Configuración",
    "settings.subtitle": "Solo preferencias de la aplicación. La privacidad de Windows está en el Panel y en Perfiles.",
    "settings.appearance": "Apariencia", "settings.theme": "Tema",
    "settings.themeDesc": "Sigue a Windows o fuerza un tema claro u oscuro.",
    "settings.themeDefault": "Valor predeterminado de Windows", "settings.themeDefaultSub": "Coincidir con el tema del sistema",
    "settings.themeLight": "Claro", "settings.themeLightSub": "Usar siempre el tema claro",
    "settings.themeDark": "Oscuro", "settings.themeDarkSub": "Usar siempre el tema oscuro",
    "settings.language": "Idioma",
    "settings.languageDesc": "Cambia toda la interfaz de PrivacyGuard. Las fechas y los números también siguen este idioma.",
    "settings.languagePlaceholder": "Buscar idiomas", "settings.startup": "Inicio y seguridad",
    "settings.startWindows": "Iniciar con Windows",
    "settings.startWindowsDesc": "Agrega o quita una clave Run del usuario actual. No requiere derechos de administrador.",
    "settings.confirm": "Confirmar antes de aplicar cambios",
    "settings.confirmDesc": "Los diálogos de confirmación siempre se muestran antes de que PrivacyGuard cambie Windows. Este interruptor está bloqueado por seguridad.",
    "settings.confirmLock": "Siempre obligatorio por seguridad", "settings.record": "Registrar historial de cambios",
    "settings.recordDesc": "Escribe cada mutación de ajuste en la base de datos SQLite local.",
    "settings.data": "Datos", "settings.logs": "Archivos de registro", "settings.openFolder": "Abrir carpeta",
    "settings.database": "Base de datos del historial", "settings.about": "Acerca de",
    "settings.aboutBody": "Panel unificado de privacidad y telemetría para Windows 10/11. Los cambios son reversibles y nunca afectan a servicios críticos del sistema.",
    "settings.checkUpdates": "Buscar actualizaciones", "settings.upToDate": "Estás al día",
    "settings.upToDateBody": "PrivacyGuard 0.1.0 es la compilación actual. La comprobación automática de actualizaciones se añadirá en una versión posterior.",
    "settings.autoStart": "Inicio automático", "settings.autoStartError": "No se pudo actualizar la clave Run del usuario actual.",
    "dialog.beforeContinue": "Antes de continuar",
    "privacy.nothingToChange": "Nada que cambiar: el sistema ya coincide con el estado solicitado.",
    "privacy.refusedUnknown": "Se rechazó el ajuste desconocido '{0}'.",
    "privacy.needsAdmin": "Este cambio requiere derechos de administrador. Usa Reiniciar como administrador e inténtalo de nuevo.",
    "privacy.applied": "Se aplicaron {0} cambio(s). Se guardó el punto de restauración n.º {1}.",
    "privacy.completedErrors": "Completado con {0} error(es). El punto de restauración n.º {1} está disponible.",
    "privacy.couldNotComplete": "No se pudo completar el cambio. {0}",
    "privacy.revertReason": "Revertir: {0}", "privacy.restoreReason": "Punto de restauración n.º {0}",
    "privacy.telemetryRange": "El nivel de telemetría debe ser 0–3.",
    "privacy.telemetryRestoreFail": "No se pudo restaurar la directiva de telemetría. Se requieren derechos de administrador.",
    "privacy.telemetryWriteFail": "No se pudo escribir AllowTelemetry. Se requieren derechos de administrador.",
    "privacy.serviceNotAllowed": "El servicio '{0}' no está en la lista permitida.",
    "privacy.advertisingFail": "No se pudo actualizar el Id. de publicidad.",
    "privacy.activityFail": "No se pudo actualizar la directiva de Historial de actividad. Se requieren derechos de administrador.",
    "privacy.cortanaRestoreFail": "No se pudo restaurar la directiva de Cortana.",
    "privacy.cortanaWriteFail": "No se pudo escribir AllowCortana. Se requieren derechos de administrador.",
    "privacy.copilotRestoreFail": "No se pudo restaurar la directiva de Copilot.",
    "privacy.copilotWriteFail": "No se pudo escribir TurnOffWindowsCopilot. Se requieren derechos de administrador.",
    "privacy.feedbackFail": "No se pudieron actualizar las reglas de comentarios.",
    "privacy.tailoredFail": "No se pudieron actualizar las experiencias personalizadas.",
    "privacy.notImplemented": "El ajuste '{0}' no está implementado.", "privacy.collectingData": "Recopilando datos",
})

import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_localization_east import AR, JA, RU
from generate_localization_more import IT, ZH
from generate_localization_rest import DE, FR


def csharp_escape(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace("\"", "\\\"")
        .replace("\r\n", "\\n")
        .replace("\n", "\\n")
    )


def emit_table(name: str, table: dict[str, str]) -> str:
    merged = {**EN, **table}
    lines = [f"    private static readonly Dictionary<string, string> {name} = new(StringComparer.Ordinal)"]
    lines.append("    {")
    for key in EN:
        lines.append(f"        [\"{key}\"] = \"{csharp_escape(merged[key])}\",")
    lines.append("    };")
    return "\n".join(lines)


def main() -> None:
    languages = [
        ("en-US", "English", "English", "En", EN),
        ("pt-BR", "Português", "Portuguese", "PtBr", PT),
        ("es-ES", "Español", "Spanish", "EsEs", ES),
        ("fr-FR", "Français", "French", "FrFr", FR),
        ("de-DE", "Deutsch", "German", "DeDe", DE),
        ("it-IT", "Italiano", "Italian", "ItIt", IT),
        ("zh-CN", "中文", "Chinese (Simplified)", "ZhCn", ZH),
        ("ja-JP", "日本語", "Japanese", "JaJp", JA),
        ("ru-RU", "Русский", "Russian", "RuRu", RU),
        ("ar", "العربية", "Arabic", "Ar", AR),
    ]

    missing = []
    for code, native, english, field, table in languages:
        for key in EN:
            if key not in table and field != "En":
                missing.append(f"{code}:{key}")

    option_lines = []
    for code, native, english, field, table in languages:
        option_lines.append(
            "        new()\n"
            "        {\n"
            f"            Code = \"{code}\",\n"
            f"            NativeName = \"{native}\",\n"
            f"            EnglishName = \"{english}\"\n"
            "        },"
        )

    switch_lines = []
    for code, native, english, field, table in languages:
        switch_lines.append(f"            \"{code}\" => {field},")

    tables = "\n\n".join(emit_table(field, table) for code, native, english, field, table in languages)

    source = f"""using System.Globalization;
using PrivacyGuard.Models;

namespace PrivacyGuard.Helpers;

/// <summary>
/// In-memory UI string catalog. Missing keys fall back to English.
/// </summary>
internal static class LocalizationCatalog
{{
    public static readonly LanguageOption[] Languages =
    [
{chr(10).join(option_lines)}
    ];

    public static string Get(string languageCode, string key)
    {{
        var table = TableFor(Normalize(languageCode));
        if (table.TryGetValue(key, out var value) && !string.IsNullOrEmpty(value))
        {{
            return value;
        }}

        return En.GetValueOrDefault(key, key);
    }}

    public static string Normalize(string? languageCode)
    {{
        if (string.IsNullOrWhiteSpace(languageCode))
        {{
            return AppPreferences.DefaultLanguage;
        }}

        if (languageCode.Equals("ar", StringComparison.OrdinalIgnoreCase)
            || languageCode.StartsWith("ar-", StringComparison.OrdinalIgnoreCase))
        {{
            return "ar";
        }}

        foreach (var option in Languages)
        {{
            if (option.Code.Equals(languageCode, StringComparison.OrdinalIgnoreCase))
            {{
                return option.Code;
            }}
        }}

        var prefix = languageCode.Split('-')[0];
        var family = Languages.FirstOrDefault(option =>
            option.Code.StartsWith(prefix + "-", StringComparison.OrdinalIgnoreCase));
        return family?.Code ?? AppPreferences.DefaultLanguage;
    }}

    private static IReadOnlyDictionary<string, string> TableFor(string languageCode) => languageCode switch
    {{
{chr(10).join(switch_lines)}
            _ => En
    }};

{tables}
}}
"""

    root = Path(__file__).resolve().parents[1]
    out = root / "src" / "PrivacyGuard" / "Helpers" / "LocalizationCatalog.cs"
    out.write_text(source.replace("\r\n", "\n"), encoding="utf-8")
    print(f"Wrote {out} ({out.stat().st_size} bytes, {len(EN)} keys, {len(missing)} fallbacks)")

    js_tables = {code: {**EN, **table} for code, native, english, field, table in languages}
    js_langs = [{"code": code, "native": native} for code, native, english, field, table in languages]
    js_path = root / "preview" / "i18n.js"
    js_path.write_text(
        "window.PRIVACYGUARD_LANGS = "
        + json.dumps(js_langs, ensure_ascii=False)
        + ";\nwindow.PRIVACYGUARD_I18N = "
        + json.dumps(js_tables, ensure_ascii=False)
        + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {js_path} ({js_path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()

