"""Japanese, Russian, and Arabic maps."""

JA = {
    "common.on": "オン", "common.off": "オフ", "common.apply": "適用", "common.cancel": "キャンセル",
    "common.ok": "OK", "common.refresh": "更新", "common.required": "必須",
    "shell.standardUser": "標準ユーザー", "shell.administrator": "管理者", "shell.restartAdmin": "管理者として再起動",
    "nav.overview": "概要", "nav.dashboard": "ダッシュボード", "nav.profiles": "プロファイル",
    "nav.records": "記録", "nav.history": "履歴", "nav.settings": "設定",
    "dashboard.title": "プライバシー ダッシュボード", "dashboard.refresh": "更新",
    "dashboard.restartBannerTitle": "変更を適用するには管理者として再起動してください",
    "dashboard.restartBannerBody": "内容の確認は今すぐできます。コンピューター ポリシー、DiagTrack、Copilot/Cortana には昇格が必要です。",
    "dashboard.restartAdmin": "管理者として再起動", "dashboard.adminTitle": "管理者",
    "dashboard.privacyScore": "プライバシー スコア", "dashboard.outOf100": "/ 100",
    "dashboard.whyScore": "このスコアの理由", "dashboard.telemetryTitle": "テレメトリ レベル",
    "dashboard.telemetrySubtitle": "AllowTelemetry ポリシー (0–3)",
    "dashboard.applyTelemetry": "テレメトリ レベルを適用",
    "dashboard.telemetryHint": "セキュリティは Enterprise と Education でのみ有効です。Home と Pro では基本として扱われます。先に復元ポイントが作成されます。",
    "dashboard.howTitle": "PrivacyGuard が変更を適用する方法",
    "dashboard.howBody": "すべての変更は確認され、PrivacyService 経由でのみ書き込まれ、SQLite にバックアップされ、履歴から元に戻せます。重要な Windows サービスには一切触れません。広告とフィードバックは標準ユーザーで切り替え可能です。サービスとポリシー キーには管理者権限が必要です。",
    "dashboard.requiresAdmin": "管理者権限が必要", "dashboard.loading": "プライバシー状態を読み込み中…",
    "dashboard.reading": "Windows のプライバシー設定を読み取り中…",
    "dashboard.bannerElevated": "管理者として実行中です。変更はすぐに適用できます。",
    "dashboard.bannerLimited": "アクセスが制限されています。サービスとコンピューター ポリシーを変更するには管理者として再起動してください。",
    "dashboard.refreshFailed": "プライバシー状態を読み取れませんでした。ログを確認してください。",
    "dashboard.refreshFailedTitle": "更新に失敗しました", "dashboard.alreadySet": "既に設定済み",
    "dashboard.alreadySetMsg": "テレメトリは既にこのレベルです。", "dashboard.goodShape": "良好な状態です",
    "dashboard.goodShapeMsg": "推奨プライバシー プロファイルは既に適用されています。",
    "dashboard.setTelemetry": "テレメトリを {0} に設定", "dashboard.enable": "有効にする", "dashboard.disable": "無効にする",
    "dashboard.confirmBody": "PrivacyGuard は次の取り消し可能な変更を適用します:\n\n{0}\n\n復元ポイントは自動的に作成されます。",
    "dashboard.changeIncomplete": "変更が完全には適用されませんでした", "dashboard.privacyUpdated": "プライバシーを更新しました",
    "dashboard.finishedErrors": "エラー付きで完了", "dashboard.changeFailed": "変更に失敗しました",
    "dashboard.denied": "Windows が変更を拒否しました。PrivacyGuard を管理者として再起動して再試行してください。",
    "dashboard.noLocalChanges": "まだローカルの変更はありません", "dashboard.lastChanged": "最終変更 {0}",
    "dashboard.updated": "更新済み {0}", "dashboard.improve": "推奨プロファイルを適用",
    "dashboard.improveDone": "推奨プロファイル適用済み",
    "dashboard.scoreLoading": "Windows のプライバシー設定を読み取り中…",
    "dashboard.scoreProtected": "任意の収集のほとんどは制限されています。一部のサービスはさらに締められます。",
    "dashboard.scorePartial": "広告や診断のオプションがまだオンです。推奨プロファイルで隙間を埋められます。",
    "dashboard.scoreCollecting": "Windows は既定の収集を使用しています。より安全な基準にするには推奨プロファイルを適用してください。",
    "health.protected": "保護済み", "health.needsAttention": "要確認", "health.collecting": "データを収集中",
    "health.unknown": "不明", "health.partial": "一部", "health.limited": "制限済み", "health.mixed": "混在",
    "dashboard.section.core": "コア テレメトリ",
    "dashboard.section.coreSub": "Windows が送信する可能性のある診断データと、それを運ぶサービス。",
    "dashboard.section.ads": "広告とパーソナライズ",
    "dashboard.section.adsSub": "広告、ヒント、タイムラインに使われる識別子と履歴。",
    "dashboard.section.ai": "AI とアシスタント機能", "dashboard.section.aiSub": "このデバイスの Cortana ポリシーと Copilot の表示。",
    "dashboard.section.other": "その他", "dashboard.section.otherSub": "フィードバックの案内とその他のプライバシー関連オプション。",
    "telemetry.security": "セキュリティ — Enterprise のみ", "telemetry.basic": "基本 — 推奨",
    "telemetry.enhanced": "拡張", "telemetry.full": "完全 — Windows の既定",
    "telemetry.value.security": "セキュリティ", "telemetry.value.basic": "基本", "telemetry.value.enhanced": "拡張",
    "telemetry.value.full": "完全", "common.windowsDefault": "Windows の既定",
    "service.running": "実行中", "service.stopped": "停止", "service.automatic": "自動",
    "service.manual": "手動", "service.disabled": "無効", "service.missing": "未インストール",
    "setting.telemetry": "Windows テレメトリ", "setting.diagTrack": "接続ユーザー エクスペリエンス (DiagTrack)",
    "setting.dmw": "WAP プッシュ メッセージ ルーティング (dmwappushservice)", "setting.advertising": "広告 ID",
    "setting.activity": "アクティビティ履歴 / タイムライン", "setting.cortana": "Cortana", "setting.copilot": "Windows Copilot",
    "setting.feedback": "フィードバックと診断の案内", "setting.tailored": "調整されたエクスペリエンス",
    "setting.telemetry.desc": "Windows が Microsoft に送信できる診断データの量 (AllowTelemetry)。",
    "setting.diagTrack.desc": "接続ユーザー エクスペリエンスとテレメトリを実装します。停止するとテレメトリは減りますが、一部の診断に影響する場合があります。",
    "setting.dmw.desc": "一部のテレメトリと MDM シナリオで使われる WAP プッシュ ルーティング。ほとんどのホーム ユーザーは無効にして問題ありません。",
    "setting.advertising.desc": "アプリがより関連性の高い広告を表示するために使う識別子。",
    "setting.activity.desc": "タイムラインとデバイス間の再開のためにアプリと閲覧のアクティビティを収集します。",
    "setting.cortana.desc": "AllowCortana ポリシー。Windows 11 では主に残っている Cortana コンポーネントに影響します。",
    "setting.copilot.desc": "TurnOffWindowsCopilot ポリシー。効果は Windows のビルドと Copilot の導入方法に依存します。",
    "setting.feedback.desc": "フィードバック Hub と満足度アンケートの頻度。",
    "setting.tailored.desc": "診断データを使ってヒント、広告、おすすめをパーソナライズします。",
    "setting.telemetry.side": "Enterprise 専用のセキュリティ レベルは Home/Pro では無視されます (Windows が基本に引き上げます)。",
    "setting.diagTrack.side": "任意の診断エクスペリエンスと一部のフィードバック/テレメトリ機能が停止する場合があります。Windows Update は動作し続けます。",
    "setting.dmw.side": "まれな WAP プッシュ / 一部の MDM 配信シナリオが影響を受ける場合があります。",
    "setting.cortana.side": "Cortana (存在する場合) はポリシーで無効になります。Windows 検索自体は利用できます。",
    "setting.copilot.side": "Windows のビルドによっては Copilot UI が非表示または無視されることがあります。サインアウトが必要な場合があります。",
    "setting.activity.side": "タイムラインとデバイス間のアクティビティ再開は停止します。",
    "factor.telemetry": "テレメトリ レベル", "factor.diagTrack": "DiagTrack", "factor.dmw": "WAP プッシュ サービス",
    "factor.advertising": "広告 ID", "factor.activity": "アクティビティ履歴", "factor.cortana": "Cortana",
    "factor.copilot": "Copilot", "factor.feedback": "フィードバックの案内", "factor.tailored": "調整されたエクスペリエンス",
    "profile.recommended.title": "推奨プライバシー",
    "profile.recommended.summary": "広告と任意の診断を減らしつつ、Windows Update とセキュリティは健全に保ちます。",
    "profile.recommended.details": "テレメトリ: 基本。広告 ID オフ。アクティビティのアップロード オフ。フィードバック オフ。Update 診断のため DiagTrack は実行したまま。",
    "profile.recommended.warning": "一部のパーソナライズされたヒント、広告、タイムライン同期は停止します。Windows セキュリティと Update には影響しません。",
    "profile.recommended.h1": "テレメトリ: 基本", "profile.recommended.h2": "広告 ID オフ",
    "profile.recommended.h3": "アクティビティ履歴オフ", "profile.recommended.h4": "フィードバック オフ",
    "profile.recommended.h5": "DiagTrack は実行継続",
    "profile.maximum.title": "最大限のプライバシー",
    "profile.maximum.summary": "サポートされる最も制限の強い構成です。一部の任意の Windows 機能が動かなくなる場合があります。",
    "profile.maximum.details": "テレメトリ: セキュリティ (Home/Pro では基本)。DiagTrack と dmwappushservice を停止。広告、履歴、Cortana/Copilot ポリシー、フィードバックをオフ。",
    "profile.maximum.warning": "検索のハイライト、タイムライン、任意の診断、一部の Store のパーソナライズが停止する場合があります。履歴または既定に戻すから取り消し可能です。Home/Pro ではセキュリティ (0) テレメトリは尊重されません。",
    "profile.maximum.h1": "テレメトリ: セキュリティまたは基本", "profile.maximum.h2": "DiagTrack 停止",
    "profile.maximum.h3": "WAP プッシュ無効", "profile.maximum.h4": "広告、タイムライン、Copilot オフ",
    "profile.maximum.h5": "フィードバックと調整オフ",
    "profile.balanced.title": "バランス",
    "profile.balanced.summary": "診断サービスは実行したまま、広告 ID とアクティビティのアップロードをオフにします。",
    "profile.balanced.details": "テレメトリ: 完全。DiagTrack 実行中。広告 ID オフ。ローカル アクティビティは許可、クラウド送信はオフ。Copilot は変更なし。",
    "profile.balanced.warning": "Windows は任意の診断データを引き続き送信します。削減されるのは広告とアクティビティのアップロードだけです。",
    "profile.balanced.h1": "テレメトリ: 完全", "profile.balanced.h2": "DiagTrack 実行中",
    "profile.balanced.h3": "広告 ID オフ", "profile.balanced.h4": "アクティビティ送信オフ",
    "profile.balanced.h5": "Copilot は変更なし",
    "profile.restore.title": "既定に戻す",
    "profile.restore.summary": "PrivacyGuard のポリシー値を削除し、サービスを一般的な Windows の既定に戻します。",
    "profile.restore.details": "AllowTelemetry ポリシーを削除し、DiagTrack を再有効化 (自動 + 実行中) し、広告 ID、履歴、Cortana/Copilot、フィードバックを既定に戻します。",
    "profile.restore.warning": "データ収集の既定値を復元します。無関係なサードパーティの調整はロールバックしません。",
    "profile.restore.h1": "テレメトリ: Windows の既定", "profile.restore.h2": "DiagTrack 自動",
    "profile.restore.h3": "広告 ID オン", "profile.restore.h4": "アクティビティ履歴オン",
    "profile.restore.h5": "Cortana と Copilot を復元",
    "profiles.title": "プライバシー プロファイル",
    "profiles.subtitle": "ワンクリック構成。適用のたびに確認を表示し、復元ポイントを作成し、完全に元に戻せます。",
    "profiles.safety": "安全", "profiles.recommendedBadge": "推奨", "profiles.active": "適用中",
    "profiles.beforeContinue": "続行する前に", "profiles.scoreNone": "スコアへの影響: 変化なし",
    "profiles.scoreUp": "スコアへの影響: +{0}", "profiles.scoreDown": "スコアへの影響: {0}",
    "profiles.scoreUnknown": "スコアへの影響: —", "profiles.lastApplied": "最終適用: {0} {1}",
    "profiles.today": "今日", "profiles.yesterday": "昨日", "profiles.review": "確認して適用",
    "profiles.currentlyApplied": "現在適用中", "profiles.alreadyTitle": "既に適用済み",
    "profiles.alreadyMsg": "{0} は既に適用されています。", "profiles.adminTitle": "管理者が必要です",
    "profiles.adminBody": "このプロファイルはコンピューター全体のポリシーまたはサービスを変更します。PrivacyGuard を管理者として再起動してから再適用してください。",
    "profiles.applyTitle": "{0} を適用しますか?", "profiles.confirmBody": "次の取り消し可能な変更が適用されます:\n\n{0}",
    "profiles.appliedTitle": "プロファイルを適用しました", "profiles.partialTitle": "プロファイルは一部のみ適用",
    "profiles.failedTitle": "プロファイルに失敗", "profiles.choose": "プロファイルを選択してください。適用のたびに先に復元ポイントが作成されます。",
    "history.title": "変更履歴",
    "history.subtitle": "すべての変更はローカルに記録されます。単一の設定を戻すか、完全なバックアップ ポイントを復元できます。",
    "history.audit": "ローカル監査ログ", "history.changes": "変更", "history.filterAll": "すべて",
    "history.filterActive": "有効", "history.filterReverted": "取り消し済み", "history.revertSelected": "選択を取り消し",
    "history.revertN": "{0} 件の変更を取り消し", "history.noneSelected": "未選択",
    "history.changeSelectedOne": "1 件の変更を選択", "history.changeSelectedMany": "{0} 件の変更を選択",
    "history.restoreSelectedOne": "復元ポイントを 1 件選択",
    "history.restoreSelectedMany": "復元ポイントを {0} 件選択",
    "history.emptyTitle": "まだ履歴がありません", "history.emptyFilterTitle": "一致する変更がありません",
    "history.emptyMsg": "まだ変更はありません。プロファイルを適用するか設定を切り替えるとここに表示されます。",
    "history.emptyFilterMsg": "このフィルターに一致する変更はありません。",
    "history.statusEmpty": "まだ変更はありません。適用した設定がここに表示されます。",
    "history.statusCounts": "記録された変更 {0} 件、復元ポイント {1} 件。",
    "history.unavailable": "履歴を利用できません", "history.alreadyRevertedTitle": "既に取り消し済み",
    "history.alreadyRevertedBody": "選択した履歴項目は既に取り消し済みとマークされています。",
    "history.revertOne": "この変更を取り消しますか?", "history.revertMany": "{0} 件の変更を取り消しますか?",
    "history.revertBody": "次の取り消し可能な変更が復元されます:\n\n{0}",
    "history.revertWarning": "取り消しの前に新しい復元ポイントが作成されます。",
    "history.revertFailed": "取り消しに失敗しました", "history.restoreTitle": "このバックアップを復元しますか?",
    "history.restoreBody": "{1} の復元ポイント #{0} を再適用します ({2} 件の設定)。",
    "history.restoreWarning": "現在の値は先にバックアップされるため、この復元自体も取り消し可能です。",
    "history.restoreFailed": "復元に失敗しました", "history.restored": "復元しました",
    "history.restorePoints": "復元ポイント", "history.restorePointsSub": "各変更の前に取得したスナップショット。",
    "history.noRestoreTitle": "まだ復元ポイントがありません",
    "history.noRestoreBody": "設定が初めて変更されると、スナップショットがここに表示されます。",
    "history.restoreButton": "選択したバックアップを復元", "history.reverted": "取り消し済み",
    "history.manualChange": "手動の変更", "history.restorePointN": "復元ポイント #{0}",
    "history.settingKey": "設定キー: ", "history.source": "ソース: ", "history.today": "今日",
    "history.yesterday": "昨日", "history.earlier": "それ以前", "history.settingCapturedOne": "1 件の設定をキャプチャ",
    "history.settingCapturedMany": "{0} 件の設定をキャプチャ",
    "history.storedLocally": "変更履歴はローカルの SQLite に保存されます。",
    "settings.title": "設定",
    "settings.subtitle": "アプリの設定のみです。Windows のプライバシー設定はダッシュボードとプロファイルにあります。",
    "settings.appearance": "外観", "settings.theme": "テーマ",
    "settings.themeDesc": "Windows に合わせるか、ライトまたはダーク テーマを強制します。",
    "settings.themeDefault": "Windows の既定", "settings.themeDefaultSub": "システムのテーマに合わせる",
    "settings.themeLight": "ライト", "settings.themeLightSub": "常にライト テーマを使用",
    "settings.themeDark": "ダーク", "settings.themeDarkSub": "常にダーク テーマを使用",
    "settings.language": "言語",
    "settings.languageDesc": "PrivacyGuard のインターフェイス全体を切り替えます。日付と数値もこの言語に従います。",
    "settings.languagePlaceholder": "言語を検索", "settings.startup": "スタートアップと安全",
    "settings.startWindows": "Windows と同時に起動",
    "settings.startWindowsDesc": "現在のユーザーの Run キーを追加または削除します。管理者権限は不要です。",
    "settings.confirm": "変更を適用する前に確認",
    "settings.confirmDesc": "PrivacyGuard が Windows を変更する前に、確認ダイアログは常に表示されます。安全のためこのスイッチはロックされています。",
    "settings.confirmLock": "安全のため常に必須", "settings.record": "変更履歴を記録",
    "settings.recordDesc": "すべての設定変更をローカルの SQLite データベースに書き込みます。",
    "settings.data": "データ", "settings.logs": "ログ ファイル", "settings.openFolder": "フォルダーを開く",
    "settings.database": "履歴データベース", "settings.about": "情報",
    "settings.aboutBody": "Windows 10/11 向けの統合プライバシー & テレメトリ コントロール ダッシュボード。変更は取り消し可能で、重要な OS サービスは対象にしません。",
    "settings.checkUpdates": "更新を確認", "settings.upToDate": "最新です",
    "settings.upToDateBody": "PrivacyGuard 0.1.0 が現在のビルドです。自動更新チェックは今後のリリースで追加されます。",
    "settings.autoStart": "自動起動", "settings.autoStartError": "現在のユーザーの Run キーを更新できませんでした。",
    "dialog.beforeContinue": "続行する前に",
    "privacy.nothingToChange": "変更はありません。システムは既に要求された状態です。",
    "privacy.refusedUnknown": "不明な設定 '{0}' を拒否しました。",
    "privacy.needsAdmin": "この変更には管理者権限が必要です。[管理者として再起動] を使用してから再試行してください。",
    "privacy.applied": "{0} 件の変更を適用しました。復元ポイント #{1} を保存しました。",
    "privacy.completedErrors": "{0} 件のエラーで完了しました。復元ポイント #{1} を利用できます。",
    "privacy.couldNotComplete": "変更を完了できませんでした。{0}",
    "privacy.revertReason": "取り消し: {0}", "privacy.restoreReason": "復元ポイント #{0}",
    "privacy.telemetryRange": "テレメトリ レベルは 0–3 である必要があります。",
    "privacy.telemetryRestoreFail": "テレメトリ ポリシーを復元できませんでした。管理者権限が必要です。",
    "privacy.telemetryWriteFail": "AllowTelemetry を書き込めませんでした。管理者権限が必要です。",
    "privacy.serviceNotAllowed": "サービス '{0}' は許可リストにありません。",
    "privacy.advertisingFail": "広告 ID を更新できませんでした。",
    "privacy.activityFail": "アクティビティ履歴ポリシーを更新できませんでした。管理者権限が必要です。",
    "privacy.cortanaRestoreFail": "Cortana ポリシーを復元できませんでした。",
    "privacy.cortanaWriteFail": "AllowCortana を書き込めませんでした。管理者権限が必要です。",
    "privacy.copilotRestoreFail": "Copilot ポリシーを復元できませんでした。",
    "privacy.copilotWriteFail": "TurnOffWindowsCopilot を書き込めませんでした。管理者権限が必要です。",
    "privacy.feedbackFail": "フィードバック規則を更新できませんでした。",
    "privacy.tailoredFail": "調整されたエクスペリエンスを更新できませんでした。",
    "privacy.notImplemented": "設定 '{0}' は実装されていません。", "privacy.collectingData": "データを収集中",
}

RU = {
    "common.on": "Вкл.", "common.off": "Выкл.", "common.apply": "Применить", "common.cancel": "Отмена",
    "common.ok": "ОК", "common.refresh": "Обновить", "common.required": "Обязательно",
    "shell.standardUser": "Обычный пользователь", "shell.administrator": "Администратор",
    "shell.restartAdmin": "Перезапуск от имени админа",
    "nav.overview": "Обзор", "nav.dashboard": "Панель", "nav.profiles": "Профили",
    "nav.records": "Записи", "nav.history": "Журнал", "nav.settings": "Параметры",
    "dashboard.title": "Панель конфиденциальности", "dashboard.refresh": "Обновить",
    "dashboard.restartBannerTitle": "Перезапустите от имени администратора, чтобы применить изменения",
    "dashboard.restartBannerBody": "Просматривать всё можно уже сейчас. Политика компьютера, DiagTrack и Copilot/Cortana требуют повышения прав.",
    "dashboard.restartAdmin": "Перезапустить от имени администратора", "dashboard.adminTitle": "Администратор",
    "dashboard.privacyScore": "Оценка конфиденциальности", "dashboard.outOf100": "из 100",
    "dashboard.whyScore": "Почему такая оценка?", "dashboard.telemetryTitle": "Уровень телеметрии",
    "dashboard.telemetrySubtitle": "Политика AllowTelemetry (0–3)",
    "dashboard.applyTelemetry": "Применить уровень телеметрии",
    "dashboard.telemetryHint": "«Безопасность» действует только в Enterprise и Education. Home и Pro считают её «Базовой». Сначала создаётся точка восстановления.",
    "dashboard.howTitle": "Как PrivacyGuard применяет изменения",
    "dashboard.howBody": "Каждое изменение подтверждается, записывается только через PrivacyService, сохраняется в SQLite и может быть отменено из журнала. Критические службы Windows не затрагиваются. Рекламу и отзывы можно переключать как обычный пользователь; службы и ключи политик требуют прав администратора.",
    "dashboard.requiresAdmin": "Требуются права администратора", "dashboard.loading": "Загрузка состояния конфиденциальности…",
    "dashboard.reading": "Чтение параметров конфиденциальности Windows…",
    "dashboard.bannerElevated": "Запущено от имени администратора. Изменения можно применить сразу.",
    "dashboard.bannerLimited": "Ограниченный доступ — перезапустите от имени администратора, чтобы менять службы и политику компьютера.",
    "dashboard.refreshFailed": "Не удалось прочитать состояние конфиденциальности. См. журналы.",
    "dashboard.refreshFailedTitle": "Не удалось обновить", "dashboard.alreadySet": "Уже установлено",
    "dashboard.alreadySetMsg": "Телеметрия уже на этом уровне.", "dashboard.goodShape": "Всё в порядке",
    "dashboard.goodShapeMsg": "Рекомендуемый профиль конфиденциальности уже применён.",
    "dashboard.setTelemetry": "Установить телеметрию: {0}", "dashboard.enable": "Включить", "dashboard.disable": "Отключить",
    "dashboard.confirmBody": "PrivacyGuard применит следующие обратимые изменения:\n\n{0}\n\nТочка восстановления создаётся автоматически.",
    "dashboard.changeIncomplete": "Изменение применено не полностью", "dashboard.privacyUpdated": "Конфиденциальность обновлена",
    "dashboard.finishedErrors": "Завершено с ошибками", "dashboard.changeFailed": "Не удалось изменить",
    "dashboard.denied": "Windows отклонила изменение. Перезапустите PrivacyGuard от имени администратора и повторите попытку.",
    "dashboard.noLocalChanges": "Локальных изменений пока нет", "dashboard.lastChanged": "Последнее изменение {0}",
    "dashboard.updated": "Обновлено {0}", "dashboard.improve": "Применить рекомендуемый профиль",
    "dashboard.improveDone": "Рекомендуемый профиль применён",
    "dashboard.scoreLoading": "Чтение параметров конфиденциальности Windows…",
    "dashboard.scoreProtected": "Большая часть необязательного сбора ограничена. Некоторые службы ещё можно ужесточить.",
    "dashboard.scorePartial": "Некоторые параметры рекламы и диагностики ещё включены. Рекомендуемый профиль закроет пробелы.",
    "dashboard.scoreCollecting": "Windows использует сбор по умолчанию. Примените рекомендуемый профиль для более безопасной базы.",
    "health.protected": "Защищено", "health.needsAttention": "Требует внимания", "health.collecting": "Сбор данных",
    "health.unknown": "Неизвестно", "health.partial": "Частично", "health.limited": "Ограничено", "health.mixed": "Смешанно",
    "dashboard.section.core": "Основная телеметрия",
    "dashboard.section.coreSub": "Диагностические данные, которые Windows может отправлять, и службы, которые их передают.",
    "dashboard.section.ads": "Реклама и персонализация",
    "dashboard.section.adsSub": "Идентификаторы и история для рекламы, подсказок и временной шкалы.",
    "dashboard.section.ai": "ИИ и помощники", "dashboard.section.aiSub": "Политика Cortana и видимость Copilot на этом устройстве.",
    "dashboard.section.other": "Прочее", "dashboard.section.otherSub": "Запросы отзывов и остальные параметры конфиденциальности.",
    "telemetry.security": "Безопасность — только Enterprise", "telemetry.basic": "Базовый — рекомендуется",
    "telemetry.enhanced": "Расширенный", "telemetry.full": "Полный — по умолчанию Windows",
    "telemetry.value.security": "Безопасность", "telemetry.value.basic": "Базовый", "telemetry.value.enhanced": "Расширенный",
    "telemetry.value.full": "Полный", "common.windowsDefault": "По умолчанию Windows",
    "service.running": "Работает", "service.stopped": "Остановлена", "service.automatic": "Автоматически",
    "service.manual": "Вручную", "service.disabled": "Отключена", "service.missing": "Не установлена",
    "setting.telemetry": "Телеметрия Windows", "setting.diagTrack": "Подключённые пользовательские возможности (DiagTrack)",
    "setting.dmw": "Маршрутизация сообщений WAP Push (dmwappushservice)", "setting.advertising": "Идентификатор рекламы",
    "setting.activity": "Журнал действий / временная шкала", "setting.cortana": "Cortana", "setting.copilot": "Windows Copilot",
    "setting.feedback": "Запросы отзывов и диагностики", "setting.tailored": "Персонализированные возможности",
    "setting.telemetry.desc": "Сколько диагностических данных Windows может отправлять в Microsoft (AllowTelemetry).",
    "setting.diagTrack.desc": "Реализует подключённые пользовательские возможности и телеметрию. Остановка снижает телеметрию, но может повлиять на часть диагностики.",
    "setting.dmw.desc": "Маршрутизация WAP Push для некоторых сценариев телеметрии и MDM. Для большинства домашних пользователей безопасно отключать.",
    "setting.advertising.desc": "Идентификатор, который приложения могут использовать для более релевантной рекламы.",
    "setting.activity.desc": "Собирает действия приложений и просмотра для временной шкалы и возобновления на других устройствах.",
    "setting.cortana.desc": "Политика AllowCortana. В Windows 11 в основном затрагивает оставшиеся компоненты Cortana.",
    "setting.copilot.desc": "Политика TurnOffWindowsCopilot. Эффект зависит от сборки Windows и способа установки Copilot.",
    "setting.feedback.desc": "Частота Центра отзывов и опросов удовлетворённости.",
    "setting.tailored.desc": "Использует диагностические данные для персонализации подсказок, рекламы и рекомендаций.",
    "setting.telemetry.side": "Уровень «Безопасность» только для Enterprise игнорируется в Home/Pro (Windows повышает его до «Базовый»).",
    "setting.diagTrack.side": "Необязательные диагностические возможности и часть функций отзывов/телеметрии могут остановиться. Windows Update продолжит работать.",
    "setting.dmw.side": "Редкие сценарии WAP Push / доставки MDM могут быть затронуты.",
    "setting.cortana.side": "Cortana (если есть) будет отключена политикой. Поиск Windows останется доступен.",
    "setting.copilot.side": "Интерфейс Copilot может быть скрыт или проигнорирован в зависимости от сборки. Может потребоваться выход из учётной записи.",
    "setting.activity.side": "Временная шкала и возобновление действий на других устройствах прекратятся.",
    "factor.telemetry": "Уровень телеметрии", "factor.diagTrack": "DiagTrack", "factor.dmw": "Служба WAP Push",
    "factor.advertising": "Идентификатор рекламы", "factor.activity": "Журнал действий", "factor.cortana": "Cortana",
    "factor.copilot": "Copilot", "factor.feedback": "Запросы отзывов", "factor.tailored": "Персонализированные возможности",
    "profile.recommended.title": "Рекомендуемая конфиденциальность",
    "profile.recommended.summary": "Сокращает рекламу и необязательную диагностику, сохраняя работоспособность Windows Update и защиты.",
    "profile.recommended.details": "Телеметрия: базовая. Идентификатор рекламы выкл. Отправка действий выкл. Отзывы выкл. DiagTrack продолжает работать для диагностики Update.",
    "profile.recommended.warning": "Некоторые персональные подсказки, реклама и синхронизация временной шкалы прекратятся. Это не затрагивает Windows Security и Update.",
    "profile.recommended.h1": "Телеметрия: базовая", "profile.recommended.h2": "Идентификатор рекламы выкл.",
    "profile.recommended.h3": "Журнал действий выкл.", "profile.recommended.h4": "Отзывы выкл.",
    "profile.recommended.h5": "DiagTrack продолжает работать",
    "profile.maximum.title": "Максимальная конфиденциальность",
    "profile.maximum.summary": "Самая строгая поддерживаемая конфигурация. Некоторые необязательные возможности Windows могут перестать работать.",
    "profile.maximum.details": "Телеметрия: безопасность (или базовая в Home/Pro). DiagTrack и dmwappushservice остановлены. Реклама, журнал, политика Cortana/Copilot и отзывы выключены.",
    "profile.maximum.warning": "Подсветка поиска, временная шкала, необязательная диагностика и часть персонализации Store могут перестать работать. Обратимо из журнала или «Восстановить по умолчанию». В Home/Pro Windows не соблюдает телеметрию «Безопасность» (0).",
    "profile.maximum.h1": "Телеметрия: безопасность или базовая", "profile.maximum.h2": "DiagTrack остановлена",
    "profile.maximum.h3": "WAP Push отключён", "profile.maximum.h4": "Реклама, шкала и Copilot выкл.",
    "profile.maximum.h5": "Отзывы и персонализация выкл.",
    "profile.balanced.title": "Сбалансированный",
    "profile.balanced.summary": "Оставляет диагностические службы включёнными, отключает идентификатор рекламы и отправку действий.",
    "profile.balanced.details": "Телеметрия: полная. DiagTrack работает. Идентификатор рекламы выкл. Локальные действия разрешены, облачная отправка выкл. Copilot без изменений.",
    "profile.balanced.warning": "Windows по-прежнему будет отправлять необязательные диагностические данные. Сокращаются только реклама и отправка действий.",
    "profile.balanced.h1": "Телеметрия: полная", "profile.balanced.h2": "DiagTrack работает",
    "profile.balanced.h3": "Идентификатор рекламы выкл.", "profile.balanced.h4": "Отправка действий выкл.",
    "profile.balanced.h5": "Copilot без изменений",
    "profile.restore.title": "Восстановить по умолчанию",
    "profile.restore.summary": "Удаляет значения политик PrivacyGuard и возвращает службы к типичным параметрам Windows.",
    "profile.restore.details": "Удаляет политику AllowTelemetry, повторно включает DiagTrack (автоматически + работает) и восстанавливает рекламу, журнал, Cortana/Copilot и отзывы.",
    "profile.restore.warning": "Это восстанавливает параметры сбора данных по умолчанию. Сторонние правки, не связанные с этим, не откатываются.",
    "profile.restore.h1": "Телеметрия: по умолчанию Windows", "profile.restore.h2": "DiagTrack автоматически",
    "profile.restore.h3": "Идентификатор рекламы вкл.", "profile.restore.h4": "Журнал действий вкл.",
    "profile.restore.h5": "Cortana и Copilot восстановлены",
    "profiles.title": "Профили конфиденциальности",
    "profiles.subtitle": "Конфигурации в один щелчок. Каждое применение показывает подтверждение, создаёт точку восстановления и полностью обратимо.",
    "profiles.safety": "Безопасность", "profiles.recommendedBadge": "Рекомендуется", "profiles.active": "Активен",
    "profiles.beforeContinue": "Прежде чем продолжить", "profiles.scoreNone": "Влияние на оценку: без изменений",
    "profiles.scoreUp": "Влияние на оценку: +{0}", "profiles.scoreDown": "Влияние на оценку: {0}",
    "profiles.scoreUnknown": "Влияние на оценку: —", "profiles.lastApplied": "Последнее применение: {0} в {1}",
    "profiles.today": "Сегодня", "profiles.yesterday": "Вчера", "profiles.review": "Проверить и применить",
    "profiles.currentlyApplied": "Сейчас применён", "profiles.alreadyTitle": "Уже применён",
    "profiles.alreadyMsg": "{0} уже применён.", "profiles.adminTitle": "Требуется администратор",
    "profiles.adminBody": "Этот профиль меняет политики или службы на уровне компьютера. Перезапустите PrivacyGuard от имени администратора и примените снова.",
    "profiles.applyTitle": "Применить {0}?", "profiles.confirmBody": "Будут применены следующие обратимые изменения:\n\n{0}",
    "profiles.appliedTitle": "Профиль применён", "profiles.partialTitle": "Профиль применён частично",
    "profiles.failedTitle": "Сбой профиля", "profiles.choose": "Выберите профиль. Каждое применение сначала создаёт точку восстановления.",
    "history.title": "Журнал изменений",
    "history.subtitle": "Каждое изменение записывается локально. Отмените один параметр или восстановите полную резервную точку.",
    "history.audit": "Локальный журнал аудита", "history.changes": "Изменения", "history.filterAll": "Все",
    "history.filterActive": "Активные", "history.filterReverted": "Отменённые", "history.revertSelected": "Отменить выбранные",
    "history.revertN": "Отменить {0} изм.", "history.noneSelected": "Ничего не выбрано",
    "history.changeSelectedOne": "Выбрано 1 изменение", "history.changeSelectedMany": "Выбрано изменений: {0}",
    "history.restoreSelectedOne": "Выбрана 1 точка восстановления",
    "history.restoreSelectedMany": "Выбрано точек восстановления: {0}",
    "history.emptyTitle": "Журнала пока нет", "history.emptyFilterTitle": "Нет подходящих изменений",
    "history.emptyMsg": "Изменений ещё нет. Примените профиль или переключите параметр — они появятся здесь.",
    "history.emptyFilterMsg": "Нет изменений, соответствующих этому фильтру.",
    "history.statusEmpty": "Изменений ещё нет. Применённые параметры появятся здесь.",
    "history.statusCounts": "Записано изменений: {0}, точек восстановления: {1}.",
    "history.unavailable": "Журнал недоступен", "history.alreadyRevertedTitle": "Уже отменено",
    "history.alreadyRevertedBody": "Выбранные записи журнала уже отмечены как отменённые.",
    "history.revertOne": "Отменить это изменение?", "history.revertMany": "Отменить {0} изменений?",
    "history.revertBody": "Будут восстановлены следующие обратимые изменения:\n\n{0}",
    "history.revertWarning": "Перед каждой отменой будет создана новая точка восстановления.",
    "history.revertFailed": "Не удалось отменить", "history.restoreTitle": "Восстановить эту резервную копию?",
    "history.restoreBody": "Точка восстановления № {0} от {1} будет применена повторно ({2} парам.).",
    "history.restoreWarning": "Текущие значения сначала сохраняются, поэтому само восстановление тоже обратимо.",
    "history.restoreFailed": "Не удалось восстановить", "history.restored": "Восстановлено",
    "history.restorePoints": "Точки восстановления", "history.restorePointsSub": "Снимки, сделанные перед каждым изменением.",
    "history.noRestoreTitle": "Точек восстановления пока нет",
    "history.noRestoreBody": "Снимок появится здесь при первом изменении параметра.",
    "history.restoreButton": "Восстановить выбранную копию", "history.reverted": "Отменено",
    "history.manualChange": "Ручное изменение", "history.restorePointN": "Точка восстановления № {0}",
    "history.settingKey": "Ключ параметра: ", "history.source": "Источник: ", "history.today": "Сегодня",
    "history.yesterday": "Вчера", "history.earlier": "Ранее", "history.settingCapturedOne": "Сохранён 1 параметр",
    "history.settingCapturedMany": "Сохранено параметров: {0}",
    "history.storedLocally": "Журнал изменений хранится локально в SQLite.",
    "settings.title": "Параметры",
    "settings.subtitle": "Только настройки приложения. Параметры конфиденциальности Windows находятся на панели и в профилях.",
    "settings.appearance": "Оформление", "settings.theme": "Тема",
    "settings.themeDesc": "Следовать Windows или принудительно использовать светлую или тёмную тему.",
    "settings.themeDefault": "По умолчанию Windows", "settings.themeDefaultSub": "Совпадает с темой системы",
    "settings.themeLight": "Светлая", "settings.themeLightSub": "Всегда использовать светлую тему",
    "settings.themeDark": "Тёмная", "settings.themeDarkSub": "Всегда использовать тёмную тему",
    "settings.language": "Язык",
    "settings.languageDesc": "Меняет весь интерфейс PrivacyGuard. Даты и числа также следуют этому языку.",
    "settings.languagePlaceholder": "Поиск языков", "settings.startup": "Запуск и безопасность",
    "settings.startWindows": "Запускать вместе с Windows",
    "settings.startWindowsDesc": "Добавляет или удаляет ключ Run текущего пользователя. Права администратора не нужны.",
    "settings.confirm": "Подтверждать перед применением изменений",
    "settings.confirmDesc": "Диалоги подтверждения всегда показываются до того, как PrivacyGuard изменит Windows. Этот переключатель заблокирован ради безопасности.",
    "settings.confirmLock": "Всегда обязательно для безопасности", "settings.record": "Записывать журнал изменений",
    "settings.recordDesc": "Записывает каждое изменение параметра в локальную базу SQLite.",
    "settings.data": "Данные", "settings.logs": "Файлы журналов", "settings.openFolder": "Открыть папку",
    "settings.database": "База журнала", "settings.about": "О программе",
    "settings.aboutBody": "Единая панель управления конфиденциальностью и телеметрией для Windows 10/11. Изменения обратимы и никогда не затрагивают критические службы ОС.",
    "settings.checkUpdates": "Проверить обновления", "settings.upToDate": "У вас актуальная версия",
    "settings.upToDateBody": "PrivacyGuard 0.1.0 — текущая сборка. Автоматическая проверка обновлений будет добавлена в следующем выпуске.",
    "settings.autoStart": "Автозапуск", "settings.autoStartError": "Не удалось обновить ключ Run текущего пользователя.",
    "dialog.beforeContinue": "Прежде чем продолжить",
    "privacy.nothingToChange": "Менять нечего — система уже соответствует запрошенному состоянию.",
    "privacy.refusedUnknown": "Отклонён неизвестный параметр «{0}».",
    "privacy.needsAdmin": "Для этого изменения нужны права администратора. Используйте «Перезапустить от имени администратора» и повторите попытку.",
    "privacy.applied": "Применено изменений: {0}. Сохранена точка восстановления № {1}.",
    "privacy.completedErrors": "Завершено с ошибками: {0}. Доступна точка восстановления № {1}.",
    "privacy.couldNotComplete": "Не удалось завершить изменение. {0}",
    "privacy.revertReason": "Отмена: {0}", "privacy.restoreReason": "Точка восстановления № {0}",
    "privacy.telemetryRange": "Уровень телеметрии должен быть 0–3.",
    "privacy.telemetryRestoreFail": "Не удалось восстановить политику телеметрии. Нужны права администратора.",
    "privacy.telemetryWriteFail": "Не удалось записать AllowTelemetry. Нужны права администратора.",
    "privacy.serviceNotAllowed": "Служба «{0}» отсутствует в списке разрешённых.",
    "privacy.advertisingFail": "Не удалось обновить идентификатор рекламы.",
    "privacy.activityFail": "Не удалось обновить политику журнала действий. Нужны права администратора.",
    "privacy.cortanaRestoreFail": "Не удалось восстановить политику Cortana.",
    "privacy.cortanaWriteFail": "Не удалось записать AllowCortana. Нужны права администратора.",
    "privacy.copilotRestoreFail": "Не удалось восстановить политику Copilot.",
    "privacy.copilotWriteFail": "Не удалось записать TurnOffWindowsCopilot. Нужны права администратора.",
    "privacy.feedbackFail": "Не удалось обновить правила отзывов.",
    "privacy.tailoredFail": "Не удалось обновить персонализированные возможности.",
    "privacy.notImplemented": "Параметр «{0}» не реализован.", "privacy.collectingData": "Сбор данных",
}

AR = {
    "common.on": "تشغيل", "common.off": "إيقاف", "common.apply": "تطبيق", "common.cancel": "إلغاء",
    "common.ok": "موافق", "common.refresh": "تحديث", "common.required": "مطلوب",
    "shell.standardUser": "مستخدم قياسي", "shell.administrator": "مسؤول", "shell.restartAdmin": "إعادة التشغيل كمسؤول",
    "nav.overview": "نظرة عامة", "nav.dashboard": "لوحة المعلومات", "nav.profiles": "الملفات",
    "nav.records": "السجلات", "nav.history": "السجل", "nav.settings": "الإعدادات",
    "dashboard.title": "لوحة خصوصية", "dashboard.refresh": "تحديث",
    "dashboard.restartBannerTitle": "أعد التشغيل كمسؤول لتطبيق التغييرات",
    "dashboard.restartBannerBody": "يمكنك فحص كل شيء الآن. سياسة الجهاز وDiagTrack وCopilot/Cortana تتطلب رفع الصلاحيات.",
    "dashboard.restartAdmin": "إعادة التشغيل كمسؤول", "dashboard.adminTitle": "مسؤول",
    "dashboard.privacyScore": "درجة الخصوصية", "dashboard.outOf100": "من 100",
    "dashboard.whyScore": "لماذا هذه الدرجة؟", "dashboard.telemetryTitle": "مستوى القياس عن بُعد",
    "dashboard.telemetrySubtitle": "نهج AllowTelemetry (0–3)",
    "dashboard.applyTelemetry": "تطبيق مستوى القياس عن بُعد",
    "dashboard.telemetryHint": "يُحترم مستوى الأمان فقط في Enterprise وEducation. يعتبره Home وPro أساسيًا. يُنشأ نقطة استعادة أولًا.",
    "dashboard.howTitle": "كيف يطبّق PrivacyGuard التغييرات",
    "dashboard.howBody": "كل تغيير يُؤكَّد ويُكتب عبر PrivacyService فقط ويُحفظ في SQLite ويمكن التراجع عنه من السجل. لا تُمس خدمات Windows الحرجة أبدًا. يمكن تبديل الإعلانات والملاحظات كمستخدم قياسي؛ الخدمات ومفاتيح النهج تحتاج إلى مسؤول.",
    "dashboard.requiresAdmin": "يتطلب مسؤولًا", "dashboard.loading": "جارٍ تحميل حالة الخصوصية…",
    "dashboard.reading": "جارٍ قراءة إعدادات خصوصية Windows…",
    "dashboard.bannerElevated": "يعمل كمسؤول. يمكن تطبيق التغييرات فورًا.",
    "dashboard.bannerLimited": "وصول محدود — أعد التشغيل كمسؤول لتغيير الخدمات ونهج الجهاز.",
    "dashboard.refreshFailed": "تعذّر قراءة حالة الخصوصية. راجع السجلات.",
    "dashboard.refreshFailedTitle": "فشل التحديث", "dashboard.alreadySet": "مضبوط بالفعل",
    "dashboard.alreadySetMsg": "القياس عن بُعد عند هذا المستوى بالفعل.", "dashboard.goodShape": "كل شيء على ما يرام",
    "dashboard.goodShapeMsg": "ملف الخصوصية الموصى به مطبَّق بالفعل.",
    "dashboard.setTelemetry": "تعيين القياس عن بُعد إلى {0}", "dashboard.enable": "تمكين", "dashboard.disable": "تعطيل",
    "dashboard.confirmBody": "سيطبق PrivacyGuard التغييرات التالية القابلة للتراجع:\n\n{0}\n\nتُنشأ نقطة استعادة تلقائيًا.",
    "dashboard.changeIncomplete": "لم يُطبَّق التغيير بالكامل", "dashboard.privacyUpdated": "تم تحديث الخصوصية",
    "dashboard.finishedErrors": "اكتمل مع أخطاء", "dashboard.changeFailed": "فشل التغيير",
    "dashboard.denied": "رفض Windows التغيير. أعد تشغيل PrivacyGuard كمسؤول ثم حاول مرة أخرى.",
    "dashboard.noLocalChanges": "لا توجد تغييرات محلية بعد", "dashboard.lastChanged": "آخر تغيير {0}",
    "dashboard.updated": "حُدِّث {0}", "dashboard.improve": "تطبيق الملف الموصى به",
    "dashboard.improveDone": "الملف الموصى به مطبَّق",
    "dashboard.scoreLoading": "جارٍ قراءة إعدادات خصوصية Windows…",
    "dashboard.scoreProtected": "معظم الجمع الاختياري محدود. ما زال بإمكانك تشديد بعض الخدمات.",
    "dashboard.scorePartial": "بعض خيارات الإعلانات والتشخيص ما زالت قيد التشغيل. الملف الموصى به يسد الفجوات.",
    "dashboard.scoreCollecting": "يستخدم Windows الجمع الافتراضي. طبّق الملف الموصى به لأساس أكثر أمانًا.",
    "health.protected": "محمي", "health.needsAttention": "يحتاج انتباهاً", "health.collecting": "يجمع البيانات",
    "health.unknown": "غير معروف", "health.partial": "جزئي", "health.limited": "محدود", "health.mixed": "مختلط",
    "dashboard.section.core": "القياس عن بُعد الأساسي",
    "dashboard.section.coreSub": "بيانات التشخيص التي قد يرسلها Windows والخدمات التي تنقلها.",
    "dashboard.section.ads": "الإعلانات والتخصيص",
    "dashboard.section.adsSub": "المعرفات والسجل المستخدمة للإعلانات والنصائح والمخطط الزمني.",
    "dashboard.section.ai": "الذكاء الاصطناعي والمساعدون", "dashboard.section.aiSub": "نهج Cortana وظهور Copilot على هذا الجهاز.",
    "dashboard.section.other": "أخرى", "dashboard.section.otherSub": "مطالبات الملاحظات وخيارات الخصوصية المتبقية.",
    "telemetry.security": "أمان — للمؤسسات فقط", "telemetry.basic": "أساسي — موصى به",
    "telemetry.enhanced": "محسّن", "telemetry.full": "كامل — افتراضي Windows",
    "telemetry.value.security": "أمان", "telemetry.value.basic": "أساسي", "telemetry.value.enhanced": "محسّن",
    "telemetry.value.full": "كامل", "common.windowsDefault": "افتراضي Windows",
    "service.running": "قيد التشغيل", "service.stopped": "متوقف", "service.automatic": "تلقائي",
    "service.manual": "يدوي", "service.disabled": "معطّل", "service.missing": "غير مثبت",
    "setting.telemetry": "قياس Windows عن بُعد", "setting.diagTrack": "تجارب المستخدم المتصلة (DiagTrack)",
    "setting.dmw": "توجيه رسائل WAP Push (dmwappushservice)", "setting.advertising": "معرّف الإعلان",
    "setting.activity": "سجل النشاط / المخطط الزمني", "setting.cortana": "Cortana", "setting.copilot": "Windows Copilot",
    "setting.feedback": "مطالبات الملاحظات والتشخيص", "setting.tailored": "التجارب المخصصة",
    "setting.telemetry.desc": "كم من بيانات التشخيص يمكن أن يرسلها Windows إلى Microsoft (AllowTelemetry).",
    "setting.diagTrack.desc": "ينفّذ تجارب المستخدم المتصلة والقياس عن بُعد. إيقافه يقلل القياس لكنه قد يؤثر على بعض التشخيصات.",
    "setting.dmw.desc": "توجيه WAP Push المستخدم في بعض سيناريوهات القياس وMDM. آمن للتعطيل لمعظم المستخدمين المنزليين.",
    "setting.advertising.desc": "معرّف يمكن للتطبيقات استخدامه لعرض إعلانات أكثر صلة.",
    "setting.activity.desc": "يجمع نشاط التطبيقات والتصفح للمخطط الزمني والاستئناف عبر الأجهزة.",
    "setting.cortana.desc": "نهج AllowCortana. في Windows 11 يؤثر أساسًا على مكونات Cortana المتبقية.",
    "setting.copilot.desc": "نهج TurnOffWindowsCopilot. تعتمد الفعالية على إصدار Windows وكيفية تثبيت Copilot.",
    "setting.feedback.desc": "تكرار مركز الملاحظات واستطلاعات الرضا.",
    "setting.tailored.desc": "يستخدم بيانات التشخيص لتخصيص النصائح والإعلانات والتوصيات.",
    "setting.telemetry.side": "يُتجاهل مستوى الأمان الخاص بالمؤسسات على Home/Pro (يرفعه Windows إلى أساسي).",
    "setting.diagTrack.side": "قد تتوقف تجارب التشخيص الاختيارية وبعض ميزات الملاحظات/القياس. يستمر Windows Update في العمل.",
    "setting.dmw.side": "قد تتأثر سيناريوهات نادرة لـ WAP Push / تسليم MDM.",
    "setting.cortana.side": "سيُعطَّل Cortana (إن وُجد) بالنهج. يبقى بحث Windows متاحًا.",
    "setting.copilot.side": "قد تُخفى واجهة Copilot أو تُتجاهل حسب إصدار Windows. قد يلزم تسجيل الخروج.",
    "setting.activity.side": "سيتوقف المخطط الزمني واستئناف النشاط عبر الأجهزة.",
    "factor.telemetry": "مستوى القياس عن بُعد", "factor.diagTrack": "DiagTrack", "factor.dmw": "خدمة WAP Push",
    "factor.advertising": "معرّف الإعلان", "factor.activity": "سجل النشاط", "factor.cortana": "Cortana",
    "factor.copilot": "Copilot", "factor.feedback": "مطالبات الملاحظات", "factor.tailored": "التجارب المخصصة",
    "profile.recommended.title": "خصوصية موصى بها",
    "profile.recommended.summary": "يقلل الإعلانات والتشخيص الاختياري مع الإبقاء على Windows Update والأمان سليمين.",
    "profile.recommended.details": "القياس: أساسي. معرّف الإعلان متوقف. رفع النشاط متوقف. الملاحظات متوقفة. يبقى DiagTrack قيد التشغيل لتشخيص التحديث.",
    "profile.recommended.warning": "ستتوقف بعض النصائح المخصصة والإعلانات ومزامنة المخطط الزمني. لا يؤثر ذلك على أمان Windows أو التحديث.",
    "profile.recommended.h1": "القياس: أساسي", "profile.recommended.h2": "معرّف الإعلان متوقف",
    "profile.recommended.h3": "سجل النشاط متوقف", "profile.recommended.h4": "الملاحظات متوقفة",
    "profile.recommended.h5": "DiagTrack يبقى قيد التشغيل",
    "profile.maximum.title": "أقصى خصوصية",
    "profile.maximum.summary": "أكثر إعداد مدعوم تقييدًا. قد تتوقف بعض تجارب Windows الاختيارية.",
    "profile.maximum.details": "القياس: أمان (أو أساسي على Home/Pro). إيقاف DiagTrack وdmwappushservice. إيقاف الإعلانات والسجل ونهج Cortana/Copilot والملاحظات.",
    "profile.maximum.warning": "قد تتوقف تمييزات البحث والمخطط الزمني والتشخيص الاختياري وبعض تخصيص المتجر. قابل للتراجع من السجل أو استعادة الافتراضي. على Home/Pro لن يحترم Windows قياس الأمان (0).",
    "profile.maximum.h1": "القياس: أمان أو أساسي", "profile.maximum.h2": "DiagTrack متوقف",
    "profile.maximum.h3": "WAP Push معطّل", "profile.maximum.h4": "الإعلانات والمخطط وCopilot متوقفة",
    "profile.maximum.h5": "الملاحظات والتجارب متوقفة",
    "profile.balanced.title": "متوازن",
    "profile.balanced.summary": "يبقي خدمات التشخيص قيد التشغيل ويعطّل معرّف الإعلان ورفع النشاط.",
    "profile.balanced.details": "القياس: كامل. DiagTrack قيد التشغيل. معرّف الإعلان متوقف. النشاط المحلي مسموح، الرفع إلى السحابة متوقف. Copilot دون تغيير.",
    "profile.balanced.warning": "سيظل Windows يرسل بيانات تشخيص اختيارية. يُقلَّل الإعلان ورفع النشاط فقط.",
    "profile.balanced.h1": "القياس: كامل", "profile.balanced.h2": "DiagTrack قيد التشغيل",
    "profile.balanced.h3": "معرّف الإعلان متوقف", "profile.balanced.h4": "رفع النشاط متوقف",
    "profile.balanced.h5": "Copilot دون تغيير",
    "profile.restore.title": "استعادة الافتراضي",
    "profile.restore.summary": "يزيل قيم نهج PrivacyGuard ويعيد الخدمات إلى إعدادات Windows النموذجية.",
    "profile.restore.details": "يحذف نهج AllowTelemetry ويعيد تمكين DiagTrack (تلقائي + قيد التشغيل) ويستعيد معرّف الإعلان والسجل وCortana/Copilot والملاحظات.",
    "profile.restore.warning": "يستعيد هذا إعدادات جمع البيانات الافتراضية. لا يتراجع عن تعديلات الجهات الخارجية غير ذات الصلة.",
    "profile.restore.h1": "القياس: افتراضي Windows", "profile.restore.h2": "DiagTrack تلقائي",
    "profile.restore.h3": "معرّف الإعلان تشغيل", "profile.restore.h4": "سجل النشاط تشغيل",
    "profile.restore.h5": "استعادة Cortana وCopilot",
    "profiles.title": "ملفات الخصوصية",
    "profiles.subtitle": "إعدادات بنقرة واحدة. كل تطبيق يعرض تأكيدًا وينشئ نقطة استعادة وهو قابل للتراجع بالكامل.",
    "profiles.safety": "أمان", "profiles.recommendedBadge": "موصى به", "profiles.active": "نشط",
    "profiles.beforeContinue": "قبل المتابعة", "profiles.scoreNone": "تأثير الدرجة: لا تغيير",
    "profiles.scoreUp": "تأثير الدرجة: +{0}", "profiles.scoreDown": "تأثير الدرجة: {0}",
    "profiles.scoreUnknown": "تأثير الدرجة: —", "profiles.lastApplied": "آخر تطبيق: {0} في {1}",
    "profiles.today": "اليوم", "profiles.yesterday": "أمس", "profiles.review": "مراجعة وتطبيق",
    "profiles.currentlyApplied": "مطبَّق حاليًا", "profiles.alreadyTitle": "مطبَّق بالفعل",
    "profiles.alreadyMsg": "{0} مطبَّق بالفعل.", "profiles.adminTitle": "المسؤول مطلوب",
    "profiles.adminBody": "يغيّر هذا الملف نهجًا أو خدمات على مستوى الجهاز. أعد تشغيل PrivacyGuard كمسؤول ثم طبّقه مرة أخرى.",
    "profiles.applyTitle": "تطبيق {0}؟", "profiles.confirmBody": "ستُطبَّق التغييرات التالية القابلة للتراجع:\n\n{0}",
    "profiles.appliedTitle": "تم تطبيق الملف", "profiles.partialTitle": "طُبّق الملف جزئيًا",
    "profiles.failedTitle": "فشل الملف", "profiles.choose": "اختر ملفًا. كل تطبيق ينشئ نقطة استعادة أولًا.",
    "history.title": "سجل التغييرات",
    "history.subtitle": "يُسجَّل كل تغيير محليًا. تراجع عن إعداد واحد أو استعد نقطة نسخ احتياطي كاملة.",
    "history.audit": "سجل تدقيق محلي", "history.changes": "التغييرات", "history.filterAll": "الكل",
    "history.filterActive": "نشطة", "history.filterReverted": "متراجع عنها", "history.revertSelected": "التراجع عن المحدد",
    "history.revertN": "التراجع عن {0} تغييرات", "history.noneSelected": "لم يُحدد شيء",
    "history.changeSelectedOne": "تم تحديد تغيير واحد", "history.changeSelectedMany": "تم تحديد {0} تغييرات",
    "history.restoreSelectedOne": "تم تحديد نقطة استعادة واحدة",
    "history.restoreSelectedMany": "تم تحديد {0} نقاط استعادة",
    "history.emptyTitle": "لا يوجد سجل بعد", "history.emptyFilterTitle": "لا توجد تغييرات مطابقة",
    "history.emptyMsg": "لا توجد تغييرات بعد. طبّق ملفًا أو بدّل إعدادًا ليظهر هنا.",
    "history.emptyFilterMsg": "لا توجد تغييرات تطابق هذا التصفية.",
    "history.statusEmpty": "لا توجد تغييرات بعد. ستظهر الإعدادات المطبَّقة هنا.",
    "history.statusCounts": "{0} تغيير(ات) مسجَّل، {1} نقطة(نقاط) استعادة.",
    "history.unavailable": "السجل غير متاح", "history.alreadyRevertedTitle": "تم التراجع بالفعل",
    "history.alreadyRevertedBody": "عناصر السجل المحددة كانت معلَّمة بالفعل كمتراجع عنها.",
    "history.revertOne": "التراجع عن هذا التغيير؟", "history.revertMany": "التراجع عن {0} تغييرات؟",
    "history.revertBody": "ستُستعاد التغييرات التالية القابلة للتراجع:\n\n{0}",
    "history.revertWarning": "ستُنشأ نقطة استعادة جديدة قبل كل تراجع.",
    "history.revertFailed": "فشل التراجع", "history.restoreTitle": "استعادة هذه النسخة؟",
    "history.restoreBody": "ستُعاد نقطة الاستعادة رقم {0} من {1} ({2} إعداد(ات)).",
    "history.restoreWarning": "تُحفظ القيم الحالية أولًا لذا هذه الاستعادة نفسها قابلة للتراجع.",
    "history.restoreFailed": "فشلت الاستعادة", "history.restored": "تمت الاستعادة",
    "history.restorePoints": "نقاط الاستعادة", "history.restorePointsSub": "لقطات أُخذت قبل كل تغيير.",
    "history.noRestoreTitle": "لا توجد نقاط استعادة بعد",
    "history.noRestoreBody": "ستظهر لقطة هنا عند تغيير إعداد لأول مرة.",
    "history.restoreButton": "استعادة النسخة المحددة", "history.reverted": "متراجع",
    "history.manualChange": "تغيير يدوي", "history.restorePointN": "نقطة استعادة رقم {0}",
    "history.settingKey": "مفتاح الإعداد: ", "history.source": "المصدر: ", "history.today": "اليوم",
    "history.yesterday": "أمس", "history.earlier": "أقدم", "history.settingCapturedOne": "تم التقاط إعداد واحد",
    "history.settingCapturedMany": "تم التقاط {0} إعدادات",
    "history.storedLocally": "يُخزَّن سجل التغييرات محليًا في SQLite.",
    "settings.title": "الإعدادات",
    "settings.subtitle": "تفضيلات التطبيق فقط. إعدادات خصوصية Windows موجودة في لوحة المعلومات والملفات.",
    "settings.appearance": "المظهر", "settings.theme": "السمة",
    "settings.themeDesc": "اتبع Windows أو افرض سمة فاتحة أو داكنة.",
    "settings.themeDefault": "افتراضي Windows", "settings.themeDefaultSub": "مطابقة سمة النظام",
    "settings.themeLight": "فاتح", "settings.themeLightSub": "استخدم السمة الفاتحة دائمًا",
    "settings.themeDark": "داكن", "settings.themeDarkSub": "استخدم السمة الداكنة دائمًا",
    "settings.language": "اللغة",
    "settings.languageDesc": "يغيّر واجهة PrivacyGuard بالكامل. تتبع التواريخ والأرقام هذه اللغة أيضًا.",
    "settings.languagePlaceholder": "البحث عن اللغات", "settings.startup": "التشغيل والأمان",
    "settings.startWindows": "البدء مع Windows",
    "settings.startWindowsDesc": "يضيف أو يزيل مفتاح Run للمستخدم الحالي. لا يتطلب حقوق مسؤول.",
    "settings.confirm": "التأكيد قبل تطبيق التغييرات",
    "settings.confirmDesc": "تظهر حوارات التأكيد دائمًا قبل أن يغيّر PrivacyGuard Windows. هذا المفتاح مقفل للأمان.",
    "settings.confirmLock": "مطلوب دائمًا للأمان", "settings.record": "تسجيل سجل التغييرات",
    "settings.recordDesc": "يكتب كل تغيير إعداد إلى قاعدة SQLite المحلية.",
    "settings.data": "البيانات", "settings.logs": "ملفات السجل", "settings.openFolder": "فتح المجلد",
    "settings.database": "قاعدة بيانات السجل", "settings.about": "حول",
    "settings.aboutBody": "لوحة تحكم موحّدة للخصوصية والقياس عن بُعد لنظامي Windows 10/11. التغييرات قابلة للتراجع ولا تستهدف أبدًا خدمات نظام حرجة.",
    "settings.checkUpdates": "التحقق من التحديثات", "settings.upToDate": "أنت محدَّث",
    "settings.upToDateBody": "PrivacyGuard 0.1.0 هو الإصدار الحالي. ستُضاف فحوصات التحديث التلقائية في إصدار لاحق.",
    "settings.autoStart": "بدء تلقائي", "settings.autoStartError": "تعذّر تحديث مفتاح Run للمستخدم الحالي.",
    "dialog.beforeContinue": "قبل المتابعة",
    "privacy.nothingToChange": "لا شيء للتغيير — النظام يطابق الحالة المطلوبة بالفعل.",
    "privacy.refusedUnknown": "رُفض إعداد غير معروف '{0}'.",
    "privacy.needsAdmin": "يتطلب هذا التغيير حقوق مسؤول. استخدم إعادة التشغيل كمسؤول ثم حاول مرة أخرى.",
    "privacy.applied": "تم تطبيق {0} تغيير(ات). حُفظت نقطة الاستعادة رقم {1}.",
    "privacy.completedErrors": "اكتمل مع {0} خطأ/أخطاء. نقطة الاستعادة رقم {1} متاحة.",
    "privacy.couldNotComplete": "تعذّر إكمال التغيير. {0}",
    "privacy.revertReason": "تراجع: {0}", "privacy.restoreReason": "نقطة استعادة رقم {0}",
    "privacy.telemetryRange": "يجب أن يكون مستوى القياس عن بُعد بين 0 و3.",
    "privacy.telemetryRestoreFail": "تعذّر استعادة نهج القياس عن بُعد. حقوق المسؤول مطلوبة.",
    "privacy.telemetryWriteFail": "تعذّر كتابة AllowTelemetry. حقوق المسؤول مطلوبة.",
    "privacy.serviceNotAllowed": "الخدمة '{0}' ليست في القائمة المسموح بها.",
    "privacy.advertisingFail": "تعذّر تحديث معرّف الإعلان.",
    "privacy.activityFail": "تعذّر تحديث نهج سجل النشاط. حقوق المسؤول مطلوبة.",
    "privacy.cortanaRestoreFail": "تعذّر استعادة نهج Cortana.",
    "privacy.cortanaWriteFail": "تعذّر كتابة AllowCortana. حقوق المسؤول مطلوبة.",
    "privacy.copilotRestoreFail": "تعذّر استعادة نهج Copilot.",
    "privacy.copilotWriteFail": "تعذّر كتابة TurnOffWindowsCopilot. حقوق المسؤول مطلوبة.",
    "privacy.feedbackFail": "تعذّر تحديث قواعد الملاحظات.",
    "privacy.tailoredFail": "تعذّر تحديث التجارب المخصصة.",
    "privacy.notImplemented": "الإعداد '{0}' غير منفَّذ.", "privacy.collectingData": "يجمع البيانات",
}
