"""Remaining localization maps for PrivacyGuard."""

FR = {
    "common.on": "Activé", "common.off": "Désactivé", "common.apply": "Appliquer", "common.cancel": "Annuler",
    "common.ok": "OK", "common.refresh": "Actualiser", "common.required": "Obligatoire",
    "shell.standardUser": "Utilisateur standard", "shell.administrator": "Administrateur",
    "shell.restartAdmin": "Redémarrer en admin",
    "nav.overview": "Aperçu", "nav.dashboard": "Tableau de bord", "nav.profiles": "Profils",
    "nav.records": "Registres", "nav.history": "Historique", "nav.settings": "Paramètres",
    "dashboard.title": "Tableau de bord confidentialité", "dashboard.refresh": "Actualiser",
    "dashboard.restartBannerTitle": "Redémarrez en administrateur pour appliquer les modifications",
    "dashboard.restartBannerBody": "Vous pouvez tout inspecter maintenant. La stratégie machine, DiagTrack et Copilot/Cortana nécessitent une élévation.",
    "dashboard.restartAdmin": "Redémarrer en administrateur", "dashboard.adminTitle": "Administrateur",
    "dashboard.privacyScore": "Score de confidentialité", "dashboard.outOf100": "sur 100",
    "dashboard.whyScore": "Pourquoi ce score ?", "dashboard.telemetryTitle": "Niveau de télémétrie",
    "dashboard.telemetrySubtitle": "Stratégie AllowTelemetry (0–3)",
    "dashboard.applyTelemetry": "Appliquer le niveau de télémétrie",
    "dashboard.telemetryHint": "Sécurité n’est honoré que sur Enterprise et Education. Home et Pro le traitent comme De base. Un point de restauration est créé d’abord.",
    "dashboard.howTitle": "Comment PrivacyGuard applique les modifications",
    "dashboard.howBody": "Chaque modification est confirmée, écrite uniquement via PrivacyService, sauvegardée dans SQLite et peut être annulée depuis l’Historique. Les services Windows critiques ne sont jamais touchés. Publicité et commentaires peuvent être basculés en utilisateur standard ; services et clés de stratégie nécessitent un administrateur.",
    "dashboard.requiresAdmin": "Nécessite un administrateur", "dashboard.loading": "Chargement de l’état de confidentialité…",
    "dashboard.reading": "Lecture des paramètres de confidentialité Windows…",
    "dashboard.bannerElevated": "Exécution en tant qu’administrateur. Les modifications peuvent être appliquées immédiatement.",
    "dashboard.bannerLimited": "Accès limité — redémarrez en administrateur pour modifier les services et la stratégie machine.",
    "dashboard.refreshFailed": "Impossible de lire l’état de confidentialité. Consultez les journaux.",
    "dashboard.refreshFailedTitle": "Échec de l’actualisation", "dashboard.alreadySet": "Déjà défini",
    "dashboard.alreadySetMsg": "La télémétrie est déjà à ce niveau.", "dashboard.goodShape": "Tout est en ordre",
    "dashboard.goodShapeMsg": "Le profil de confidentialité recommandé est déjà appliqué.",
    "dashboard.setTelemetry": "Définir la télémétrie sur {0}", "dashboard.enable": "Activer", "dashboard.disable": "Désactiver",
    "dashboard.confirmBody": "PrivacyGuard appliquera les modifications réversibles suivantes :\n\n{0}\n\nUn point de restauration est créé automatiquement.",
    "dashboard.changeIncomplete": "Modification incomplète", "dashboard.privacyUpdated": "Confidentialité mise à jour",
    "dashboard.finishedErrors": "Terminé avec des erreurs", "dashboard.changeFailed": "Échec de la modification",
    "dashboard.denied": "Windows a refusé la modification. Redémarrez PrivacyGuard en administrateur et réessayez.",
    "dashboard.noLocalChanges": "Aucune modification locale pour le moment", "dashboard.lastChanged": "Dernière modification {0}",
    "dashboard.updated": "Mis à jour {0}", "dashboard.improve": "Appliquer le profil recommandé",
    "dashboard.improveDone": "Profil recommandé appliqué",
    "dashboard.scoreLoading": "Lecture des paramètres de confidentialité Windows…",
    "dashboard.scoreProtected": "La plupart de la collecte facultative est limitée. Vous pouvez encore renforcer quelques services.",
    "dashboard.scorePartial": "Certaines options publicitaires et de diagnostic sont encore actives. Le profil recommandé comble les écarts.",
    "dashboard.scoreCollecting": "Windows utilise la collecte par défaut. Appliquez le profil recommandé pour une base plus sûre.",
    "health.protected": "Protégé", "health.needsAttention": "À surveiller", "health.collecting": "Collecte de données",
    "health.unknown": "Inconnu", "health.partial": "Partiel", "health.limited": "Limité", "health.mixed": "Mixte",
    "dashboard.section.core": "Télémétrie principale",
    "dashboard.section.coreSub": "Données de diagnostic que Windows peut envoyer, et les services qui les transportent.",
    "dashboard.section.ads": "Publicité et personnalisation",
    "dashboard.section.adsSub": "Identifiants et historique utilisés pour les publicités, les conseils et la Timeline.",
    "dashboard.section.ai": "IA et assistants", "dashboard.section.aiSub": "Stratégie Cortana et visibilité de Copilot sur cet appareil.",
    "dashboard.section.other": "Autres", "dashboard.section.otherSub": "Invites de commentaires et autres options de confidentialité.",
    "telemetry.security": "Sécurité — Enterprise uniquement", "telemetry.basic": "De base — recommandé",
    "telemetry.enhanced": "Amélioré", "telemetry.full": "Complet — valeur par défaut Windows",
    "telemetry.value.security": "Sécurité", "telemetry.value.basic": "De base", "telemetry.value.enhanced": "Amélioré",
    "telemetry.value.full": "Complet", "common.windowsDefault": "Valeur par défaut Windows",
    "service.running": "En cours", "service.stopped": "Arrêté", "service.automatic": "Automatique",
    "service.manual": "Manuel", "service.disabled": "Désactivé", "service.missing": "Non installé",
    "setting.telemetry": "Télémétrie Windows", "setting.diagTrack": "Expériences utilisateur connectées (DiagTrack)",
    "setting.dmw": "Routage des messages WAP Push (dmwappushservice)", "setting.advertising": "ID publicitaire",
    "setting.activity": "Historique d’activité / Timeline", "setting.cortana": "Cortana", "setting.copilot": "Windows Copilot",
    "setting.feedback": "Invites de commentaires et de diagnostic", "setting.tailored": "Expériences personnalisées",
    "setting.telemetry.desc": "Quantité de données de diagnostic que Windows peut envoyer à Microsoft (AllowTelemetry).",
    "setting.diagTrack.desc": "Implémente les expériences utilisateur connectées et la télémétrie. L’arrêter réduit la télémétrie mais peut affecter certains diagnostics.",
    "setting.dmw.desc": "Routage WAP Push utilisé dans certains scénarios de télémétrie et MDM. Sans danger à désactiver pour la plupart des particuliers.",
    "setting.advertising.desc": "Identifiant que les applications peuvent utiliser pour des publicités plus pertinentes.",
    "setting.activity.desc": "Collecte l’activité des applications et de la navigation pour la Timeline et la reprise multi-appareils.",
    "setting.cortana.desc": "Stratégie AllowCortana. Sous Windows 11, cela concerne surtout les composants Cortana restants.",
    "setting.copilot.desc": "Stratégie TurnOffWindowsCopilot. L’efficacité dépend de la build et de l’installation de Copilot.",
    "setting.feedback.desc": "Fréquence du Hub de commentaires et des enquêtes de satisfaction.",
    "setting.tailored.desc": "Utilise les données de diagnostic pour personnaliser conseils, publicités et recommandations.",
    "setting.telemetry.side": "Le niveau Sécurité réservé à Enterprise est ignoré sur Home/Pro (Windows le relève à De base).",
    "setting.diagTrack.side": "Des expériences de diagnostic facultatives et certaines fonctions de commentaires/télémétrie peuvent s’arrêter. Windows Update continue de fonctionner.",
    "setting.dmw.side": "De rares scénarios WAP Push / livraison MDM peuvent être affectés.",
    "setting.cortana.side": "Cortana (si présent) sera désactivé par stratégie. La recherche Windows reste disponible.",
    "setting.copilot.side": "L’interface Copilot peut être masquée ou ignorée selon la build. Une déconnexion peut être nécessaire.",
    "setting.activity.side": "La Timeline et la reprise d’activité entre appareils s’arrêteront.",
    "factor.telemetry": "Niveau de télémétrie", "factor.diagTrack": "DiagTrack", "factor.dmw": "Service WAP Push",
    "factor.advertising": "ID publicitaire", "factor.activity": "Historique d’activité", "factor.cortana": "Cortana",
    "factor.copilot": "Copilot", "factor.feedback": "Invites de commentaires", "factor.tailored": "Expériences personnalisées",
    "profile.recommended.title": "Confidentialité recommandée",
    "profile.recommended.summary": "Réduit la publicité et les diagnostics facultatifs tout en préservant Windows Update et la sécurité.",
    "profile.recommended.details": "Télémétrie : De base. ID publicitaire désactivé. Envoi d’activité désactivé. Commentaires désactivés. DiagTrack reste actif pour les diagnostics Update.",
    "profile.recommended.warning": "Certains conseils personnalisés, publicités et la synchro Timeline s’arrêteront. Cela n’affecte pas Windows Security ni Update.",
    "profile.recommended.h1": "Télémétrie : De base", "profile.recommended.h2": "ID publicitaire désactivé",
    "profile.recommended.h3": "Historique d’activité désactivé", "profile.recommended.h4": "Commentaires désactivés",
    "profile.recommended.h5": "DiagTrack reste actif",
    "profile.maximum.title": "Confidentialité maximale",
    "profile.maximum.summary": "Configuration la plus restrictive prise en charge. Certaines expériences Windows facultatives peuvent cesser.",
    "profile.maximum.details": "Télémétrie : Sécurité (ou De base sur Home/Pro). DiagTrack et dmwappushservice arrêtés. Publicité, historique, stratégie Cortana/Copilot et commentaires désactivés.",
    "profile.maximum.warning": "Les suggestions de recherche, la Timeline, les diagnostics facultatifs et une partie de la personnalisation du Store peuvent cesser. Réversible depuis l’Historique ou Restaurer les valeurs. Sur Home/Pro, Windows n’honore pas la télémétrie Sécurité (0).",
    "profile.maximum.h1": "Télémétrie : Sécurité ou De base", "profile.maximum.h2": "DiagTrack arrêté",
    "profile.maximum.h3": "WAP Push désactivé", "profile.maximum.h4": "Publicités, Timeline et Copilot désactivés",
    "profile.maximum.h5": "Commentaires et expériences désactivés",
    "profile.balanced.title": "Équilibré",
    "profile.balanced.summary": "Laisse les services de diagnostic actifs, désactive l’ID publicitaire et l’envoi d’activité.",
    "profile.balanced.details": "Télémétrie : Complet. DiagTrack en cours. ID publicitaire désactivé. Activité locale autorisée, envoi cloud désactivé. Copilot inchangé.",
    "profile.balanced.warning": "Windows enverra encore des données de diagnostic facultatives. Seuls la publicité et l’envoi d’activité sont réduits.",
    "profile.balanced.h1": "Télémétrie : Complet", "profile.balanced.h2": "DiagTrack en cours",
    "profile.balanced.h3": "ID publicitaire désactivé", "profile.balanced.h4": "Envoi d’activité désactivé",
    "profile.balanced.h5": "Copilot inchangé",
    "profile.restore.title": "Restaurer les valeurs",
    "profile.restore.summary": "Supprime les valeurs de stratégie PrivacyGuard et rétablit les services aux valeurs Windows habituelles.",
    "profile.restore.details": "Supprime la stratégie AllowTelemetry, réactive DiagTrack (Automatique + En cours) et restaure publicité, historique, Cortana/Copilot et commentaires.",
    "profile.restore.warning": "Cela restaure les valeurs de collecte par défaut. Cela n’annule pas les tweaks tiers sans rapport.",
    "profile.restore.h1": "Télémétrie : valeur par défaut Windows", "profile.restore.h2": "DiagTrack automatique",
    "profile.restore.h3": "ID publicitaire activé", "profile.restore.h4": "Historique d’activité activé",
    "profile.restore.h5": "Cortana et Copilot restaurés",
    "profiles.title": "Profils de confidentialité",
    "profiles.subtitle": "Configurations en un clic. Chaque application affiche une confirmation, crée un point de restauration et est entièrement réversible.",
    "profiles.safety": "Sécurité", "profiles.recommendedBadge": "Recommandé", "profiles.active": "Actif",
    "profiles.beforeContinue": "Avant de continuer", "profiles.scoreNone": "Impact sur le score : aucun changement",
    "profiles.scoreUp": "Impact sur le score : +{0}", "profiles.scoreDown": "Impact sur le score : {0}",
    "profiles.scoreUnknown": "Impact sur le score : —", "profiles.lastApplied": "Dernière application : {0} à {1}",
    "profiles.today": "Aujourd’hui", "profiles.yesterday": "Hier", "profiles.review": "Examiner et appliquer",
    "profiles.currentlyApplied": "Actuellement appliqué", "profiles.alreadyTitle": "Déjà appliqué",
    "profiles.alreadyMsg": "{0} est déjà appliqué.", "profiles.adminTitle": "Administrateur requis",
    "profiles.adminBody": "Ce profil modifie une stratégie ou des services à l’échelle de la machine. Redémarrez PrivacyGuard en administrateur, puis appliquez-le à nouveau.",
    "profiles.applyTitle": "Appliquer {0} ?", "profiles.confirmBody": "Les modifications réversibles suivantes seront appliquées :\n\n{0}",
    "profiles.appliedTitle": "Profil appliqué", "profiles.partialTitle": "Profil partiellement appliqué",
    "profiles.failedTitle": "Échec du profil", "profiles.choose": "Choisissez un profil. Chaque application crée d’abord un point de restauration.",
    "history.title": "Historique des modifications",
    "history.subtitle": "Chaque mutation est enregistrée localement. Annulez un paramètre ou restaurez un point de sauvegarde complet.",
    "history.audit": "Journal d’audit local", "history.changes": "Modifications", "history.filterAll": "Toutes",
    "history.filterActive": "Actives", "history.filterReverted": "Annulées", "history.revertSelected": "Annuler la sélection",
    "history.revertN": "Annuler {0} modifications", "history.noneSelected": "Aucune sélection",
    "history.changeSelectedOne": "1 modification sélectionnée", "history.changeSelectedMany": "{0} modifications sélectionnées",
    "history.restoreSelectedOne": "1 point de restauration sélectionné",
    "history.restoreSelectedMany": "{0} points de restauration sélectionnés",
    "history.emptyTitle": "Pas encore d’historique", "history.emptyFilterTitle": "Aucune modification correspondante",
    "history.emptyMsg": "Pas encore de modifications. Appliquez un profil ou basculez un paramètre pour l’afficher ici.",
    "history.emptyFilterMsg": "Aucune modification ne correspond à ce filtre.",
    "history.statusEmpty": "Pas encore de modifications. Les paramètres appliqués apparaîtront ici.",
    "history.statusCounts": "{0} modification(s) enregistrée(s), {1} point(s) de restauration.",
    "history.unavailable": "Historique indisponible", "history.alreadyRevertedTitle": "Déjà annulé",
    "history.alreadyRevertedBody": "Les éléments d’historique sélectionnés étaient déjà marqués comme annulés.",
    "history.revertOne": "Annuler cette modification ?", "history.revertMany": "Annuler {0} modifications ?",
    "history.revertBody": "Les modifications réversibles suivantes seront restaurées :\n\n{0}",
    "history.revertWarning": "Un nouveau point de restauration sera créé avant chaque annulation.",
    "history.revertFailed": "Échec de l’annulation", "history.restoreTitle": "Restaurer cette sauvegarde ?",
    "history.restoreBody": "Le point de restauration n° {0} du {1} sera réappliqué ({2} paramètre(s)).",
    "history.restoreWarning": "Les valeurs actuelles sont d’abord sauvegardées, cette restauration est donc elle-même réversible.",
    "history.restoreFailed": "Échec de la restauration", "history.restored": "Restauré",
    "history.restorePoints": "Points de restauration", "history.restorePointsSub": "Instantanés pris avant chaque mutation.",
    "history.noRestoreTitle": "Pas encore de points de restauration",
    "history.noRestoreBody": "Un instantané apparaîtra ici dès la première modification d’un paramètre.",
    "history.restoreButton": "Restaurer la sauvegarde sélectionnée", "history.reverted": "Annulé",
    "history.manualChange": "Modification manuelle", "history.restorePointN": "Point de restauration n° {0}",
    "history.settingKey": "Clé du paramètre : ", "history.source": "Source : ", "history.today": "Aujourd’hui",
    "history.yesterday": "Hier", "history.earlier": "Plus tôt", "history.settingCapturedOne": "1 paramètre capturé",
    "history.settingCapturedMany": "{0} paramètres capturés",
    "history.storedLocally": "L’historique des modifications est stocké localement dans SQLite.",
    "settings.title": "Paramètres",
    "settings.subtitle": "Préférences de l’application uniquement. Les paramètres de confidentialité Windows sont sur le Tableau de bord et les Profils.",
    "settings.appearance": "Apparence", "settings.theme": "Thème",
    "settings.themeDesc": "Suivre Windows, ou forcer un thème clair ou sombre.",
    "settings.themeDefault": "Valeur par défaut Windows", "settings.themeDefaultSub": "Correspondre au thème du système",
    "settings.themeLight": "Clair", "settings.themeLightSub": "Toujours utiliser le thème clair",
    "settings.themeDark": "Sombre", "settings.themeDarkSub": "Toujours utiliser le thème sombre",
    "settings.language": "Langue",
    "settings.languageDesc": "Change toute l’interface de PrivacyGuard. Les dates et les nombres suivent aussi cette langue.",
    "settings.languagePlaceholder": "Rechercher des langues", "settings.startup": "Démarrage et sécurité",
    "settings.startWindows": "Démarrer avec Windows",
    "settings.startWindowsDesc": "Ajoute ou supprime une clé Run de l’utilisateur actuel. Ne nécessite pas de droits d’administrateur.",
    "settings.confirm": "Confirmer avant d’appliquer les modifications",
    "settings.confirmDesc": "Les boîtes de confirmation s’affichent toujours avant que PrivacyGuard ne modifie Windows. Ce commutateur est verrouillé pour la sécurité.",
    "settings.confirmLock": "Toujours obligatoire pour la sécurité", "settings.record": "Enregistrer l’historique des modifications",
    "settings.recordDesc": "Écrit chaque mutation de paramètre dans la base SQLite locale.",
    "settings.data": "Données", "settings.logs": "Fichiers journaux", "settings.openFolder": "Ouvrir le dossier",
    "settings.database": "Base de l’historique", "settings.about": "À propos",
    "settings.aboutBody": "Tableau de bord unifié de confidentialité et de télémétrie pour Windows 10/11. Les modifications sont réversibles et ne ciblent jamais les services OS critiques.",
    "settings.checkUpdates": "Rechercher des mises à jour", "settings.upToDate": "Vous êtes à jour",
    "settings.upToDateBody": "PrivacyGuard 0.1.0 est la version actuelle. La recherche automatique de mises à jour sera ajoutée dans une version ultérieure.",
    "settings.autoStart": "Démarrage automatique", "settings.autoStartError": "Impossible de mettre à jour la clé Run de l’utilisateur actuel.",
    "dialog.beforeContinue": "Avant de continuer",
    "privacy.nothingToChange": "Rien à modifier — le système correspond déjà à l’état demandé.",
    "privacy.refusedUnknown": "Paramètre inconnu refusé : '{0}'.",
    "privacy.needsAdmin": "Cette modification nécessite des droits d’administrateur. Utilisez Redémarrer en administrateur, puis réessayez.",
    "privacy.applied": "{0} modification(s) appliquée(s). Le point de restauration n° {1} a été enregistré.",
    "privacy.completedErrors": "Terminé avec {0} erreur(s). Le point de restauration n° {1} est disponible.",
    "privacy.couldNotComplete": "La modification n’a pas pu être terminée. {0}",
    "privacy.revertReason": "Annuler : {0}", "privacy.restoreReason": "Point de restauration n° {0}",
    "privacy.telemetryRange": "Le niveau de télémétrie doit être compris entre 0 et 3.",
    "privacy.telemetryRestoreFail": "Impossible de restaurer la stratégie de télémétrie. Des droits d’administrateur sont requis.",
    "privacy.telemetryWriteFail": "Impossible d’écrire AllowTelemetry. Des droits d’administrateur sont requis.",
    "privacy.serviceNotAllowed": "Le service '{0}' n’est pas dans la liste autorisée.",
    "privacy.advertisingFail": "Impossible de mettre à jour l’ID publicitaire.",
    "privacy.activityFail": "Impossible de mettre à jour la stratégie d’historique d’activité. Des droits d’administrateur sont requis.",
    "privacy.cortanaRestoreFail": "Impossible de restaurer la stratégie Cortana.",
    "privacy.cortanaWriteFail": "Impossible d’écrire AllowCortana. Des droits d’administrateur sont requis.",
    "privacy.copilotRestoreFail": "Impossible de restaurer la stratégie Copilot.",
    "privacy.copilotWriteFail": "Impossible d’écrire TurnOffWindowsCopilot. Des droits d’administrateur sont requis.",
    "privacy.feedbackFail": "Impossible de mettre à jour les règles de commentaires.",
    "privacy.tailoredFail": "Impossible de mettre à jour les expériences personnalisées.",
    "privacy.notImplemented": "Le paramètre '{0}' n’est pas implémenté.", "privacy.collectingData": "Collecte de données",
}

DE = {
    "common.on": "Ein", "common.off": "Aus", "common.apply": "Übernehmen", "common.cancel": "Abbrechen",
    "common.ok": "OK", "common.refresh": "Aktualisieren", "common.required": "Erforderlich",
    "shell.standardUser": "Standardbenutzer", "shell.administrator": "Administrator",
    "shell.restartAdmin": "Als Admin neu starten",
    "nav.overview": "Übersicht", "nav.dashboard": "Dashboard", "nav.profiles": "Profile",
    "nav.records": "Einträge", "nav.history": "Verlauf", "nav.settings": "Einstellungen",
    "dashboard.title": "Datenschutz-Dashboard", "dashboard.refresh": "Aktualisieren",
    "dashboard.restartBannerTitle": "Als Administrator neu starten, um Änderungen anzuwenden",
    "dashboard.restartBannerBody": "Sie können jetzt alles einsehen. Computerrichtlinie, DiagTrack und Copilot/Cortana erfordern eine Erhöhung.",
    "dashboard.restartAdmin": "Als Administrator neu starten", "dashboard.adminTitle": "Administrator",
    "dashboard.privacyScore": "Datenschutzbewertung", "dashboard.outOf100": "von 100",
    "dashboard.whyScore": "Warum diese Bewertung?", "dashboard.telemetryTitle": "Telemetrieebene",
    "dashboard.telemetrySubtitle": "AllowTelemetry-Richtlinie (0–3)",
    "dashboard.applyTelemetry": "Telemetrieebene übernehmen",
    "dashboard.telemetryHint": "Sicherheit gilt nur für Enterprise und Education. Home und Pro behandeln sie als Basis. Zuerst wird ein Wiederherstellungspunkt erstellt.",
    "dashboard.howTitle": "So wendet PrivacyGuard Änderungen an",
    "dashboard.howBody": "Jede Änderung wird bestätigt, nur über PrivacyService geschrieben, in SQLite gesichert und kann im Verlauf rückgängig gemacht werden. Kritische Windows-Dienste werden nie angefasst. Werbung und Feedback können als Standardbenutzer umgeschaltet werden; Dienste und Richtlinienschlüssel brauchen Administratorrechte.",
    "dashboard.requiresAdmin": "Administrator erforderlich", "dashboard.loading": "Datenschutzstatus wird geladen…",
    "dashboard.reading": "Windows-Datenschutzeinstellungen werden gelesen…",
    "dashboard.bannerElevated": "Wird als Administrator ausgeführt. Änderungen können sofort angewendet werden.",
    "dashboard.bannerLimited": "Eingeschränkter Zugriff — als Administrator neu starten, um Dienste und Computerrichtlinie zu ändern.",
    "dashboard.refreshFailed": "Datenschutzstatus konnte nicht gelesen werden. Siehe Protokolle.",
    "dashboard.refreshFailedTitle": "Aktualisierung fehlgeschlagen", "dashboard.alreadySet": "Bereits festgelegt",
    "dashboard.alreadySetMsg": "Die Telemetrie ist bereits auf dieser Ebene.", "dashboard.goodShape": "Alles in Ordnung",
    "dashboard.goodShapeMsg": "Das empfohlene Datenschutzprofil ist bereits angewendet.",
    "dashboard.setTelemetry": "Telemetrie auf {0} setzen", "dashboard.enable": "Aktivieren", "dashboard.disable": "Deaktivieren",
    "dashboard.confirmBody": "PrivacyGuard wendet die folgenden umkehrbaren Änderungen an:\n\n{0}\n\nEin Wiederherstellungspunkt wird automatisch erstellt.",
    "dashboard.changeIncomplete": "Änderung nicht vollständig angewendet", "dashboard.privacyUpdated": "Datenschutz aktualisiert",
    "dashboard.finishedErrors": "Mit Fehlern abgeschlossen", "dashboard.changeFailed": "Änderung fehlgeschlagen",
    "dashboard.denied": "Windows hat die Änderung verweigert. Starten Sie PrivacyGuard als Administrator neu und versuchen Sie es erneut.",
    "dashboard.noLocalChanges": "Noch keine lokalen Änderungen", "dashboard.lastChanged": "Zuletzt geändert {0}",
    "dashboard.updated": "Aktualisiert {0}", "dashboard.improve": "Empfohlenes Profil übernehmen",
    "dashboard.improveDone": "Empfohlenes Profil angewendet",
    "dashboard.scoreLoading": "Windows-Datenschutzeinstellungen werden gelesen…",
    "dashboard.scoreProtected": "Die meiste optionale Erfassung ist eingeschränkt. Einige Dienste können noch härter konfiguriert werden.",
    "dashboard.scorePartial": "Einige Werbe- und Diagnoseoptionen sind noch aktiv. Das empfohlene Profil schließt die Lücken.",
    "dashboard.scoreCollecting": "Windows verwendet die Standarderfassung. Übernehmen Sie das empfohlene Profil für eine sicherere Basis.",
    "health.protected": "Geschützt", "health.needsAttention": "Handlungsbedarf", "health.collecting": "Daten werden erfasst",
    "health.unknown": "Unbekannt", "health.partial": "Teilweise", "health.limited": "Eingeschränkt", "health.mixed": "Gemischt",
    "dashboard.section.core": "Kerntelemetrie",
    "dashboard.section.coreSub": "Diagnosedaten, die Windows senden kann, und die Dienste, die sie übertragen.",
    "dashboard.section.ads": "Werbung und Personalisierung",
    "dashboard.section.adsSub": "Kennungen und Verlauf für Werbung, Tipps und die Timeline.",
    "dashboard.section.ai": "KI- und Assistentenfunktionen", "dashboard.section.aiSub": "Cortana-Richtlinie und Copilot-Sichtbarkeit auf diesem Gerät.",
    "dashboard.section.other": "Sonstiges", "dashboard.section.otherSub": "Feedback-Eingaben und weitere datenschutzbezogene Optionen.",
    "telemetry.security": "Sicherheit — nur Enterprise", "telemetry.basic": "Basis — empfohlen",
    "telemetry.enhanced": "Erweitert", "telemetry.full": "Vollständig — Windows-Standard",
    "telemetry.value.security": "Sicherheit", "telemetry.value.basic": "Basis", "telemetry.value.enhanced": "Erweitert",
    "telemetry.value.full": "Vollständig", "common.windowsDefault": "Windows-Standard",
    "service.running": "Wird ausgeführt", "service.stopped": "Beendet", "service.automatic": "Automatisch",
    "service.manual": "Manuell", "service.disabled": "Deaktiviert", "service.missing": "Nicht installiert",
    "setting.telemetry": "Windows-Telemetrie", "setting.diagTrack": "Connected User Experiences (DiagTrack)",
    "setting.dmw": "WAP-Push-Nachrichtenrouting (dmwappushservice)", "setting.advertising": "Werbe-ID",
    "setting.activity": "Aktivitätsverlauf / Timeline", "setting.cortana": "Cortana", "setting.copilot": "Windows Copilot",
    "setting.feedback": "Feedback- und Diagnoseaufforderungen", "setting.tailored": "Zugeschnittene Erfahrungen",
    "setting.telemetry.desc": "Wie viele Diagnosedaten Windows an Microsoft senden darf (AllowTelemetry).",
    "setting.diagTrack.desc": "Implementiert Connected User Experiences und Telemetrie. Das Beenden reduziert Telemetrie, kann aber einige Diagnosen beeinträchtigen.",
    "setting.dmw.desc": "WAP-Push-Routing für einige Telemetrie- und MDM-Szenarien. Für die meisten Heimanwender sicher deaktivierbar.",
    "setting.advertising.desc": "Kennung, mit der Apps relevantere Werbung anzeigen können.",
    "setting.activity.desc": "Erfasst App- und Browserverlauf für Timeline und geräteübergreifendes Fortsetzen.",
    "setting.cortana.desc": "Richtlinie AllowCortana. Unter Windows 11 betrifft dies vor allem verbleibende Cortana-Komponenten.",
    "setting.copilot.desc": "Richtlinie TurnOffWindowsCopilot. Die Wirkung hängt vom Windows-Build und der Copilot-Installation ab.",
    "setting.feedback.desc": "Häufigkeit des Feedback-Hubs und von Zufriedenheitsabfragen.",
    "setting.tailored.desc": "Nutzt Diagnosedaten, um Tipps, Werbung und Empfehlungen zu personalisieren.",
    "setting.telemetry.side": "Die nur für Enterprise geltende Ebene Sicherheit wird unter Home/Pro ignoriert (Windows hebt sie auf Basis an).",
    "setting.diagTrack.side": "Optionale Diagnoseerlebnisse und einige Feedback-/Telemetriefunktionen können enden. Windows Update funktioniert weiter.",
    "setting.dmw.side": "Seltene WAP-Push-/MDM-Zustellungsszenarien können betroffen sein.",
    "setting.cortana.side": "Cortana (falls vorhanden) wird per Richtlinie deaktiviert. Die Windows-Suche bleibt verfügbar.",
    "setting.copilot.side": "Die Copilot-Oberfläche kann je nach Build ausgeblendet oder ignoriert werden. Eine Abmeldung kann nötig sein.",
    "setting.activity.side": "Timeline und geräteübergreifendes Fortsetzen werden beendet.",
    "factor.telemetry": "Telemetrieebene", "factor.diagTrack": "DiagTrack", "factor.dmw": "WAP-Push-Dienst",
    "factor.advertising": "Werbe-ID", "factor.activity": "Aktivitätsverlauf", "factor.cortana": "Cortana",
    "factor.copilot": "Copilot", "factor.feedback": "Feedback-Aufforderungen", "factor.tailored": "Zugeschnittene Erfahrungen",
    "profile.recommended.title": "Empfohlener Datenschutz",
    "profile.recommended.summary": "Reduziert Werbung und optionale Diagnosen und hält Windows Update sowie die Sicherheit gesund.",
    "profile.recommended.details": "Telemetrie: Basis. Werbe-ID aus. Aktivitätsupload aus. Feedback aus. DiagTrack bleibt aktiv, damit Update-Diagnosen funktionieren.",
    "profile.recommended.warning": "Einige personalisierte Tipps, Werbung und Timeline-Sync enden. Windows Security und Update sind nicht betroffen.",
    "profile.recommended.h1": "Telemetrie: Basis", "profile.recommended.h2": "Werbe-ID aus",
    "profile.recommended.h3": "Aktivitätsverlauf aus", "profile.recommended.h4": "Feedback-Aufforderungen aus",
    "profile.recommended.h5": "DiagTrack bleibt aktiv",
    "profile.maximum.title": "Maximaler Datenschutz",
    "profile.maximum.summary": "Die restriktivste unterstützte Konfiguration. Einige optionale Windows-Erlebnisse können ausfallen.",
    "profile.maximum.details": "Telemetrie: Sicherheit (oder Basis unter Home/Pro). DiagTrack und dmwappushservice gestoppt. Werbung, Verlauf, Cortana/Copilot-Richtlinie und Feedback aus.",
    "profile.maximum.warning": "Suchhervorhebungen, Timeline, optionale Diagnosen und einige Store-Personalisierungen können ausfallen. Umkehrbar über Verlauf oder Standard wiederherstellen. Unter Home/Pro honori Windows Sicherheit (0) nicht.",
    "profile.maximum.h1": "Telemetrie: Sicherheit oder Basis", "profile.maximum.h2": "DiagTrack gestoppt",
    "profile.maximum.h3": "WAP-Push deaktiviert", "profile.maximum.h4": "Werbung, Timeline, Copilot aus",
    "profile.maximum.h5": "Feedback und zugeschnittene Erfahrungen aus",
    "profile.balanced.title": "Ausgewogen",
    "profile.balanced.summary": "Hält Diagnosedienste aktiv und schaltet Werbe-ID sowie Aktivitätsupload aus.",
    "profile.balanced.details": "Telemetrie: Vollständig. DiagTrack aktiv. Werbe-ID aus. Lokale Aktivität erlaubt, Cloud-Upload aus. Copilot unverändert.",
    "profile.balanced.warning": "Windows sendet weiterhin optionale Diagnosedaten. Nur Werbung und Aktivitätsupload werden reduziert.",
    "profile.balanced.h1": "Telemetrie: Vollständig", "profile.balanced.h2": "DiagTrack aktiv",
    "profile.balanced.h3": "Werbe-ID aus", "profile.balanced.h4": "Aktivitätsupload aus",
    "profile.balanced.h5": "Copilot unverändert",
    "profile.restore.title": "Standard wiederherstellen",
    "profile.restore.summary": "Entfernt PrivacyGuard-Richtlinienwerte und setzt Dienste auf typische Windows-Standards zurück.",
    "profile.restore.details": "Löscht die AllowTelemetry-Richtlinie, reaktiviert DiagTrack (Automatisch + Wird ausgeführt) und stellt Werbung, Verlauf, Cortana/Copilot und Feedback wieder her.",
    "profile.restore.warning": "Dies stellt die Standard-Datenerfassung wieder her. Unabhängige Drittanbieter-Tweaks werden nicht zurückgesetzt.",
    "profile.restore.h1": "Telemetrie: Windows-Standard", "profile.restore.h2": "DiagTrack automatisch",
    "profile.restore.h3": "Werbe-ID ein", "profile.restore.h4": "Aktivitätsverlauf ein",
    "profile.restore.h5": "Cortana und Copilot wiederhergestellt",
    "profiles.title": "Datenschutzprofile",
    "profiles.subtitle": "Konfigurationen mit einem Klick. Jede Übernahme zeigt eine Bestätigung, erstellt einen Wiederherstellungspunkt und ist vollständig umkehrbar.",
    "profiles.safety": "Sicherheit", "profiles.recommendedBadge": "Empfohlen", "profiles.active": "Aktiv",
    "profiles.beforeContinue": "Bevor Sie fortfahren", "profiles.scoreNone": "Auswirkung auf die Bewertung: keine Änderung",
    "profiles.scoreUp": "Auswirkung auf die Bewertung: +{0}", "profiles.scoreDown": "Auswirkung auf die Bewertung: {0}",
    "profiles.scoreUnknown": "Auswirkung auf die Bewertung: —", "profiles.lastApplied": "Zuletzt angewendet: {0} um {1}",
    "profiles.today": "Heute", "profiles.yesterday": "Gestern", "profiles.review": "Prüfen und übernehmen",
    "profiles.currentlyApplied": "Derzeit angewendet", "profiles.alreadyTitle": "Bereits angewendet",
    "profiles.alreadyMsg": "{0} ist bereits angewendet.", "profiles.adminTitle": "Administrator erforderlich",
    "profiles.adminBody": "Dieses Profil ändert computerweite Richtlinien oder Dienste. Starten Sie PrivacyGuard als Administrator neu und übernehmen Sie es erneut.",
    "profiles.applyTitle": "{0} übernehmen?", "profiles.confirmBody": "Die folgenden umkehrbaren Änderungen werden angewendet:\n\n{0}",
    "profiles.appliedTitle": "Profil angewendet", "profiles.partialTitle": "Profil teilweise angewendet",
    "profiles.failedTitle": "Profil fehlgeschlagen", "profiles.choose": "Wählen Sie ein Profil. Jede Übernahme erstellt zuerst einen Wiederherstellungspunkt.",
    "history.title": "Änderungsverlauf",
    "history.subtitle": "Jede Mutation wird lokal aufgezeichnet. Setzen Sie eine einzelne Einstellung zurück oder stellen Sie einen vollständigen Sicherungspunkt wieder her.",
    "history.audit": "Lokales Auditprotokoll", "history.changes": "Änderungen", "history.filterAll": "Alle",
    "history.filterActive": "Aktiv", "history.filterReverted": "Zurückgesetzt", "history.revertSelected": "Auswahl zurücksetzen",
    "history.revertN": "{0} Änderungen zurücksetzen", "history.noneSelected": "Keine Auswahl",
    "history.changeSelectedOne": "1 Änderung ausgewählt", "history.changeSelectedMany": "{0} Änderungen ausgewählt",
    "history.restoreSelectedOne": "1 Wiederherstellungspunkt ausgewählt",
    "history.restoreSelectedMany": "{0} Wiederherstellungspunkte ausgewählt",
    "history.emptyTitle": "Noch kein Verlauf", "history.emptyFilterTitle": "Keine passenden Änderungen",
    "history.emptyMsg": "Noch keine Änderungen. Übernehmen Sie ein Profil oder schalten Sie eine Einstellung um, damit sie hier erscheint.",
    "history.emptyFilterMsg": "Keine Änderungen entsprechen diesem Filter.",
    "history.statusEmpty": "Noch keine Änderungen. Angewendete Einstellungen erscheinen hier.",
    "history.statusCounts": "{0} aufgezeichnete Änderung(en), {1} Wiederherstellungspunkt(e).",
    "history.unavailable": "Verlauf nicht verfügbar", "history.alreadyRevertedTitle": "Bereits zurückgesetzt",
    "history.alreadyRevertedBody": "Die ausgewählten Verlaufseinträge waren bereits als zurückgesetzt markiert.",
    "history.revertOne": "Diese Änderung zurücksetzen?", "history.revertMany": "{0} Änderungen zurücksetzen?",
    "history.revertBody": "Die folgenden umkehrbaren Änderungen werden wiederhergestellt:\n\n{0}",
    "history.revertWarning": "Vor jedem Zurücksetzen wird ein neuer Wiederherstellungspunkt erstellt.",
    "history.revertFailed": "Zurücksetzen fehlgeschlagen", "history.restoreTitle": "Diese Sicherung wiederherstellen?",
    "history.restoreBody": "Wiederherstellungspunkt #{0} vom {1} wird erneut angewendet ({2} Einstellung(en)).",
    "history.restoreWarning": "Aktuelle Werte werden zuerst gesichert, daher ist auch diese Wiederherstellung umkehrbar.",
    "history.restoreFailed": "Wiederherstellung fehlgeschlagen", "history.restored": "Wiederhergestellt",
    "history.restorePoints": "Wiederherstellungspunkte", "history.restorePointsSub": "Momentaufnahmen vor jeder Mutation.",
    "history.noRestoreTitle": "Noch keine Wiederherstellungspunkte",
    "history.noRestoreBody": "Eine Momentaufnahme erscheint hier, sobald eine Einstellung geändert wird.",
    "history.restoreButton": "Ausgewählte Sicherung wiederherstellen", "history.reverted": "Zurückgesetzt",
    "history.manualChange": "Manuelle Änderung", "history.restorePointN": "Wiederherstellungspunkt #{0}",
    "history.settingKey": "Einstellungsschlüssel: ", "history.source": "Quelle: ", "history.today": "Heute",
    "history.yesterday": "Gestern", "history.earlier": "Früher", "history.settingCapturedOne": "1 Einstellung erfasst",
    "history.settingCapturedMany": "{0} Einstellungen erfasst",
    "history.storedLocally": "Der Änderungsverlauf wird lokal in SQLite gespeichert.",
    "settings.title": "Einstellungen",
    "settings.subtitle": "Nur App-Einstellungen. Die Windows-Datenschutzeinstellungen befinden sich auf Dashboard und Profile.",
    "settings.appearance": "Darstellung", "settings.theme": "Design",
    "settings.themeDesc": "Windows folgen oder ein helles bzw. dunkles Design erzwingen.",
    "settings.themeDefault": "Windows-Standard", "settings.themeDefaultSub": "Systemdesign übernehmen",
    "settings.themeLight": "Hell", "settings.themeLightSub": "Immer das helle Design verwenden",
    "settings.themeDark": "Dunkel", "settings.themeDarkSub": "Immer das dunkle Design verwenden",
    "settings.language": "Sprache",
    "settings.languageDesc": "Ändert die gesamte PrivacyGuard-Oberfläche. Daten und Zahlen folgen ebenfalls dieser Sprache.",
    "settings.languagePlaceholder": "Sprachen suchen", "settings.startup": "Start und Sicherheit",
    "settings.startWindows": "Mit Windows starten",
    "settings.startWindowsDesc": "Fügt einen Run-Schlüssel des aktuellen Benutzers hinzu oder entfernt ihn. Keine Administratorrechte nötig.",
    "settings.confirm": "Vor dem Anwenden von Änderungen bestätigen",
    "settings.confirmDesc": "Bestätigungsdialoge werden immer angezeigt, bevor PrivacyGuard Windows ändert. Dieser Schalter ist aus Sicherheitsgründen gesperrt.",
    "settings.confirmLock": "Aus Sicherheitsgründen immer erforderlich", "settings.record": "Änderungsverlauf aufzeichnen",
    "settings.recordDesc": "Schreibt jede Einstellungmutation in die lokale SQLite-Datenbank.",
    "settings.data": "Daten", "settings.logs": "Protokolldateien", "settings.openFolder": "Ordner öffnen",
    "settings.database": "Verlaufsdatenbank", "settings.about": "Info",
    "settings.aboutBody": "Einheitliches Datenschutz- und Telemetrie-Dashboard für Windows 10/11. Änderungen sind umkehrbar und betreffen nie kritische Betriebssystemdienste.",
    "settings.checkUpdates": "Nach Updates suchen", "settings.upToDate": "Sie sind auf dem neuesten Stand",
    "settings.upToDateBody": "PrivacyGuard 0.1.0 ist der aktuelle Build. Automatische Updateprüfungen werden in einer späteren Version hinzugefügt.",
    "settings.autoStart": "Autostart", "settings.autoStartError": "Der Run-Schlüssel des aktuellen Benutzers konnte nicht aktualisiert werden.",
    "dialog.beforeContinue": "Bevor Sie fortfahren",
    "privacy.nothingToChange": "Nichts zu ändern — das System entspricht bereits dem gewünschten Zustand.",
    "privacy.refusedUnknown": "Unbekannte Einstellung '{0}' abgelehnt.",
    "privacy.needsAdmin": "Diese Änderung erfordert Administratorrechte. Nutzen Sie Als Administrator neu starten und versuchen Sie es erneut.",
    "privacy.applied": "{0} Änderung(en) angewendet. Wiederherstellungspunkt #{1} wurde gespeichert.",
    "privacy.completedErrors": "Mit {0} Fehler(n) abgeschlossen. Wiederherstellungspunkt #{1} ist verfügbar.",
    "privacy.couldNotComplete": "Die Änderung konnte nicht abgeschlossen werden. {0}",
    "privacy.revertReason": "Zurücksetzen: {0}", "privacy.restoreReason": "Wiederherstellungspunkt #{0}",
    "privacy.telemetryRange": "Die Telemetrieebene muss 0–3 sein.",
    "privacy.telemetryRestoreFail": "Die Telemetrierichtlinie konnte nicht wiederhergestellt werden. Administratorrechte sind erforderlich.",
    "privacy.telemetryWriteFail": "AllowTelemetry konnte nicht geschrieben werden. Administratorrechte sind erforderlich.",
    "privacy.serviceNotAllowed": "Dienst '{0}' steht nicht auf der Positivliste.",
    "privacy.advertisingFail": "Die Werbe-ID konnte nicht aktualisiert werden.",
    "privacy.activityFail": "Die Aktivitätsverlauf-Richtlinie konnte nicht aktualisiert werden. Administratorrechte sind erforderlich.",
    "privacy.cortanaRestoreFail": "Die Cortana-Richtlinie konnte nicht wiederhergestellt werden.",
    "privacy.cortanaWriteFail": "AllowCortana konnte nicht geschrieben werden. Administratorrechte sind erforderlich.",
    "privacy.copilotRestoreFail": "Die Copilot-Richtlinie konnte nicht wiederhergestellt werden.",
    "privacy.copilotWriteFail": "TurnOffWindowsCopilot konnte nicht geschrieben werden. Administratorrechte sind erforderlich.",
    "privacy.feedbackFail": "Feedbackregeln konnten nicht aktualisiert werden.",
    "privacy.tailoredFail": "Zugeschnittene Erfahrungen konnten nicht aktualisiert werden.",
    "privacy.notImplemented": "Einstellung '{0}' ist nicht implementiert.", "privacy.collectingData": "Daten werden erfasst",
}
