"""Italian, Chinese, Japanese, Russian, and Arabic maps."""

IT = {
    "common.on": "Attivato", "common.off": "Disattivato", "common.apply": "Applica", "common.cancel": "Annulla",
    "common.ok": "OK", "common.refresh": "Aggiorna", "common.required": "Obbligatorio",
    "shell.standardUser": "Utente standard", "shell.administrator": "Amministratore",
    "shell.restartAdmin": "Riavvia come admin",
    "nav.overview": "Panoramica", "nav.dashboard": "Dashboard", "nav.profiles": "Profili",
    "nav.records": "Registri", "nav.history": "Cronologia", "nav.settings": "Impostazioni",
    "dashboard.title": "Dashboard privacy", "dashboard.refresh": "Aggiorna",
    "dashboard.restartBannerTitle": "Riavvia come amministratore per applicare le modifiche",
    "dashboard.restartBannerBody": "Puoi già ispezionare tutto. Criteri del computer, DiagTrack e Copilot/Cortana richiedono elevazione.",
    "dashboard.restartAdmin": "Riavvia come amministratore", "dashboard.adminTitle": "Amministratore",
    "dashboard.privacyScore": "Punteggio privacy", "dashboard.outOf100": "su 100",
    "dashboard.whyScore": "Perché questo punteggio?", "dashboard.telemetryTitle": "Livello di telemetria",
    "dashboard.telemetrySubtitle": "Criterio AllowTelemetry (0–3)",
    "dashboard.applyTelemetry": "Applica livello di telemetria",
    "dashboard.telemetryHint": "Sicurezza è rispettato solo su Enterprise e Education. Home e Pro lo trattano come Base. Prima viene creato un punto di ripristino.",
    "dashboard.howTitle": "Come PrivacyGuard applica le modifiche",
    "dashboard.howBody": "Ogni modifica è confermata, scritta solo tramite PrivacyService, salvata in SQLite e può essere annullata dalla Cronologia. I servizi Windows critici non vengono mai toccati. Pubblicità e feedback si possono cambiare come utente standard; servizi e chiavi dei criteri richiedono amministratore.",
    "dashboard.requiresAdmin": "Richiede amministratore", "dashboard.loading": "Caricamento stato privacy…",
    "dashboard.reading": "Lettura delle impostazioni privacy di Windows…",
    "dashboard.bannerElevated": "In esecuzione come amministratore. Le modifiche possono essere applicate subito.",
    "dashboard.bannerLimited": "Accesso limitato: riavvia come amministratore per cambiare servizi e criteri del computer.",
    "dashboard.refreshFailed": "Impossibile leggere lo stato privacy. Consulta i log.",
    "dashboard.refreshFailedTitle": "Aggiornamento non riuscito", "dashboard.alreadySet": "Già impostato",
    "dashboard.alreadySetMsg": "La telemetria è già a questo livello.", "dashboard.goodShape": "Tutto a posto",
    "dashboard.goodShapeMsg": "Il profilo privacy consigliato è già applicato.",
    "dashboard.setTelemetry": "Imposta telemetria su {0}", "dashboard.enable": "Attiva", "dashboard.disable": "Disattiva",
    "dashboard.confirmBody": "PrivacyGuard applicherà le seguenti modifiche reversibili:\n\n{0}\n\nUn punto di ripristino viene creato automaticamente.",
    "dashboard.changeIncomplete": "Modifica non applicata del tutto", "dashboard.privacyUpdated": "Privacy aggiornata",
    "dashboard.finishedErrors": "Completato con errori", "dashboard.changeFailed": "Modifica non riuscita",
    "dashboard.denied": "Windows ha rifiutato la modifica. Riavvia PrivacyGuard come amministratore e riprova.",
    "dashboard.noLocalChanges": "Nessuna modifica locale ancora", "dashboard.lastChanged": "Ultima modifica {0}",
    "dashboard.updated": "Aggiornato {0}", "dashboard.improve": "Applica profilo consigliato",
    "dashboard.improveDone": "Profilo consigliato applicato",
    "dashboard.scoreLoading": "Lettura delle impostazioni privacy di Windows…",
    "dashboard.scoreProtected": "La maggior parte della raccolta facoltativa è limitata. Puoi ancora rafforzare alcuni servizi.",
    "dashboard.scorePartial": "Alcune opzioni pubblicitarie e diagnostiche sono ancora attive. Il profilo consigliato chiude le lacune.",
    "dashboard.scoreCollecting": "Windows usa la raccolta predefinita. Applica il profilo consigliato per una base più sicura.",
    "health.protected": "Protetto", "health.needsAttention": "Richiede attenzione", "health.collecting": "Raccolta dati",
    "health.unknown": "Sconosciuto", "health.partial": "Parziale", "health.limited": "Limitato", "health.mixed": "Misto",
    "dashboard.section.core": "Telemetria principale",
    "dashboard.section.coreSub": "Dati diagnostici che Windows può inviare e i servizi che li trasportano.",
    "dashboard.section.ads": "Pubblicità e personalizzazione",
    "dashboard.section.adsSub": "Identificatori e cronologia usati per annunci, suggerimenti e Timeline.",
    "dashboard.section.ai": "IA e assistenti", "dashboard.section.aiSub": "Criterio Cortana e visibilità di Copilot su questo dispositivo.",
    "dashboard.section.other": "Altro", "dashboard.section.otherSub": "Richieste di feedback e altre opzioni sulla privacy.",
    "telemetry.security": "Sicurezza — solo Enterprise", "telemetry.basic": "Base — consigliato",
    "telemetry.enhanced": "Avanzato", "telemetry.full": "Completo — predefinito Windows",
    "telemetry.value.security": "Sicurezza", "telemetry.value.basic": "Base", "telemetry.value.enhanced": "Avanzato",
    "telemetry.value.full": "Completo", "common.windowsDefault": "Predefinito Windows",
    "service.running": "In esecuzione", "service.stopped": "Arrestato", "service.automatic": "Automatico",
    "service.manual": "Manuale", "service.disabled": "Disabilitato", "service.missing": "Non installato",
    "setting.telemetry": "Telemetria Windows", "setting.diagTrack": "Esperienze utente connesse (DiagTrack)",
    "setting.dmw": "Instradamento messaggi WAP Push (dmwappushservice)", "setting.advertising": "ID pubblicità",
    "setting.activity": "Cronologia attività / Timeline", "setting.cortana": "Cortana", "setting.copilot": "Windows Copilot",
    "setting.feedback": "Richieste di feedback e diagnostica", "setting.tailored": "Esperienze personalizzate",
    "setting.telemetry.desc": "Quanti dati diagnostici Windows può inviare a Microsoft (AllowTelemetry).",
    "setting.diagTrack.desc": "Implementa Esperienze utente connesse e Telemetria. Arrestarlo riduce la telemetria ma può influire su alcune diagnostiche.",
    "setting.dmw.desc": "Instradamento WAP Push usato in alcuni scenari di telemetria e MDM. Sicuro da disattivare per la maggior parte degli utenti home.",
    "setting.advertising.desc": "Identificatore che le app possono usare per annunci più pertinenti.",
    "setting.activity.desc": "Raccoglie attività di app e navigazione per Timeline e ripresa tra dispositivi.",
    "setting.cortana.desc": "Criterio AllowCortana. Su Windows 11 riguarda soprattutto i componenti Cortana rimasti.",
    "setting.copilot.desc": "Criterio TurnOffWindowsCopilot. L’efficacia dipende dalla build e da come è installato Copilot.",
    "setting.feedback.desc": "Frequenza del Feedback Hub e dei sondaggi di soddisfazione.",
    "setting.tailored.desc": "Usa i dati diagnostici per personalizzare suggerimenti, annunci e raccomandazioni.",
    "setting.telemetry.side": "Il livello Sicurezza solo Enterprise viene ignorato su Home/Pro (Windows lo alza a Base).",
    "setting.diagTrack.side": "Esperienze diagnostiche facoltative e alcune funzioni di feedback/telemetria possono fermarsi. Windows Update continua a funzionare.",
    "setting.dmw.side": "Scenari rari di WAP Push / recapito MDM possono essere interessati.",
    "setting.cortana.side": "Cortana (se presente) verrà disabilitata da criterio. La ricerca Windows resta disponibile.",
    "setting.copilot.side": "L’interfaccia Copilot può essere nascosta o ignorata a seconda della build. Potrebbe servire una disconnessione.",
    "setting.activity.side": "Timeline e ripresa attività tra dispositivi si interromperanno.",
    "factor.telemetry": "Livello di telemetria", "factor.diagTrack": "DiagTrack", "factor.dmw": "Servizio WAP Push",
    "factor.advertising": "ID pubblicità", "factor.activity": "Cronologia attività", "factor.cortana": "Cortana",
    "factor.copilot": "Copilot", "factor.feedback": "Richieste di feedback", "factor.tailored": "Esperienze personalizzate",
    "profile.recommended.title": "Privacy consigliata",
    "profile.recommended.summary": "Riduce pubblicità e diagnostica facoltativa mantenendo Windows Update e la sicurezza in salute.",
    "profile.recommended.details": "Telemetria: Base. ID pubblicità disattivato. Caricamento attività disattivato. Feedback disattivato. DiagTrack resta in esecuzione per la diagnostica di Update.",
    "profile.recommended.warning": "Alcuni suggerimenti personalizzati, annunci e la sincronizzazione Timeline si fermeranno. Non influisce su Windows Security o Update.",
    "profile.recommended.h1": "Telemetria: Base", "profile.recommended.h2": "ID pubblicità disattivato",
    "profile.recommended.h3": "Cronologia attività disattivata", "profile.recommended.h4": "Feedback disattivato",
    "profile.recommended.h5": "DiagTrack resta in esecuzione",
    "profile.maximum.title": "Privacy massima",
    "profile.maximum.summary": "Configurazione più restrittiva supportata. Alcune esperienze Windows facoltative possono interrompersi.",
    "profile.maximum.details": "Telemetria: Sicurezza (o Base su Home/Pro). DiagTrack e dmwappushservice arrestati. Pubblicità, cronologia, criterio Cortana/Copilot e feedback disattivati.",
    "profile.maximum.warning": "In evidenza nella ricerca, Timeline, diagnostica facoltativa e parte della personalizzazione dello Store possono smettere di funzionare. Reversibile da Cronologia o Ripristina predefiniti. Su Home/Pro Windows non rispetta la telemetria Sicurezza (0).",
    "profile.maximum.h1": "Telemetria: Sicurezza o Base", "profile.maximum.h2": "DiagTrack arrestato",
    "profile.maximum.h3": "WAP Push disabilitato", "profile.maximum.h4": "Annunci, Timeline e Copilot disattivati",
    "profile.maximum.h5": "Feedback ed esperienze disattivati",
    "profile.balanced.title": "Bilanciato",
    "profile.balanced.summary": "Mantiene i servizi diagnostici attivi e disattiva ID pubblicità e caricamento attività.",
    "profile.balanced.details": "Telemetria: Completa. DiagTrack in esecuzione. ID pubblicità disattivato. Attività locale consentita, caricamento cloud disattivato. Copilot invariato.",
    "profile.balanced.warning": "Windows continuerà a inviare dati diagnostici facoltativi. Si riducono solo pubblicità e caricamento attività.",
    "profile.balanced.h1": "Telemetria: Completa", "profile.balanced.h2": "DiagTrack in esecuzione",
    "profile.balanced.h3": "ID pubblicità disattivato", "profile.balanced.h4": "Caricamento attività disattivato",
    "profile.balanced.h5": "Copilot invariato",
    "profile.restore.title": "Ripristina predefiniti",
    "profile.restore.summary": "Rimuove i valori dei criteri PrivacyGuard e riporta i servizi ai valori tipici di Windows.",
    "profile.restore.details": "Elimina il criterio AllowTelemetry, riattiva DiagTrack (Automatico + In esecuzione) e ripristina pubblicità, cronologia, Cortana/Copilot e feedback.",
    "profile.restore.warning": "Questo ripristina i valori predefiniti di raccolta dati. Non annulla modifiche di terze parti non correlate.",
    "profile.restore.h1": "Telemetria: predefinito Windows", "profile.restore.h2": "DiagTrack automatico",
    "profile.restore.h3": "ID pubblicità attivato", "profile.restore.h4": "Cronologia attività attivata",
    "profile.restore.h5": "Cortana e Copilot ripristinati",
    "profiles.title": "Profili privacy",
    "profiles.subtitle": "Configurazioni con un clic. Ogni applicazione mostra una conferma, crea un punto di ripristino ed è completamente reversibile.",
    "profiles.safety": "Sicurezza", "profiles.recommendedBadge": "Consigliato", "profiles.active": "Attivo",
    "profiles.beforeContinue": "Prima di continuare", "profiles.scoreNone": "Impatto sul punteggio: nessun cambiamento",
    "profiles.scoreUp": "Impatto sul punteggio: +{0}", "profiles.scoreDown": "Impatto sul punteggio: {0}",
    "profiles.scoreUnknown": "Impatto sul punteggio: —", "profiles.lastApplied": "Ultima applicazione: {0} alle {1}",
    "profiles.today": "Oggi", "profiles.yesterday": "Ieri", "profiles.review": "Rivedi e applica",
    "profiles.currentlyApplied": "Attualmente applicato", "profiles.alreadyTitle": "Già applicato",
    "profiles.alreadyMsg": "{0} è già applicato.", "profiles.adminTitle": "Amministratore richiesto",
    "profiles.adminBody": "Questo profilo modifica criteri o servizi a livello di computer. Riavvia PrivacyGuard come amministratore e applicalo di nuovo.",
    "profiles.applyTitle": "Applicare {0}?", "profiles.confirmBody": "Verranno applicate le seguenti modifiche reversibili:\n\n{0}",
    "profiles.appliedTitle": "Profilo applicato", "profiles.partialTitle": "Profilo applicato parzialmente",
    "profiles.failedTitle": "Profilo non riuscito", "profiles.choose": "Scegli un profilo. Ogni applicazione crea prima un punto di ripristino.",
    "history.title": "Cronologia modifiche",
    "history.subtitle": "Ogni mutazione è registrata in locale. Annulla una singola impostazione o ripristina un punto di backup completo.",
    "history.audit": "Registro di controllo locale", "history.changes": "Modifiche", "history.filterAll": "Tutte",
    "history.filterActive": "Attive", "history.filterReverted": "Annullate", "history.revertSelected": "Annulla selezionate",
    "history.revertN": "Annulla {0} modifiche", "history.noneSelected": "Nessuna selezione",
    "history.changeSelectedOne": "1 modifica selezionata", "history.changeSelectedMany": "{0} modifiche selezionate",
    "history.restoreSelectedOne": "1 punto di ripristino selezionato",
    "history.restoreSelectedMany": "{0} punti di ripristino selezionati",
    "history.emptyTitle": "Nessuna cronologia ancora", "history.emptyFilterTitle": "Nessuna modifica corrispondente",
    "history.emptyMsg": "Ancora nessuna modifica. Applica un profilo o cambia un’impostazione per vederla qui.",
    "history.emptyFilterMsg": "Nessuna modifica corrisponde a questo filtro.",
    "history.statusEmpty": "Ancora nessuna modifica. Le impostazioni applicate appariranno qui.",
    "history.statusCounts": "{0} modifica/e registrata/e, {1} punto/i di ripristino.",
    "history.unavailable": "Cronologia non disponibile", "history.alreadyRevertedTitle": "Già annullato",
    "history.alreadyRevertedBody": "Gli elementi di cronologia selezionati erano già contrassegnati come annullati.",
    "history.revertOne": "Annullare questa modifica?", "history.revertMany": "Annullare {0} modifiche?",
    "history.revertBody": "Verranno ripristinate le seguenti modifiche reversibili:\n\n{0}",
    "history.revertWarning": "Un nuovo punto di ripristino verrà creato prima di ogni annullamento.",
    "history.revertFailed": "Annullamento non riuscito", "history.restoreTitle": "Ripristinare questo backup?",
    "history.restoreBody": "Il punto di ripristino n. {0} del {1} verrà riapplicato ({2} impostazione/i).",
    "history.restoreWarning": "I valori attuali vengono salvati prima, quindi anche questo ripristino è reversibile.",
    "history.restoreFailed": "Ripristino non riuscito", "history.restored": "Ripristinato",
    "history.restorePoints": "Punti di ripristino", "history.restorePointsSub": "Istantanee scattate prima di ogni mutazione.",
    "history.noRestoreTitle": "Nessun punto di ripristino ancora",
    "history.noRestoreBody": "Un’istantanea apparirà qui la prima volta che un’impostazione viene modificata.",
    "history.restoreButton": "Ripristina backup selezionato", "history.reverted": "Annullato",
    "history.manualChange": "Modifica manuale", "history.restorePointN": "Punto di ripristino n. {0}",
    "history.settingKey": "Chiave impostazione: ", "history.source": "Origine: ", "history.today": "Oggi",
    "history.yesterday": "Ieri", "history.earlier": "Precedente", "history.settingCapturedOne": "1 impostazione acquisita",
    "history.settingCapturedMany": "{0} impostazioni acquisite",
    "history.storedLocally": "La cronologia delle modifiche è archiviata in locale in SQLite.",
    "settings.title": "Impostazioni",
    "settings.subtitle": "Solo preferenze dell’app. Le impostazioni privacy di Windows sono in Dashboard e Profili.",
    "settings.appearance": "Aspetto", "settings.theme": "Tema",
    "settings.themeDesc": "Segui Windows oppure forza un tema chiaro o scuro.",
    "settings.themeDefault": "Predefinito Windows", "settings.themeDefaultSub": "Corrispondi al tema di sistema",
    "settings.themeLight": "Chiaro", "settings.themeLightSub": "Usa sempre il tema chiaro",
    "settings.themeDark": "Scuro", "settings.themeDarkSub": "Usa sempre il tema scuro",
    "settings.language": "Lingua",
    "settings.languageDesc": "Cambia l’intera interfaccia di PrivacyGuard. Date e numeri seguono questa lingua.",
    "settings.languagePlaceholder": "Cerca lingue", "settings.startup": "Avvio e sicurezza",
    "settings.startWindows": "Avvia con Windows",
    "settings.startWindowsDesc": "Aggiunge o rimuove una chiave Run dell’utente corrente. Non richiede diritti di amministratore.",
    "settings.confirm": "Conferma prima di applicare le modifiche",
    "settings.confirmDesc": "I dialoghi di conferma sono sempre mostrati prima che PrivacyGuard modifichi Windows. Questo interruttore è bloccato per sicurezza.",
    "settings.confirmLock": "Sempre obbligatorio per sicurezza", "settings.record": "Registra cronologia modifiche",
    "settings.recordDesc": "Scrive ogni mutazione di impostazione nel database SQLite locale.",
    "settings.data": "Dati", "settings.logs": "File di log", "settings.openFolder": "Apri cartella",
    "settings.database": "Database cronologia", "settings.about": "Informazioni",
    "settings.aboutBody": "Dashboard unificata di privacy e telemetria per Windows 10/11. Le modifiche sono reversibili e non coinvolgono mai servizi OS critici.",
    "settings.checkUpdates": "Controlla aggiornamenti", "settings.upToDate": "Sei aggiornato",
    "settings.upToDateBody": "PrivacyGuard 0.1.0 è la build attuale. I controlli automatici degli aggiornamenti saranno aggiunti in una versione successiva.",
    "settings.autoStart": "Avvio automatico", "settings.autoStartError": "Impossibile aggiornare la chiave Run dell’utente corrente.",
    "dialog.beforeContinue": "Prima di continuare",
    "privacy.nothingToChange": "Niente da cambiare: il sistema corrisponde già allo stato richiesto.",
    "privacy.refusedUnknown": "Impostazione sconosciuta rifiutata: '{0}'.",
    "privacy.needsAdmin": "Questa modifica richiede diritti di amministratore. Usa Riavvia come amministratore e riprova.",
    "privacy.applied": "Applicate {0} modifica/e. Salvato il punto di ripristino n. {1}.",
    "privacy.completedErrors": "Completato con {0} errore/i. Il punto di ripristino n. {1} è disponibile.",
    "privacy.couldNotComplete": "Impossibile completare la modifica. {0}",
    "privacy.revertReason": "Annulla: {0}", "privacy.restoreReason": "Punto di ripristino n. {0}",
    "privacy.telemetryRange": "Il livello di telemetria deve essere 0–3.",
    "privacy.telemetryRestoreFail": "Impossibile ripristinare il criterio di telemetria. Servono diritti di amministratore.",
    "privacy.telemetryWriteFail": "Impossibile scrivere AllowTelemetry. Servono diritti di amministratore.",
    "privacy.serviceNotAllowed": "Il servizio '{0}' non è nell’elenco consentito.",
    "privacy.advertisingFail": "Impossibile aggiornare l’ID pubblicità.",
    "privacy.activityFail": "Impossibile aggiornare il criterio Cronologia attività. Servono diritti di amministratore.",
    "privacy.cortanaRestoreFail": "Impossibile ripristinare il criterio Cortana.",
    "privacy.cortanaWriteFail": "Impossibile scrivere AllowCortana. Servono diritti di amministratore.",
    "privacy.copilotRestoreFail": "Impossibile ripristinare il criterio Copilot.",
    "privacy.copilotWriteFail": "Impossibile scrivere TurnOffWindowsCopilot. Servono diritti di amministratore.",
    "privacy.feedbackFail": "Impossibile aggiornare le regole di feedback.",
    "privacy.tailoredFail": "Impossibile aggiornare le esperienze personalizzate.",
    "privacy.notImplemented": "L’impostazione '{0}' non è implementata.", "privacy.collectingData": "Raccolta dati",
}

ZH = {
    "common.on": "开", "common.off": "关", "common.apply": "应用", "common.cancel": "取消",
    "common.ok": "确定", "common.refresh": "刷新", "common.required": "必需",
    "shell.standardUser": "标准用户", "shell.administrator": "管理员", "shell.restartAdmin": "以管理员身份重启",
    "nav.overview": "概览", "nav.dashboard": "仪表板", "nav.profiles": "配置", "nav.records": "记录",
    "nav.history": "历史", "nav.settings": "设置",
    "dashboard.title": "隐私仪表板", "dashboard.refresh": "刷新",
    "dashboard.restartBannerTitle": "请以管理员身份重启以应用更改",
    "dashboard.restartBannerBody": "你现在可以查看所有内容。计算机策略、DiagTrack 以及 Copilot/Cortana 需要提升权限。",
    "dashboard.restartAdmin": "以管理员身份重启", "dashboard.adminTitle": "管理员",
    "dashboard.privacyScore": "隐私评分", "dashboard.outOf100": "满分 100", "dashboard.whyScore": "为什么是这个分数？",
    "dashboard.telemetryTitle": "遥测级别", "dashboard.telemetrySubtitle": "AllowTelemetry 策略（0–3）",
    "dashboard.applyTelemetry": "应用遥测级别",
    "dashboard.telemetryHint": "“安全”仅在企业版和教育版生效。家庭版和专业版会将其视为“基本”。会先创建还原点。",
    "dashboard.howTitle": "PrivacyGuard 如何应用更改",
    "dashboard.howBody": "每次更改都会先确认，仅通过 PrivacyService 写入，备份到 SQLite，并可从历史记录还原。绝不会改动关键 Windows 服务。广告和反馈可由标准用户切换；服务和策略项需要管理员权限。",
    "dashboard.requiresAdmin": "需要管理员", "dashboard.loading": "正在加载隐私状态…",
    "dashboard.reading": "正在读取 Windows 隐私设置…",
    "dashboard.bannerElevated": "正在以管理员身份运行。可以立即应用更改。",
    "dashboard.bannerLimited": "权限有限 — 请以管理员身份重启以更改服务和计算机策略。",
    "dashboard.refreshFailed": "无法读取隐私状态。请查看日志。",
    "dashboard.refreshFailedTitle": "刷新失败", "dashboard.alreadySet": "已是该级别",
    "dashboard.alreadySetMsg": "遥测已经是此级别。", "dashboard.goodShape": "状态良好",
    "dashboard.goodShapeMsg": "推荐的隐私配置已应用。",
    "dashboard.setTelemetry": "将遥测设为 {0}", "dashboard.enable": "启用", "dashboard.disable": "禁用",
    "dashboard.confirmBody": "PrivacyGuard 将应用以下可还原的更改：\n\n{0}\n\n将自动创建还原点。",
    "dashboard.changeIncomplete": "更改未完全应用", "dashboard.privacyUpdated": "隐私已更新",
    "dashboard.finishedErrors": "已完成但有错误", "dashboard.changeFailed": "更改失败",
    "dashboard.denied": "Windows 拒绝了此更改。请以管理员身份重启 PrivacyGuard 后重试。",
    "dashboard.noLocalChanges": "尚无本地更改", "dashboard.lastChanged": "上次更改 {0}",
    "dashboard.updated": "已更新 {0}", "dashboard.improve": "应用推荐配置",
    "dashboard.improveDone": "已应用推荐配置",
    "dashboard.scoreLoading": "正在读取 Windows 隐私设置…",
    "dashboard.scoreProtected": "大部分可选收集已被限制。你仍可进一步收紧部分服务。",
    "dashboard.scorePartial": "部分广告和诊断选项仍处于开启状态。推荐配置可补上缺口。",
    "dashboard.scoreCollecting": "Windows 正在使用默认收集。应用推荐配置可获得更安全的基线。",
    "health.protected": "已保护", "health.needsAttention": "需要注意", "health.collecting": "正在收集数据",
    "health.unknown": "未知", "health.partial": "部分", "health.limited": "受限", "health.mixed": "混合",
    "dashboard.section.core": "核心遥测",
    "dashboard.section.coreSub": "Windows 可能发送的诊断数据以及承载这些数据的服务。",
    "dashboard.section.ads": "广告与个性化",
    "dashboard.section.adsSub": "用于广告、提示和时间线的标识符与历史记录。",
    "dashboard.section.ai": "AI 与助手功能", "dashboard.section.aiSub": "此设备上的 Cortana 策略和 Copilot 可见性。",
    "dashboard.section.other": "其他", "dashboard.section.otherSub": "反馈提示及其他与隐私相关的选项。",
    "telemetry.security": "安全 — 仅企业版", "telemetry.basic": "基本 — 推荐",
    "telemetry.enhanced": "增强", "telemetry.full": "完整 — Windows 默认",
    "telemetry.value.security": "安全", "telemetry.value.basic": "基本", "telemetry.value.enhanced": "增强",
    "telemetry.value.full": "完整", "common.windowsDefault": "Windows 默认",
    "service.running": "正在运行", "service.stopped": "已停止", "service.automatic": "自动",
    "service.manual": "手动", "service.disabled": "已禁用", "service.missing": "未安装",
    "setting.telemetry": "Windows 遥测", "setting.diagTrack": "连接用户体验 (DiagTrack)",
    "setting.dmw": "WAP 推送消息路由 (dmwappushservice)", "setting.advertising": "广告 ID",
    "setting.activity": "活动历史记录 / 时间线", "setting.cortana": "Cortana", "setting.copilot": "Windows Copilot",
    "setting.feedback": "反馈与诊断提示", "setting.tailored": "量身定制的体验",
    "setting.telemetry.desc": "Windows 可向 Microsoft 发送多少诊断数据（AllowTelemetry）。",
    "setting.diagTrack.desc": "实现连接用户体验和遥测。停止该服务可减少遥测，但可能影响部分诊断。",
    "setting.dmw.desc": "部分遥测和 MDM 场景使用的 WAP 推送路由。大多数家庭用户可安全禁用。",
    "setting.advertising.desc": "应用可用于展示更相关广告的标识符。",
    "setting.activity.desc": "收集应用和浏览活动，用于时间线和跨设备继续。",
    "setting.cortana.desc": "AllowCortana 策略。在 Windows 11 上主要影响残留的 Cortana 组件。",
    "setting.copilot.desc": "TurnOffWindowsCopilot 策略。效果取决于 Windows 版本和 Copilot 的安装方式。",
    "setting.feedback.desc": "反馈中心和满意度提示的频率。",
    "setting.tailored.desc": "使用诊断数据个性化提示、广告和建议。",
    "setting.telemetry.side": "仅企业版的“安全”级别在家庭版/专业版上会被忽略（Windows 会提升为“基本”）。",
    "setting.diagTrack.side": "可选诊断体验和部分反馈/遥测功能可能会停止。Windows Update 仍可工作。",
    "setting.dmw.side": "少见的 WAP 推送 / 某些 MDM 交付场景可能受影响。",
    "setting.cortana.side": "Cortana（如存在）将被策略禁用。Windows 搜索本身仍然可用。",
    "setting.copilot.side": "根据 Windows 版本，Copilot 界面可能被隐藏或忽略。可能需要注销。",
    "setting.activity.side": "时间线和跨设备活动继续将停止。",
    "factor.telemetry": "遥测级别", "factor.diagTrack": "DiagTrack", "factor.dmw": "WAP 推送服务",
    "factor.advertising": "广告 ID", "factor.activity": "活动历史记录", "factor.cortana": "Cortana",
    "factor.copilot": "Copilot", "factor.feedback": "反馈提示", "factor.tailored": "量身定制的体验",
    "profile.recommended.title": "推荐隐私",
    "profile.recommended.summary": "减少广告和可选诊断，同时保持 Windows Update 和安全功能正常。",
    "profile.recommended.details": "遥测：基本。广告 ID 关闭。活动上传关闭。反馈提示关闭。DiagTrack 保持运行以便 Update 诊断。",
    "profile.recommended.warning": "部分个性化提示、广告和时间线同步将停止。不影响 Windows 安全或更新。",
    "profile.recommended.h1": "遥测：基本", "profile.recommended.h2": "广告 ID 关闭",
    "profile.recommended.h3": "活动历史记录关闭", "profile.recommended.h4": "反馈提示关闭",
    "profile.recommended.h5": "DiagTrack 保持运行",
    "profile.maximum.title": "最高隐私",
    "profile.maximum.summary": "支持的最严格配置。部分可选 Windows 体验可能无法使用。",
    "profile.maximum.details": "遥测：安全（家庭版/专业版为基本）。DiagTrack 和 dmwappushservice 已停止。广告、活动历史、Cortana/Copilot 策略和反馈均关闭。",
    "profile.maximum.warning": "搜索亮点、时间线、可选诊断以及部分商店个性化可能停止。可从历史记录或恢复默认还原。家庭版/专业版不会遵守“安全”(0) 遥测。",
    "profile.maximum.h1": "遥测：安全或基本", "profile.maximum.h2": "DiagTrack 已停止",
    "profile.maximum.h3": "WAP 推送已禁用", "profile.maximum.h4": "广告、时间线、Copilot 关闭",
    "profile.maximum.h5": "反馈与定制体验关闭",
    "profile.balanced.title": "平衡",
    "profile.balanced.summary": "保持诊断服务运行，关闭广告 ID 和活动上传。",
    "profile.balanced.details": "遥测：完整。DiagTrack 运行中。广告 ID 关闭。允许本地活动，关闭云上传。Copilot 保持不变。",
    "profile.balanced.warning": "Windows 仍会发送可选诊断数据。仅减少广告和活动上传。",
    "profile.balanced.h1": "遥测：完整", "profile.balanced.h2": "DiagTrack 运行中",
    "profile.balanced.h3": "广告 ID 关闭", "profile.balanced.h4": "活动上传关闭",
    "profile.balanced.h5": "Copilot 不变",
    "profile.restore.title": "恢复默认",
    "profile.restore.summary": "移除 PrivacyGuard 策略值，并将服务恢复为典型的 Windows 默认值。",
    "profile.restore.details": "删除 AllowTelemetry 策略，重新启用 DiagTrack（自动 + 运行），并将广告 ID、活动历史、Cortana/Copilot 和反馈恢复为默认。",
    "profile.restore.warning": "这将恢复数据收集默认值。不会回滚无关的第三方调整。",
    "profile.restore.h1": "遥测：Windows 默认", "profile.restore.h2": "DiagTrack 自动",
    "profile.restore.h3": "广告 ID 开启", "profile.restore.h4": "活动历史记录开启",
    "profile.restore.h5": "已恢复 Cortana 和 Copilot",
    "profiles.title": "隐私配置",
    "profiles.subtitle": "一键配置。每次应用都会确认、创建还原点，并且完全可还原。",
    "profiles.safety": "安全", "profiles.recommendedBadge": "推荐", "profiles.active": "当前",
    "profiles.beforeContinue": "继续之前", "profiles.scoreNone": "评分影响：无变化",
    "profiles.scoreUp": "评分影响：+{0}", "profiles.scoreDown": "评分影响：{0}",
    "profiles.scoreUnknown": "评分影响：—", "profiles.lastApplied": "上次应用：{0} {1}",
    "profiles.today": "今天", "profiles.yesterday": "昨天", "profiles.review": "查看并应用",
    "profiles.currentlyApplied": "当前已应用", "profiles.alreadyTitle": "已应用",
    "profiles.alreadyMsg": "{0} 已应用。", "profiles.adminTitle": "需要管理员",
    "profiles.adminBody": "此配置会更改计算机范围的策略或服务。请以管理员身份重启 PrivacyGuard，然后再次应用。",
    "profiles.applyTitle": "应用 {0}？", "profiles.confirmBody": "将应用以下可还原的更改：\n\n{0}",
    "profiles.appliedTitle": "已应用配置", "profiles.partialTitle": "配置部分应用",
    "profiles.failedTitle": "配置失败", "profiles.choose": "选择一个配置。每次应用都会先创建还原点。",
    "history.title": "更改历史",
    "history.subtitle": "每次更改都在本地记录。可还原单项设置或完整备份点。",
    "history.audit": "本地审计日志", "history.changes": "更改", "history.filterAll": "全部",
    "history.filterActive": "有效", "history.filterReverted": "已还原", "history.revertSelected": "还原所选",
    "history.revertN": "还原 {0} 项更改", "history.noneSelected": "未选择",
    "history.changeSelectedOne": "已选择 1 项更改", "history.changeSelectedMany": "已选择 {0} 项更改",
    "history.restoreSelectedOne": "已选择 1 个还原点",
    "history.restoreSelectedMany": "已选择 {0} 个还原点",
    "history.emptyTitle": "尚无历史记录", "history.emptyFilterTitle": "没有匹配的更改",
    "history.emptyMsg": "还没有更改。应用配置或切换设置后会显示在这里。",
    "history.emptyFilterMsg": "没有符合此筛选条件的更改。",
    "history.statusEmpty": "还没有更改。已应用的设置将显示在这里。",
    "history.statusCounts": "已记录 {0} 项更改，{1} 个还原点。",
    "history.unavailable": "历史记录不可用", "history.alreadyRevertedTitle": "已还原",
    "history.alreadyRevertedBody": "所选历史项已被标记为已还原。",
    "history.revertOne": "还原此更改？", "history.revertMany": "还原 {0} 项更改？",
    "history.revertBody": "将还原以下可逆更改：\n\n{0}",
    "history.revertWarning": "每次还原前都会创建新的还原点。",
    "history.revertFailed": "还原失败", "history.restoreTitle": "恢复此备份？",
    "history.restoreBody": "将重新应用来自 {1} 的还原点 #{0}（{2} 项设置）。",
    "history.restoreWarning": "会先备份当前值，因此这次恢复本身也可还原。",
    "history.restoreFailed": "恢复失败", "history.restored": "已恢复",
    "history.restorePoints": "还原点", "history.restorePointsSub": "每次更改前拍摄的快照。",
    "history.noRestoreTitle": "尚无还原点",
    "history.noRestoreBody": "首次更改设置时，快照会显示在这里。",
    "history.restoreButton": "恢复所选备份", "history.reverted": "已还原",
    "history.manualChange": "手动更改", "history.restorePointN": "还原点 #{0}",
    "history.settingKey": "设置键：", "history.source": "来源：", "history.today": "今天",
    "history.yesterday": "昨天", "history.earlier": "更早", "history.settingCapturedOne": "已捕获 1 项设置",
    "history.settingCapturedMany": "已捕获 {0} 项设置",
    "history.storedLocally": "更改历史存储在本地 SQLite 中。",
    "settings.title": "设置",
    "settings.subtitle": "仅应用偏好。Windows 隐私设置位于仪表板和配置页面。",
    "settings.appearance": "外观", "settings.theme": "主题",
    "settings.themeDesc": "跟随 Windows，或强制使用浅色或深色主题。",
    "settings.themeDefault": "Windows 默认", "settings.themeDefaultSub": "与系统主题一致",
    "settings.themeLight": "浅色", "settings.themeLightSub": "始终使用浅色主题",
    "settings.themeDark": "深色", "settings.themeDarkSub": "始终使用深色主题",
    "settings.language": "语言",
    "settings.languageDesc": "更改整个 PrivacyGuard 界面。日期和数字也遵循此语言。",
    "settings.languagePlaceholder": "搜索语言", "settings.startup": "启动与安全",
    "settings.startWindows": "随 Windows 启动",
    "settings.startWindowsDesc": "添加或删除当前用户的 Run 项。不需要管理员权限。",
    "settings.confirm": "应用更改前确认",
    "settings.confirmDesc": "PrivacyGuard 更改 Windows 之前始终显示确认对话框。此开关出于安全考虑已锁定。",
    "settings.confirmLock": "出于安全始终必需", "settings.record": "记录更改历史",
    "settings.recordDesc": "将每次设置更改写入本地 SQLite 数据库。",
    "settings.data": "数据", "settings.logs": "日志文件", "settings.openFolder": "打开文件夹",
    "settings.database": "历史数据库", "settings.about": "关于",
    "settings.aboutBody": "面向 Windows 10/11 的统一隐私与遥测控制仪表板。更改可还原，且从不针对关键系统服务。",
    "settings.checkUpdates": "检查更新", "settings.upToDate": "已是最新",
    "settings.upToDateBody": "PrivacyGuard 0.1.0 是当前版本。自动检查更新将在后续版本中加入。",
    "settings.autoStart": "自动启动", "settings.autoStartError": "无法更新当前用户的 Run 项。",
    "dialog.beforeContinue": "继续之前",
    "privacy.nothingToChange": "无需更改 — 系统已处于请求的状态。",
    "privacy.refusedUnknown": "已拒绝未知设置“{0}”。",
    "privacy.needsAdmin": "此更改需要管理员权限。请使用“以管理员身份重启”，然后重试。",
    "privacy.applied": "已应用 {0} 项更改。已保存还原点 #{1}。",
    "privacy.completedErrors": "完成时有 {0} 个错误。还原点 #{1} 可用。",
    "privacy.couldNotComplete": "无法完成更改。{0}",
    "privacy.revertReason": "还原：{0}", "privacy.restoreReason": "还原点 #{0}",
    "privacy.telemetryRange": "遥测级别必须为 0–3。",
    "privacy.telemetryRestoreFail": "无法还原遥测策略。需要管理员权限。",
    "privacy.telemetryWriteFail": "无法写入 AllowTelemetry。需要管理员权限。",
    "privacy.serviceNotAllowed": "服务“{0}”不在允许列表中。",
    "privacy.advertisingFail": "无法更新广告 ID。",
    "privacy.activityFail": "无法更新活动历史策略。需要管理员权限。",
    "privacy.cortanaRestoreFail": "无法还原 Cortana 策略。",
    "privacy.cortanaWriteFail": "无法写入 AllowCortana。需要管理员权限。",
    "privacy.copilotRestoreFail": "无法还原 Copilot 策略。",
    "privacy.copilotWriteFail": "无法写入 TurnOffWindowsCopilot。需要管理员权限。",
    "privacy.feedbackFail": "无法更新反馈规则。",
    "privacy.tailoredFail": "无法更新量身定制的体验。",
    "privacy.notImplemented": "设置“{0}”尚未实现。", "privacy.collectingData": "正在收集数据",
}
